<wc:init></wc:init>
{~
@view = \Base::instance()->get('view');

@orderalt = @view->orderalt;
@col_arrow = @view->col_arrow;
@page = @view->page;
@data = &@page->items;
@pgsize = "?pgsize=" . @view->pgsize;
@ubase =  @view->url . @pgsize . "&orderby=";

~}

<div class='outerwrap pad10'>
    <div class="container-fluid">
        <check if="{{ @page->last > 1 }}"><true>
            &nbsp; | &nbsp;<link-to href="{{ @link }}" text="First" />
            &nbsp; | &nbsp;<link-to href="{{ @link . '&page='. @page->before  }}" text="Previous" />
            &nbsp; | &nbsp;<link-to href="{{ @link . '&page=' . @page->next  }}" text="Next" />
            &nbsp; | &nbsp;<link-to href="{{ @link .  '&page=' . @page->last  }}" text="Last" />
            </true>
            <false>
                
            </false>
        </check>
        &nbsp;|&nbsp;  {{ @page->current . "/" . @page->last }}
        &nbsp;|&nbsp;  
        <a href="/admin/member/new" >New Record</a> &nbsp;|&nbsp;  
        
        <div class="row">
            <div class="col-1">
                # <span ><link-to href="{{ @ubase . @orderalt.name }}" text="Name" />{{ @col_arrow.name }}</span>
            </div>
            <div class="col-2">
                <span class=""><link-to href="{{ @ubase . @orderalt.surname }}" text="Surname" />{{ @col_arrow.surname }}</span>
            </div>
            <div class="col-3">
                <span class=""><link-to href="{{ @ubase . @orderalt.email }}" text="Email" />{{ @col_arrow.email }}</span>
            </div>
            <div class="col-2">
                <span class=""><link-to href="{{ @ubase . @orderalt.phone }}" text="Phone" />{{ @col_arrow.phone }}</span>
            </div>
            <div class="col-2">
                <span class=""><link-to href="{{ @ubase . @orderalt.city }}" text="Suburb" />{{ @col_arrow.city }}</span>
            </div>
            <div class="col-1">
                <span class=""><link-to href="{{ @ubase . @orderalt.cdate }}" text="Created" />{{ @col_arrow.cdate }}</span>
            </div>
            <div class="col-1">
                <span class=""><link-to href="{{ @ubase . @orderalt.status }}" text="Status" />{{ @col_arrow.status }}</span>
            </div>
        </div>
        <hr>
        <style>
            .row-striped div.row:nth-of-type(odd) {
                background-color: aliceblue;
            }
            .row-striped div.row:nth-of-type(even) {
                background-color: azure;
            }            
        </style>
        {~ @rno = 0; ~}
        <div class="row-striped">
        <repeat group="{{ @data }}" value="{{ @row }}">
            {~ @rno += 1; ~}
            <div class="row">
                <div class="col-3">
                    {{ @rno }} <link-to href="{{ '/admin/member/edit/' . @row.id }}" text="{{ @row.fname . ' &nbsp; ' . @row.lname }}"></link-to>
                </div>
                <div class="col-3">
                    {{ @row.email_address }}
                </div>
                <div class="col-2">
                    {{ @row.phone }}
                </div>
                <div class="col-2">
                    {{ @row.city }}
                </div>
                <div class="col-1">
                    {{ @row.create_date }}
                </div>
                <div class="col-1">
                    {{ @row.email_status }}
                </div>
            </div>
        </repeat>
        </div>
    </div>
</div>