<wc:init></wc:init>
{~
@view = Base::instance()->get('view');
@link = @view->link;
@url = @view->url;
@linkery = @view->linkery;
@collections = @view->collections;

@display = \Pcan\DB\Links::display();
@urltypes = @link->getUrlTypes();
~}

<style>
    label {
        font-weight:bold;
        min-width: 10em;
        text-align: right;
        padding-right: 0.5em;
        padding-top:10px;
    }
    

    .col-restrict {
        max-width: 70%;
    }
    #date_created {
        max-width: 15em;
    };
</style>

<div class="container-fluid outerwrap pad10">


    <div class="row">
        <div class="col-4">
            <a href="/dash">Dash</a> &nbsp; >> &nbsp; 
            <a href="/admin/link">Links</a> &nbsp; >> &nbsp; 
            <span>{{ @view->title }}</span>
        </div>

        <check if="{{ @link.refid }}">
            <true>
            <div class="col-2">
                <link-to href="{{ '/admin/blog/edit/' . @link.refid }}" text="Edit Target Blog" target="_blank" class="btn btn-default"></link-to>
            </div>
            </true>
        </check>
        <check if="{{ isset(@linkery) }}"><true>
            <div class="col-2">
                <form id="addLinkery" action="/admin/linkery/add" method="post">
                    <hidden name="linkid" value="{{ @link.id }}"></hidden>
                    <hidden name="gallid" value="{{ @linkery.id }}"></hidden>
                    <submit-btn value="{{ 'Add to linkery ' . @linkery.name }}" class="btn btn-primary"></submit-btn>
                </form>
            </div>
            </true></check>

    </div>
    <check if="{{ count(@collections) }}"><true>
        <div class="row" >
            <div class="col-1">
                <label><b>Collections</b></label>
            </div>
            <div class="col-11">
                <p>
                <repeat group="{{ @collections }}" value="{{ @coll  }}">
                    {{ @coll.name . "&nbsp[" . @coll.id . "]&nbsp; | &nbsp;" }}
                </repeat>
                </p>
            </div>
        </div>
        </true></check>
    <hr />
    <div class="clear"></div>
    <form id="linkform" name="linkform" method="post" action="{{ @view->post }}" onsubmit="smotePost()">
        <check if="{{ @link.refid }}">
            <true>
            <hidden name="refid" value="{{ @link.refid }}" />
            </true>
        </check>
        <div class='row'>
            <label class="col-form-label" for='sitename'>Site Name</label>
            <text-field name='sitename' value="{{ @link.sitename }}" maxlength="{{  @display.sitename.max }}" ></text-field>
        </div>
        <div class='row'>
            <label class="col-form-label" for='title'>Title</label>
            <text-field class="col-restrict" name='title' value="{{ @link.title }}" maxlength="{{  @display.title.max }}" size="80"  ></text-field>
        </div>

        <div class="row">
            <label class="col-form-label" for='url'>URL</label>
            <text-field class="col-restrict" name='url'  value="{{ @link.url }}" maxlength="{{  @display.url.max }}" size="80"  ></text-field>
        </div>
        <div class='row pad10'>
            <div class="col-3">
                <label class="col-form-label">Enabled</label>
                <checkbox name='enabled' checked="{{ @link.enabled }}"  ></checkbox>
            </div>
            <check if="{{ @view->linkid > 0 }}">
                <true>
                <div class="col-5">
                    <datetime size="20" label="Created at" name="date_created" id="date_created" value="{{ @link.date_created }}"></datetime>
                    
                </div>
                </true>
            </check>
            <hidden name="id" value="{{ @link.id }}" />
            <div>
                <label class="col-4" for='url'>URL Type</label>
                <select-menu name="urltype"  list="{{ @urltypes }}" value="{{ @link.urltype }}"></select-menu>
            </div>
        </div>
        <div>
            <button id="airbtn" type="button" 
                    title="This also does a save-submit" 
                    onclick="codeSwitch()">Switch to 'Air-Mode'</button>
        </div>
        <div class="clear"></div>
        <div class="form-group">
            <textarea id='summary' name='summary' cols='100' rows='25'>{{ @link.summary }}</textarea>
            <hr>
            <check if="{{ @view->linkid==0 }}"><true>
                <div class="col-sm-2">
                    <input name='btnUpdate' class='btn btn-success' type='submit' id='btnupdate' value="Create">
                </div>
                </true>
                <false>
                <div class="form-group row" >
                    <div class="col-sm-3">
                        <input name='btnDelete' class='btn btn-danger' type='button' id='btndelete' value="Delete" onclick="return doDelete(this.form);"/>
                    </div>
                    <div class="col-sm-6">
                        <input name='btnUpdate' class='btn btn-success' type='submit' id='btnupdate' value="Update">
                    </div>
                </div>
                </false>
            </check>
        </div>
    </form>
</div>





