<?php 
$theme = $f3->get('theme');
?>
<style>
    nav  {
        background-image: url("<?=$theme?>/tile-fog.png");
        color:lightcoral;
    }
    ul.navbar-nav a {
        font-size:1.2em;
    }
    .nav-link {
        font-weight:bold;
    }
    .navbar-brand {
        padding-top:0;
        padding-bottom:0;
    }
    .navbar {
        padding:0 0;
        margin: 0 0;
    }

</style>

<nav class="navbar navbar-expand-lg navbar-light ">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
            <?php $this->insert('generated/dropdowns',$this->data) ?>
        </ul>
    </div>
</nav>