<?php
$event = $m->event ?? null;
$hasEvent = !empty($event);
$eblog = $m->eblog ?? null;
$reg = $m->register ?? null;
$assets->add(['bootstrap', 'validate']);
$m->title="Register";
$formid = $m->formid;
$xcheck = $m->xcheck;
$google = $m->google;
?>

<style>
    .label {
        min-width:10em; 
        text-align:right;
        padding-right:10px;
        font-weight:bold;
    }
    .eblog {
        padding: 1.0em;
        background-color: lavenderblush;
    }
    #regform {
        padding: 1.0em;
    }
    .title-1 {
        font-size:1.3em;
    }
    .checkbox {
         font-weight:bold;
         margin-left:10em;
    }
    .title-2 {
        font-size:1.6em;
        font-weight:bolder;
    }
    .notice {
        padding:10px;
        border-style: groove;
        border-color:lightgreen;
    }
    .error {
        color:red;
    }
    
</style>

<div class="container body-wrap">
    
    <div class="row">
        <div class="col text-center">
            <p class="title-1">This event is fully subscribed.<br>
                Only cancellations can allow new registration.
            </p>
            <?php if($hasEvent): ?>
            <p class="title-2"> <?= $eblog->title ?></p>
            <?php endif ?>
        </div>

    </div>


</div>
        <?php if ($hasEvent && !empty($reg->linkcode)): ?>
    <div class="row">
        <div class="outerwrap notice">
            <p>Important Online Details</p>
            <?= $event->reg_detail; ?>
        </div>
    </div>
    <?php endif ?>
    <?php if ($hasEvent): ?>

    <div class="eblog">
        
        <div class="<?= $eblog->style ?>">
            <?= $eblog->article ?>
        </div>
    </div>
<?php else: ?>
        <p>Event Page not found</p>
<?php endif; ?>
</div>


<?php
$blob = <<<EOJS
<script>
function formid_submit() {
    var fm = $("#$formid");
    var purl = fm.attr('action');
    var request_method =fm.attr("method");
    var form_data = fm.serialize();

    $.ajax({
            type: request_method,
            url:  purl,
            data: form_data
        }).done(function(response) {
             $("#regform").html(response);
        }) ;
        
    $("#submit").hide();
    $("#loading").show();
}    
</script>
EOJS;
$assets->addJS($blob);
?>

<?php
$blob = <<<EOJS
<script>
function doprep() {
    prep_valid();  
};
window.onload = doprep; 
</script>
EOJS;
$assets->addJS($blob);
?>