<?php
$event = $m->event ?? null;
$eblog = $m->eblog ?? null;

$hasEvent = !empty($event) && !empty($eblog);
$reg = $m->register ?? null;
$assets->add(['bootstrap', 'register-js']);
$m->title="Register";
?>

<style>
    .label {
        min-width:10em; 
        text-align:right;
        padding-right:10px;
        font-weight:bold;
    }
    .eblog {
        padding: 1.0em;
        background-color: lavenderblush;
    }
    #regform {
        padding: 1.0em;
    }
    .title-1 {
        font-size:1.3em;
    }
    .title-2 {
        font-size:1.6em;
        font-weight:bolder;
    }
    .notice {
        padding:10px;
        border-style: groove;
        border-color:lightgreen;
    }
    
</style>

<div class="container body-wrap">
    
    <div class="row">
        <div class="col text-center">
            <p class="title-1">Registration Page for Event:</p>
            <?php if($hasEvent): ?>
            <p class="title-2"> <?= $eblog->title ?></p>
            <?php endif ?>
        </div>
    </div>
        <?php if ($hasEvent && !empty($reg->linkcode)): ?>
    <div class="row">
        <div class="outerwrap notice">
            <p>A registration form already exists for the email <?= $reg->email ?></p>
            <p>
        </div>
    </div>
    <?php endif ?>
    <?php if ($hasEvent): ?>
            <form id="regevt" method="post" action="/register/resend">
            <div id="regform">
                <?= $this->partial('events/resend') ?>
            </div>
        </form>
    <div class="eblog">   
        <div class="<?= $eblog->style?>">
            <?= $eblog->article?>
        </div>
    </div>
<?php else: ?>
        <p>Event Page not found</p>
<?php endif; ?>
</div>