
Hi <?= $m->userName ?>,
Your event registration link.

This email has been sent by a registration event form on site  <?= $m->domain ?>.
Thank you very much taking this step to participate.<!-- comment -->
<?php if (isset($m->text_detail)): ?>
Additional details:
<?= $m->text_detail ?>

<?php endif ?>
 
 The following link enables you to view all the event details and links online.
It also permits you to change or delete your registration : 
<?= $m->link ?>



