
{~ 
    @view = \Base::instance()->get('view');
    @domain = @view->publicUrl;
    @link = @domain . @view->confirmUrl;
~}
<p style="color:#000;font-size: 16px;line-height:24px;font-family:Verdana,Helvetica,Arial,sans-serif;font-weight:normal;">

<h2 style="font-size: 14px;font-family:Verdana,Helvetica,Arial,sans-serif;">Reset Your Password</h2>

<p style="font-size: 13px;line-height:24px;font-family:Verdana,Helvetica,Arial,sans-serif;">To reset the password for the parracan.org account associated with your email, click on the button below. If you don't want to reset your password, please disregard this email.

<br>
This is temporary reset link sent on {{ @view->sendDate }} from {{ @site }} at {{ @domain }}.
<br>  
<a style="background:#E86537;color:#fff;padding:10px" href="{{ @link }}">{{ @link }}</a>
<br>
</p>


