{~ 
    @view = \Base::instance()->get('view');
    @menulist = @view->menulist;
    @url = @view->url;
    @item = @view->item;
    @rootId = @view->rootId;
~}

<style>
    label.control-label {
        min-width:110px;
        text-align:right;
        margin-right:10px;
    }
    
    span.input-group-addon {
        display: inline-table;
    }
    a.btn {
        margin-left:50px;
    }
</style>
<div class='container-fluid outerwrap'>
<div class='row'>
    <div class='col-2'>
        <link-to href="{{ @url }}" text="Menus List" class="btn btn-outline-primary"></link-to>
    </div>
    <check if="{{ @item.parent  }}"><true>
    <link-to href="{{ @url . 'edit?m0=' . @item.parent }}" text="Parent" class="btn btn-outline-primary"></link-to>
    </true><false>
    <span><b>New Menu</b></span>
    </false>
</check>   
    <div class='col-3'>
<check if="{{ @item.id  }}"><true>
    <span><b>Edit Sub-Menu #{{ @item.id  }}</b></span>
    </true><false>
    <span><b>New Menu</b></span>
    </false>
</check>   
    </div>
</div>
    <hr>
<form action="{{ @url . "post"}}" method="post">
    <check if="{{ @item.id  }}"><true>
        <hidden name="id" value="{{ @item.id  }}"></hidden>
    </true>
    <false>
        <checkbox name="isRoot" value="1" ></checkbox>
        <label for="isRoot" >Is a main menu</label>
    </false>
    </check>
<div class='row'>
    <label for="caption" class="control-label">Caption</label>
    <text-field name="caption" value="{{ @item.caption }}"></text-field>
</div>
<div class='row'>
    <label for="caption" class="control-label">Controller</label>
    <text-field name="controller" value="{{ @item.controller }}"></text-field>
</div>
<div class='row'>
    <label for="caption" class="control-label">Action</label>
    <text-field name="action" value="{{ @item.action }}"></text-field>
</div>
<div class='row'>
     <label for="caption" class="control-label">User Role</label>
     <text-field name="user_role" value="{{ @item.user_role }}"></text-field>
</div>
<div class='row'>
     <label for="caption" class="control-label">Class</label>
    <text-field name="class" value="{{ @item.class }}"></text-field>
</div>
<div class='row'>
     <label for="caption" class="control-label">Language Id</label>
     <text-field name="lang_id" value="{{ @item.lang_id }}"></text-field>
</div>
<div class='row'>
     <label for="parent" class="control-label">Parent</label>
     <text-field name="parent" value="{{ @item.parent }}"></text-field>
</div>
<div class='row'>
     <label for="serial" class="control-label">Serial</label>
     <text-field name="serial" value="{{ @item.serial }}"></text-field>
</div>
<div class='row center'>
    <submit-btn value="Save" class="btn btn-primary"></submit-btn>
    
</div>
</form>
<check if="{{ @item.id  }}"><true>
    <hr>
    <form method="post" action="{{ @url . 'delete'}}">
         <hidden name="id" value="{{ @item.id  }}"></hidden>
         <submit-btn value="Delete" class="btn btn-warning"></submit-btn>
    </form>
        
</true></check>

</div>

        

