
<p style="color:#000;font-size: 16px;line-height:24px;font-family:Verdana,Helvetica,Arial,sans-serif;font-weight:normal;">

<h2 style="font-size: 14px;font-family:Verdana,Helvetica,Arial,sans-serif;">Reset Your Password</h2>

<p style="font-size: 13px;line-height:24px;font-family:Verdana,Helvetica,Arial,sans-serif;">
    Hi, <br>

You asked for a reset password from <?= $m->site ?> site<br> 
at <?= $m->domain ?> at local timestamp of  <?= $m->sendDate ?>.<br>
Below is a temporary password reset link.<br><br>

Copy and paste it onto your browser URL to get new password dialog.

Link: <br>
<?= $m->link ?><br>  
<br>
</p>


