<?php
$gem = $this->htmlgem;
$assets->add(['bootstrap', 'DateTime']);
$url = "/admin/donation/";
$donate = $m->donation;
$member = $m->member;
$m->title = "Credits";
$name = $member->fname . ' ' .$member->lname;
?>
<style>
    label.label {
        padding-right:10px;
        min-width:120px;
        text-align:right;
        font-weight:bold;
        vertical-align: top;
    }
    .row {
        padding-bottom:10px;
    }
    textarea {
        resize: both;
    }
</style>
<div class="container">
<div class="row">
            <div class="previous"><?= $gem->linkTo(['href' => $url . "index", 'text' => 'Donations']) ?></div>
</div>

<div class="page-header">
    <h1>Money Contributions</h1>
    <div>
        <p>Member: 
        <?= $gem->linkTo(['href'=> '/admin/member/edit/' . $member->id, 'text'=>$name ]) ?></p>
    </div>
</div>

<?php echo $this->getContent(); ?>

<form action="<?= $url ?>save" class="form-horizontal" method="post">

<div class="row">
    <div class="col-sm-5">
        <?= $gem->plainText(['label' => 'Amount', 'name' => "amount", "type" => "number", 'inlabel' => 'Amount', 'value' => $donate->amount]) ?>
    </div>
</div>

<div class="row">
    <div class="col-sm-5">
        <?= $gem->select(['label' => 'Purpose', 'name' => "purpose",   "class" => "selectpicker", 'list' => $m->purpose, 'value' => $donate->purpose]) ?>
    </div>
</div>
<div class="row">
    <div class="col">
        <?= $gem->multiline(['label' => 'Details', 'name' => "detail", 'value' => $donate->detail])?>
    </div>
</div>
<div class="row">
    <div class="col-sm-5">
        <?= $gem->datetime(['label' => 'Entered', 'name' => "created_at", "size" => 20, 'value' => $donate->created_at]) ?>
    </div>
        <div class="col-sm-5">
       <?= $gem->datetime(['label' => 'Date for', 'name' => "member_date", "size" => 20,'value' => $donate->member_date ]) ?>
    </div>
</div>



        <?= $gem->hidden(['name' => "id", "value" => $donate->id]) ?>
    <?= $gem->hidden(['name' => "memberid", "value" => $donate->memberid]) ?>

    <div class="row">
        <div class="col-sm-offset-2 col-sm-10">
            <?= $gem->submit(['value' => 'Save']) ?>
        </div>
    </div>
</form>
</div>