<?php
$gem = $this->htmlgem;
$assets->add(['bootstrap', 'DateTime']);
$url = "/admin/donation/";
$donate = $m->donation;
?>
<style>
    label.label {
        min-width:120px;
        text-align:right;
        font-weight:bold;
    }
</style>
<div class="container">
<div class="row">
            <div class="previous"><?= $gem->linkTo(['href' => $url . "index", 'text' => 'Donations']) ?></div>
</div>

<div class="page-header">
    <h1>Edit donation</h1>
</div>

<?php echo $this->getContent(); ?>

<form action="<?= $url ?>save" class="form-horizontal" method="post">

<div class="row">
    <div class="col-sm-5">
        <?= $gem->plainText(['in-label' => 'Amount', 'name' => "amount", "type" => "number", 'inlabel' => 'Amount', 'value' => $donate->amount]) ?>
    </div>
</div>

<div class="row">
    <div class="col-sm-5">
        <?= $gem->select(['in-label' => 'Purpose', 'name' => "purpose",   "class" => "selectpicker", 'list' => $m->purpose, 'value' => $donate->purpose]) ?>
    </div>
</div>

<div class="row">
    <div class="col-sm-5">
        <?= $gem->datetime(['in-label' => 'Entered', 'name' => "created_at", "size" => 20, 'value' => $donate->created_at]) ?>
    </div>
        <div class="col-sm-5">
       <?= $gem->datetime(['in-label' => 'Date for', 'name' => "member_date", "size" => 20,'value' => $donate->member_date ]) ?>
    </div>
</div>



        <?= $gem->hidden(['name' => "id", "value" => $donate->id]) ?>
    <?= $gem->hidden(['name' => "memberid", "value" => $donate->memberid]) ?>

    <div class="row">
        <div class="col-sm-offset-2 col-sm-10">
            <?= $gem->submit(['value' => 'Save']) ?>
        </div>
    </div>
</form>
</div>