<?php
use WC\HtmlGem as Gem;
$assets->add(['bootstrap','select', 'DateTime']);
$tag = $this->tag;
$url = "/admin/donation/";
?>
<style>
    .outerwrap {
        padding:15px;
    }
</style>
<div class="container">
    <div class="outerwrap">
<div class="page-header">
    <h1>Search donations</h1>
</div>

<?php echo $this->getContent() ?>

<?php echo $this->flash->output() ?>

<form action="<?= $url . 'search' ?>"  class="form-horizontal" method="get">
    <div class="form-group">
    <div class="col-sm-5">
        <?= Gem::datetime(['name' => 'fromdate', 'in-label' => 'From Date', "class" => "date"]) ?>
    </div>
        <div class="col-sm-5">
        <?= Gem::datetime(['name' => 'todate', 'in-label' => 'To Date', "class" => "date"]) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-10">
        <?= Gem::select([ 'list' => ['donate' => 'Donation', 'member' => 'Membership' ], 
                'name'=> "purpose", 'in-label' => 'Purpose' , "size" => 30, "class" => "selectpicker"]) ?>
    </div>
</div>



    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <?= Gem::submit(['name' => "Search", "class" => "btn-lg"]) ?>
        </div>
    </div>
</form>
    </div>
</div>