<?php
// This is a insert 
$gem = $this->htmlgem;
$catset = $m->catset;
$catList = $catset->catlist;
$catValues = implode(",",$catset->available);
$catBlogId = $catset->cat_blogid;
$chkct = count($catList);
$url=$m->url;
?>

<?php if($chkct > 0): 
      $rowid = 0; ?>
<p>&nbsp;<em>Unselected categories are: </em><?= $catValues ?></p>
<table class='table table-striped'>
    <tbody><tr>
            <?php foreach( $catList as $cat):
                if ($rowid % 3 === 0): ?>
                    </tr><tr>
             <?php  endif;   
             $rowid += 1;
             $catid = "cat" . $rowid;   
             $checked = ($cat['blog_id'] > 0) ? 1 : 0;
             ?>    
         <td class='leftCell'><?= $gem->checkbox(['name'=>$catid, 'value'=> $cat['id'], 'checked' => $checked]) ?>
             <?=$cat['name']?></td>
   <?php endforeach ?>
   </tr>
   <tr><td><input type='submit' value='Update' class='btn-danger' /></td>
   </tr>
    </tbody>
    </table>
    <input type='hidden' name='chkct' value='<?= $chkct ?>' />
    <input type='hidden' name='blogid' value='<?= $catBlogId ?>' />
<?php endif ?>
