<?php
$links = $m->links;
$linkery = $m->linkery;
$fm = $this->form();
?>


<div class="container body-wrap">
    <?php if (!empty($links)): 
        $rowId = 0;

?>
        <div id="mgrid"  data-columns>
            <?php foreach($links as $fup):
                 $url = $fup['url'];
                    $lid = 'lnky=' . $linkery['id'];
                    
                    if ($url !== '/') :
                        if (strpos( $url, '?')===false):
                            $url .= '?' . $lid;
                        else:
                            $url .= '&' . $lid;
                        endif;
                   endif;   ?>
            
                <div class='mitem' id="<?= 'lnk' . $fup['id'] ?>">
                    <div class="wrap-item">
                    <div style="padding:10px; width:100%; overflow-x:auto;">
                        <span class="title-area" >
                            <span class="link-title">
                                <a href="<?= $url ?>"><?= $fup['title'] ?></a>
                            </span>
                            <?php if ($fup['urltype']==='Event' ): ?>                         
                                <div class="float-right"><?= $fm->datetime_value(['value' => $fup['date_created'],
                                    'format' => 'd F Y' ]) ?></div>
                                <div class='clear'></div>
                           <?php endif; ?>
                        </span>    
                        <?= $fup['summary'] ?>
                        <div class='clear'></div>
                        <a href="<?= $url ?>">Full article ...</a>
                    </div>
                    </div>
                </div>
                <?php endforeach; ?>
        </div>
<?php else: ?>
        <p>No Link records here</p>
<?php endif;  ?>
</div>
