<?php
$gem = $this->htmlgem;

$assets->add(['bootstrap', 'select']);
$theme = "/" . $m->theme;
$catId = $m->catId;
$orderalt = $m->orderalt;
$col_arrow = $m->col_arrow;
$isEditor = $m->isEditor;

$catItems = $m->catItems;
$url = "/admin/blog/";
$btn_class = "btn btn-outline-info";
if ($catId > 0) {
    $ubase = $url . "?catId=" . $catId . "&orderby=";
} else {
    $ubase = $url . "?orderby=";
}
$show_slug = ($m->orderby === 'slug' || $m->orderby === 'slug-alt') ? true : false;

$link = $ubase . $m->orderby;
$page = $m->page;
?>

<style>
    span.lighten {
        color:#774488;
    }
    a:link {
        color:black;
    }
    a:visited {
        color:darkblue;
    }
    div.gap {
        padding-bottom:15px;
        margin-bottom:15px;
    }
</style>

<div class="container-fluid body-wrap">
    <div class="row">

        <div class="col-4">

            <?php if ($page->last > 1): ?>
                <?= $gem->linkTo(['href' => "/admin/dash", 'text' => "Dash", 'class' => $btn_class]) ?> &#x25C7;
                <?= $gem->linkTo(['href' => $link, 'btn-glyph' => "fast-backward", 'class' => $btn_class]) ?> &#x25C7; 
                <?= $gem->linkTo(['href' => $link . '&page=' . $page->before, 'btn-glyph' => 'arrow-left', 'class' => $btn_class]) ?> &#x25C7; 
                <?= $gem->linkTo(['href' => $link . '&page=' . $page->next, 'btn-glyph' => 'arrow-right', 'class' => $btn_class]) ?> &#x25C7; 
                <?= $gem->linkTo(['href' => $link . '&page=' . $page->last, 'btn-glyph' => "fast-forward", 'class' => $btn_class]) ?> 
            <?php endif ?>
            &#x25C7; <?= $page->current . "/" . $page->last ?>
        </div>

        <div class="col-4">
            <form method='get'>
                <?= $gem->select(['label' => 'Category', 'class' => 'selectpicker', 'list' => $catItems, 'name' => 'catId', 'value' => $catId]) ?>
                <?= $gem->hidden(['name' => 'args', 'value' => $m->args]) ?> 
                <?= $gem->submit(['value' => "Fetch"]) ?>
            </form>
        </div>
        <div class="col-4">

            <?= $gem->linkTo(['href' => $url . 'new', 'text' => "New Article", 'class' => $btn_class]) ?>
        </div>
    </div>
    <div class="hline"></div>
    <div class="container outerwrap">
        <form method="post" action="<?= $url . 'postflag' ?>" >

            <table class="table table-bordered table-striped" align="center">
                <thead>
                    <tr>
                        <th><img src='<?= $theme ?>/tick16.png' /></th>
                        <th style="width:50%;"><?= $gem->linkTo(['href' => $ubase . $orderalt['title'], 'text' => 'Title' . $col_arrow['title']]) ?> / 
                            <?= $gem->linkTo(['href' => $ubase . $orderalt['slug'], 'text' => 'Slug' . $col_arrow['slug']]) ?></th>
                        <th style="width:15%;"><?= $gem->linkTo(['href' => $ubase . $orderalt['author'], 'text' => "Author" . $col_arrow['author']]) ?></th>
                        <th style="width:10%;"><?= $gem->linkTo(['href' => $ubase . $orderalt['date'], 'text' => "Date" . $col_arrow['date']]) ?></th>
                        <th>Feature</th>
                        <th>Enable</th>
                        <th>Comment</th>
                    </tr>
                </thead>
                <tbody>
                    <?php
                    foreach ($page->items as $blog):
                        $pubdate = (new DateTime($blog['date_saved']))->format('d M y');
                        ?>
                        <tr>
                            <td><?= $gem->checkbox(['name' => 'op' . $blog['id']]) ?></td>
                            <?php if ($show_slug): ?>
                                <td class="leftCell"><?= $gem->linkTo(['href' => $url . "edit/" . $blog['id'], 'text' => $blog['title_clean']]) ?></td>
                            <?php else: ?>
                                <td class="leftCell"><?= $gem->linkTo(['href' => $url . "edit/" . $blog['id'], 'text' => $blog['title']]) ?></td>
                            <?php endif ?>

                            <td><span class="lighten"><?= $blog['author_name'] ?></span></td>
                            <td><span class="lighten"><?= $pubdate ?></span></td>
                            <td><?php if ($blog['featured']): ?>
                                    <img src="<?= $theme ?>/tick16.png" />
                                <?php endif ?></td>
                            <td><?php if ($blog['enabled']): ?>
                                    <img src='<?= $theme ?>/tick16.png' />
                                <?php endif ?></td>
                            <td><?php if ($blog['comments']): ?>
                                    <img src='<?= $theme ?>/tick16.png' />
                                <?php endif ?></td>
                            </td>
                        </tr>
                    <?php endforeach ?>
                </tbody>
            </table>
            <div class="row gap">
                <div class="col-2">
                    <select name="flagsel">
                        <option value="enable">Enable</option>
                        <option value="disable">Disable</option>
                        <option value="comment">Comment</option>
                        <option value="noComment">No Comment</option>
                        <option value="feature">Feature</option>
                        <option value="noFeature">No Feature</option>
                    </select>
                </div>
                <div class="col">
                    <?= $gem->submit(['value' => "Change selected"]) ?>
                </div>
            </div>
            <hidden name="args" value="<?= $m->args ?>" ></hidden>
        </form>
    </div>
