<?php 
$gem = $this->htmlgem;
$assets->add('bootstrap');

$url = $m->url;
$ubase = $url . '?orderby=';
$ref = $ubase . $m->orderby;
$page = $m->page;
$orderalt = $m->orderalt;
$col_arrow = $m->col_arrow;
$btn_class = "btn btn-outline-info";
?>

<style>
    span.lighten {
        color:#774488;
    }
    a:link {
        color:black;
    }
    a:visited {
        color:darkblue;
    }
    div.gap {
        padding-bottom:15px;
        margin-bottom:15px;
    }
</style>
<div class='container body-wrap'>
    <div class="row">
        <div class="col-2">
            <span><b>Links</b></span>&nbsp; 
            <?= $gem->linkTo(['href' => $url . 'new', 'text' => 'New Link', 'class' => $btn_class]) ?>
        </div>
        <div class="col-8">
&nbsp; 
<?= $gem->linkTo(['href' => $ref . '&page=1', 'btn-glyph' => "fast-backward",  'class' => $btn_class]) ?>&nbsp; 
<?= $gem->linkTo(['href' => $ref . '&page='. $page->before, 'btn-glyph'=>'arrow-left', 'class' => $btn_class]) ?>&nbsp; 
<?= $gem->linkTo(['href' => $ref . '&page='. $page->next, 'btn-glyph'=>'arrow-right', 'class' => $btn_class]) ?>&nbsp; 

<?= $gem->linkTo(['href' => $ref . '&page='. $page->last, 'btn-glyph' => "fast-forward", 'class' => $btn_class]) ?>
    &nbsp;Page <?= $page->current . " of " .  $page->last ?>
        </div>
    </div>
</div>
<div class='container outerwrap'>
    <form id="links_form" method="post", action="<?= $url . 'enabler' ?>" >
<table class='table table-striped'>
    <thead>
        <tr>
             <th><?= $gem->linkTo(['href' => $ubase . $orderalt['enabled'], 'text' => "Enabled" . $col_arrow['enabled']]) ?></th>
           <th><?= $gem->linkTo(['href' => $ubase . $orderalt['title'], 'text' => "Title" . $col_arrow['title']]) ?></th>
            <th><?= $gem->linkTo(['href' => $ubase . $orderalt['site'], 'text' => "Site" . $col_arrow['site']]) ?></th>
            <th><?= $gem->linkTo(['href' => $ubase . $orderalt['type'], 'text' => "Type" . $col_arrow['type']]) ?></th>
            <th><?= $gem->linkTo(['href' => $ubase . $orderalt['date'], 'text' => "Date" . $col_arrow['date']]) ?></th>
        </tr>
    </thead>
    <tbody>
        <?php 
        foreach($page->items as $link): 
            

        $enabled = $link['enabled'] ? 'Y' : 'N';
        $created = substr($link['date_created'], 0, 10);
        $id = $link['id'];
        $title = trim($link['title']);
        if (empty($title)) {
            $title = '[NULL]';
        }
        ?>
        <tr>
            <td><label><?= $enabled ?>&nbsp;<input type="checkbox" name="lid<?= $id ?>" value="<?= $link['enabled' ] ?>" ?></label></td>
            <td class='leftCell'><a href="<?= $url . 'edit/' . $id ?>"><?= $title ?></a></td>
            <td><?= $link['sitename'] ?></td>
            <td><?= $link['urltype'] ?></td>
            <td><?= $created ?></td>
            
        </tr>
    <?php endforeach ?>
    </tbody>
</table>
        <?= $gem->hidden(['name' => 'page', 'value' => $page->current ]) ?>
          <?= $gem->hidden(['name' => 'orderby', 'value' => $m->orderby ]) ?>
        
        <div class="row center">
        <div class="form-group">
            <label for="link_enable">Change Selected</label>
        <select name="link_enable" id="link_enable">
            <option value="1">Enable</option>
            <option value="0">Disable</option>
        </select>
            <?= $gem->submit(['value' => 'Save', 'class' => "btn btn-warning"]) ?>
        </div>
        </div>
    </form>
</div>