<?php

$gem = $this->htmlgem;

$images = $m->images;
$gallery = $m->gallery;
$series = $m->series;
$post = $m->post;
$name = $gallery->name;
$btnclass = 'btn btn-outline-info';
$assets->add(['bootstrap', 'grid', 'select','jquery-form', 'gallery-progress', 'imagelist']);
?>
<style>
    textarea.form-control {
        margin-left:10px;
        margin-right:10px;
    }
    label {
        font-weight: bold;
    }
    form.label {
        text-align: right;
        margin-right:10px;
        min-width: 120px;

    }

    .boxit label{
        font-weight:normal;
        color:grey;
    }
    .boxit {
        border-radius:5px;
        border-style:outset;
        border-width:2px;
        border-color:grey;
        padding:0.5em;
        display:inline;
        font-weight:bold;
    }
</style>
<?php $this->partial("gallery_adm/title") ?>

<div class="container-fluid outerwrap">
    <div class="row">
        <div class="col">
                <?= $gem->linkTo(['href' => '/admin/gallery/edit/' . urlencode($name),
                    'class' => $btnclass, 'text' => 'Edit Gallery Record'])
                ?>
            <div class="boxit">
                <?= $gem->text_value(['label' => 'Name', 'value' => $name]) ?>
            </div>
                <?php if (!empty($gallery->seriesid)): ?>
                <div class="boxit">
                    <?= $gem->text_value(['label' => 'Series',
                        'value' => $gallery->seriesid])
                    ?>
                </div>
                <div class="boxit">
                    <?= $gem->text_value(['label' => 'Previous',
                        'value' => $gallery->leva_path])
                    ?>
                </div>
                <div class="boxit">
                    <?= $gem->text_value(['label' => 'Next',
                        'value' => $gallery->prava_path])
                    ?>
                </div>
                <?php endif ?>
            <div class="boxit">
<?= $gem->check_value(['checked' => $gallery->view_thumbs,
    'label' => 'View Thumbs'])
?>
            </div>
            <div class="boxit">
        <?= $gem->datetime_value(['label' => 'Last upload',
            'value' => $gallery->last_upload])
        ?>
            </div>
        </div>
    </div>
    <hr>
    <span class="pull-right"><?= $gem->linkTo(['href' => $post . 'scan/' . $name,
            'class' => $btnclass, 'text' => 'Scan ' . $name])
        ?></span>
    <span class="pull-right"><?= $gem->linkTo(['href' => $post . 'sync/' . $name,
            'class' => $btnclass, 'text' => 'Sync ' . $name])
        ?></span>

    <form id='upfile' action="<?= $post . 'upload' ?>" method="post" enctype="multipart/form-data">
        <input type="hidden" id="galleryid" name="galleryid" value="<?= $gallery->id ?>" />
        <div style='outline: 1px dotted orange;width:50em;'>
            <table class='table table-condensed table-borderless' >
                <tr>
                    <td><p><span style="font-size:1.0em;"><b>Upload image or file</b></span></p></td>
                    <td><input id="file" type="file" name="files[]" multiple="multple" ></td>
                    <td><input type="submit" value="upload" class='btn-danger' ></td>
                    <td><?= 
                        $gem->checkbox(['name'=>'thumbs', 'text'=> 'Upload to Thumbs'])
                        ?>
                </tr>
            </table>
        </div>
        <div class="progress">
            <div class="progress-bar" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100"></div>
        </div>
        <div id="targetLayer" style="display:none;"></div>
    </form>
    <div id="image_status"><?php $this->partial("gallery_adm/file") ?></div>
</div>

