<?php 
Use WC\HtmlGem as Gem;
    $gallery = $m->gallery;
    $series = $m->series;
    $name = $gallery->name;
    $btnclass = 'btn btn-lg btn-outline-info';
    $assets->add('bootstrap');
?>
<style>
    textarea.form-control {
        margin-left:10px;
        margin-right:10px;
    }

    label{
        text-align: right;
        margin-right:10px;
        min-width: 120px;
        font-weight: bold;
    }
</style>
<?php $this->partial("gallery_adm/title" ) ?>

<div class="container-fluid outerwrap">
    <form id="galedit" action="/admin/gallery/postnew" method="post">
        <?= Gem::hidden([ 'name' => 'id', 'value' => $gallery->id ]) ?>
        <div class="row">
            <div class="col-10">
                <label for="description" class="control-label">Description</label>
                <?= Gem::multiline([ 'name' => 'description', 'value' => $gallery->description, 'cols' => 80 ]) ?>
            </div>
            <div class="col-1">
                 <?= Gem::submit([ 'class' => 'btn btn-danger', 'value' => 'Update Gallery' ]) ?>
            </div>
        </div>
        <div class="row">
            <div class="col-3">
                <?= Gem::select([ 'name' => 'seriesid', 'label' => 'Series',  
                    'list' => $series, 'value' => $gallery->seriesid ]) ?>
            </div>
            <div class="col-4">
                <label for="leva_path" class="control-label">Previous</label>
                 <?= Gem::plainText([ 'size'=>30, 'name' => 'leva_path', 
                            'value' => $gallery->leva_path ]) ?>
            </div>
            <div class="col-4">
                <label for="prava_path" class="control-label">Next</label>
                <?= Gem::plainText([ 'size'=>30, 'name' => 'prava_path', 
                            'value' => $gallery->prava_path ]) ?>
            </div>
        </div>
        <div class="row">
            <div class="col-2">
                 <?= Gem::checkbox([   'name' => 'view_thumbs',  'checked' =>$gallery->view_thumbs,
                            'text' => 'View Thumbs'  ]) ?>
            </div>
            <div class="col-6">
                <?= Gem::datetime([  'label' => 'Last upload',  'size' => 20, 
                            'name' => 'last_upload',  'value' =>$gallery->last_upload ]) ?>
            </div>
        </div>
    </form>
</div>

