<?php
$gem = $this->htmlgem;
$ubase = "/admin/gallery?orderby="; 
$link =  $ubase . $m->orderby;  
$page = $m->page;
$url =  "/admin/gallery/images/";
$btn_class = "btn btn-outline-info";
$assets->add(['bootstrap','grid']);
?>
<style>
    span.lighten {
        color:#774488;
    }
    a:link {
        color:black;
    }
    a:visited {
        color:darkblue;
    }
    div.gap {
        padding-bottom:15px;
        margin-bottom:15px;
    }
</style>
<div class="container body-wrap">
<div class="outerwrap">
    <div class="row">
    <div class="col-4">
        &nbsp;<?= $gem->linkTo(['href'=> "/dash", 'text' => 'Dash', 'class' => $btn_class]) ?>
      <span> --> <b>Gallery Index</b></span>
    </div>
    <div class="col-5" >
   <?= $gem->linkTo(['href'=>$link,  'btn-glyph' => "fast-backward", 'class' => $btn_class]) ?> &nbsp;
    <?= $gem->linkTo(['href'=>$link.'&page='.$page->before, 'btn-glyph' => 'arrow-left', 'class' => $btn_class]) ?> &nbsp;
 <?= $gem->linkTo(['href'=>$link.'&page='.$page->next, 'btn-glyph' => 'arrow-right', 'class' => $btn_class]) ?> &nbsp;
 <?= $gem->linkTo(['href'=>$link.'&page='.$page->last,'btn-glyph' => "fast-forward", 'class' => $btn_class]) ?> &nbsp;
 <?=$page->current . "/" . $page->last ?> 
    </div>
    <div class="col-3">
  <?= $gem->linkTo(['href'=> "/admin/gallery/new", 'text' => 'New Gallery' , 'class' => $btn_class]) ?>
    </div>
</div>
</div>
 <div class="hline"></div>
 <div class="outerwrap">
<table class='table table-striped'>
    <thead>
        <tr>
            <th class='leftCell'>Path</th>
            <th class='leftCell'>Description</th>
              <th>Upload</th>
        </tr>
    </thead>
    <tbody>
        <?php 
        
        foreach($page->items as $gallery): 
                $udate = date('d-M-Y H:i',strtotime($gallery['last_upload']));
                 $description = $gallery['description'];
                 $name = $gallery['name'];
         ?>
<tr>
    <td class='leftCell'><?= $gem->linkTo(['href'=>$url.$name, 'text'=>$name]) ?></td>
            <td class='leftCell'><?= $description ?></td>
             <td><?= $udate ?></td>
        </tr>
        <?php endforeach ?>
    </tbody>
</table>
 </div>
</div>