
    {~ 
            @view = Base::Instance()->get('view');
            @images = @view->images;
            @gallery = @view->gallery;
    ~}
    
<div class="container">
    <p><span style='font-size:1.0em;'>Gallery: <b>{{ @gallery.name }}</b></span></p>

<div id='image_status'>

    <check if="{{ count(@images) }}" >
        <true>
        {~   
        @linkpath = "/" . @gallery.path . "/";
        @rowId = 0;
        ~}
        <!--
        <table class="table-condensed table-striped">
        <tr>
            <th>name</th>
            <th>thumb</th>
            <th>date</th>
            <th>description</th>
        </tr>
        <tbody> -->
        <!--
<tr>
    <td class="leftCell"><p>{{ @fup.name }} <br> {{ @info }}</p></td>
    <td><a href="{{ @linkpath .  @fup.name }}"><img src="{{ @thumb }}"  title="{{ @info }}" /></a></td>
    <td><p>{{ date('d-M-Y',@idate) .  '</br>' . date('H:i', @idate)  }}</p></td>
    <td><textarea class="imageDesc" id="img{{@fup.id}}" cols='40' readonly>{{ @fup.description }}</textarea></td> 
</tr>
-->
        <div class="row">
            <div class="col-2">
                <span>Name</span>
            </div>
            <div class="col-5">
                <span>Thumbnail</span>
            </div>
            <div class="col-2">
                <span>date</span>
            </div>
            <div class="col-3">
                <span>description</span>
            </div>
        </div>
        <repeat group="{{ @images }}" value="{{ @fup  }}">
{~ 
    @info = @fup->size_str . ' ' . @fup->mime_type;
    @row_id = @row_id + 1;
    @chkid = "chk" . @row_id;
    @idate = strtotime(@fup->date_upload);
    if (!empty(@fup.thumb_ext)) {
        @fname  = pathinfo( @fup.name , PATHINFO_FILENAME);
        @thumb = @linkpath . 'thumbs/' . @fname . "." . @fup.thumb_ext;   
    }
    else {
        @thumb = @fup.name;
    }
~}

<div class="row">
            <div class="col-7">
                <span>{{ @fup.name }}</span>
                <div class="float-right">
                <a href="{{ @linkpath .  @fup.name }}"><img src="{{ @thumb }}"  title="{{ @info }}" /></a>
                </div>
            </div>
            <div class="col-2">
                <p>{{ date('d-M-Y',@idate) .  '</br>' . date('H:i', @idate)  }}</p>
            </div>
            <div class="col-3">
                <textarea class="imageDesc" id="img{{@fup.id}}" cols='40' readonly>{{ @fup.description }}</textarea>
            </div>
        </div>

        </repeat>
</tbody>
 </table></true>
        <false>
            <p>No image files in this gallery yet</p>
        </false>
    </check>

    
</div>

    

</div>   