{~
@events = @view->events;
@chkct = count(@events);
@event_blogid = 0;
@row_id = 0;
~}
<check if="{{ @chkct > 0 }}" ><true>

    <p>Event List</p>
    <form id='eventList' action="{{ @url . 'eventList'}}" method="post">
        <table class='table table-striped' style='width:600px;'>
            <thead>
                <tr>
                    <th width='10%' class='centerCell'></th>
                    <th  width='20%' class='centerCell'><label>Start</label></th>
                    <th width='20%' class='centerCell'><label>End</label></th>
                    <th width='15%' class='centerCell'><label>Slug</label></th>
                    <th width='10%' class='centerCell'><label>Enabled</label></th>
                </tr>
            </thead>
            <repeat group="{{ @events }}" value="{{ @bevt }}">
                {~   @row_id += 1;
                @chkid = "chk" . @row_id;
                ~}

                <tr><td><input name='{{ @chkid }}' id='{{ @chkid }}' type='checkbox' value='{{ @bevt.id }}' /></td>
                    <td>{{ @bevt.fromTime }}</td>
                    <td>{{ @bevt.toTime }}</td>
                    <td>{{ @bevt.slug }}</td>
                    <td>{{ @bevt.enabled ? "Yes" : "No" }}</td></tr>
                {~ @event_blogid = @bevt.blogId; ~}
            </repeat>
            <tr><td><select name='event_op'>
                        <option value='enable'>enable</option>
                        <option value='disable'>disable</option>
                        <option value='remove'>remove</option>
                    </select></td>

                <td><input type='submit' value='Update Selected' class='btn-danger' /></td></tr>
        </table>
        <input type='hidden' name='chkct' value='$chkct' />
        <input type='hidden' name='blogid' value='$event_blogid' />
    </form>
    </true>
    <false>
    <p>Event list is empty<p>
        </false>
</check>