<?php  
use \WC\HtmlGem as Gem;
    $user = $m->user;
    $groups = $m->groups;
    $others = $m->others;
    $url = $m->url;
    $m->title = "G#" . $user->id;
    $gem = new Gem();
?>

<div class="container-fluid outerwrap">
<?php if (empty($user)): ?>
    <p>No Data Found</p>
<?php else: ?>   

<form method="post" autocomplete="off" action="<?= $url . 'gpost'?>">
    <input type="hidden" name='id' value='<?= $user->id ?>'>
<ul class="pager">
    <li class="previous pull-left">
    <?= $gem->linkTo(['href' => $url . 'edit/' . $user->id, 'text' => '&larr; User ' .  $user->name ]) ?>
    </li>
</ul>

    <h2>Groups for <?= $user->name?></h2>
    <p>Default Group of 'Guest'</p>
    <h3>Remove Groups</h3>
    <?php if (!empty($groups)): ?>
    <?php foreach ($groups as $group): ?>
     <div class="row">
                <div class="col">
                    <?= $gem->checkbox(['name' => 'dgp'. $group->groupid, 'text' => $group->name ]) ?>
                </div>
            </div>
    <?php endforeach; ?>
    <?php endif; ?>
        <hr>
        <h3>Add Groups</h3>
    <?php if (!empty($others)): ?>
    <?php foreach ($others as $group): ?>
     <div class="row">
                <div class="col">
                    <?= $gem->checkbox(['name' => 'agp'. $group->id, 'text' => $group->name] ) ?>
                </div>
            </div>
    <?php endforeach; ?>
    <?php else: ?>
        <p>No other groups to add</p>
    <?php endif; ?>



    <div class="row">
        <div class="col-1">
        </div>
        <div class="col">
    <button type="submit" name="add_group" value="1" class="btn btn-warning btn-lg">Change</button>
        </div>
    </div>
    <hr>
</form>
<?php endif; ?> 
</div>