<?php Use WC\Assets, WC\UserSession; ?>
<!DOCTYPE html>
<html>
    <style>
        label {
            min-width:150px;
            text-align:right;
        }
    </style>
    <head>
        <title>Schema View</title>
        <meta http-equiv='Content-Type' content='text/html; charset=utf-8'/>
        <meta name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=1.0; minimum-scale=1.0; user-scalable=no; target-densityDpi=device-dpi"/>
        <?= Assets::instance()->CssHeader(); ?>
    </head>
    <body>
        <h3>Schema Compare Result</h3>
        <pre>
<?= $script ?>
        </pre>
        <?= Assets::instance()->JsFooter(); ?>
    </body>
</html>