<?php
if ($view->layout) {
    $this->layout($view->layout,$this->data);
}
$prevlink = $m->prevlink;
$nextlink = $m->nextlink;
$theme = $f3->get('theme');
$gallery = $m->gallery;
$suburl = $m->suburl;
$params = $m->params;
$index = $m->indexlink;
?>

<!-- title.phtml -->
<style>
    $media screen and (max-width: 900px){
        #mgrid[data-columns]::before {
            content: '1 .column.size-1of1';
        }
    }

    $media screen and (min-width: 901px) and (max-width: 1300px) {
        #mgrid[data-columns]::before {
            content: '2 .column.size-1of2';
        }
    }
    $media screen and (min-width: 1301px) and (max-width: 1600px){
        #mgrid[data-columns]::before {
            content: '3 .column.size-1of3';
        }
    }
    $media screen and (min-width: 1601px) {
        #mgrid[data-columns]::before {
            content: '4 .column.size-1of4';
        }
    }
    .column { float:left; }
    .size-1of1 { width: 100%; }
    .size-1of2 { width: 50%; }
    .size-1of3 { width: 33.333%; }
    .size-1of4 { width: 25%; }

    .nextprev {
        font-size:1.2em;
        font-weight:bolder;
    }
</style>
<div class="container-fluid" style="background-color:lightskyblue;padding:2px;">
    <div class="row">
        <div class="col-sm-2">
            <span class="view-title">
                <a class="site-logo" href="/"><img style="width:100%;max-width:144px;" src="<?= $theme ?>/site-logo-small.png"></a>
            </span>    
        </div>
        <div class="col">
            <div  class="row">

                <?php if(!is_null($prevlink)): ?>
                    <div class="col-md-auto">
                        <div class="btn btn-light">
                            <a href="/gallery/view/<?=$prevlink['name']?>">
                                <span class="nextprev"><img src="/font/glyphicons_free/glyphicons/png/glyphicons-225-chevron-left.png">&nbsp;<?=$prevlink['name']?></span></a>
                        </div>
                    </div>
                <?php endif ?>

                <div class="col text-center">
                    <span class="nextprev"><a href="<?=$index?>">Index</a></span>
                </div>
                <?php if(!is_null($nextlink)): ?>
                
                    <div class="col-md-auto">
                        <a class="btn btn-light" href="/gallery/view/<?=$nextlink['name']?>"><span class="nextprev"><?=$nextlink['name']?>&nbsp;<img src="/font/glyphicons_free/glyphicons/png/glyphicons-224-chevron-right.png"></a>
                    </div>
                 <?php endif ?>

            </div>
            <div class="row">
                <div class="col">
                    <span style='font-size:1.2em;'> 
                        <b><a href="<?= $m->url . "?show=" . $m->show ?>"><?= $gallery['name'] ?></a></b>  
                        &nbsp; | &nbsp; <small><i><?= $gallery['description'] ?></i></small>
                    </span>
                </div>
            </div>
        </div>
        <div class="col-3">
            <div class="row">
                    <div class="col text-center">
                        <span><?= $view->title ?></span><br>
                        <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
                            View as <span id="showid"><?=$m->show?></span>   
                        </button>

                        <div class="dropdown-menu">
                            <a get="<?=$suburl . '&show=grid' ?>" class="dropdown-item" href="#" 
                               onclick="showAs('Grid');<?= $m->subjs ?>" >Grid</a>
                            <a get="<?=$suburl . '&show=slider' ?>" class="dropdown-item" href="#" 
                               onclick="showAs('Slider');<?= $m->subjs ?>" >Slider</a>
                            <a get="<?=$suburl . '&show=table' ?>" class="dropdown-item" href="#" 
                               onclick="showAs('Table');<?= $m->subjs ?>" >Table</a>
                        </div>
                    </div> 
            </div>
        </div>
    </div>
</div>

<div id="gview"><?php $this->insert($m->vname,$this->data)?></div>



