
{~ 
@view = Base::Instance()->get('view');
@series = @view->series;
~}

<style>
    p {
        font-size:1.3em;
    }
</style>
<div class="outerwrap padborder">
    <div class="row">
        <div class="col-4">
            <h2>Series</h2>
        </div>
    </div>
<check if="{{ count(@series) }}" >
    <hr>
    <true>
            <div class="row" style="margin-bottom:5px;">
                <div class="col-1"><span>ID</span></div>
                <div class="col-2"><span>Name</span></div>
                <div class="col-1"><span>Tag</span></div>
            <div class="col-8"><span>Description</span></div>
        </div>
    <hr>
    <repeat group="{{ @series }}" value="{{ @sr  }}">
        <div class="row" style="margin-bottom:5px;">
            <div class="col-1"><p>{{@sr.id}}</p></div>
            <div class="col-2"><p><a href="/series/{{@sr.tinytag}}">{{@sr.name}}</a></p></div>
            <div class="col-1"><p>{{@ssr.tinytag}}</p></div>
            <div class="col-8"><p>{{@sr.description}}</p></div>
        </div>
    </repeat>
    </true>
</check>
</div>
