<?php
if ($view->layout) {
    $this->layout($view->layout, $this->data);
}
$gen = $this->form();
$donations = $m->donations;
$btnclass = 'btn btn-outline-info';
?>
<div class='container' >
    <div id='dnwrap' class='row'>
        <div class='col-2 text-center'>
            Date
        </div>
        <div class='col-2 text-center'>
            Purpose
        </div>
        <div class='col-2 text-right'>
            Amount
        </div>
    </div>

    <?php foreach($donations as $dn): ?>
        <div class="row" id="dnid<?= $dn['donateId'] ?>">
            <div class="col-2 text-center">
                <span><?= $dn['member_date'] ?></span>
            </div>

            <div class="col-2 text-center">
                <span><?= $dn['purpose'] ?></span>
            </div>
            <div class="col-2 text-right">
                <span class="align-right"><?= $gen->price($dn['amount']) ?></span>
            </div>
        </div>
    <?php endforeach ?>
</div>