<?php
$images = $m->images;
$gallery = $m->gallery;
?>
<!--
{~ 
    $view = Base::Instance()->get('view');
    
    $gallery = $view->gallery;
    if ($view->sub===1) {
        $url = "?item=" . $view->requri;
    }
    else {
         $url = $view->requri . "?q=0";
    }
~}
-->

<div class="container-fluid outerwrap">
    <?php if (!empty($images)):  
        $linkpath = "/" . $gallery['path'] . "/";
        $rowId = 0;
        ?>
        
        <?php foreach($images as $fup): 
            $info = $fup['size_str'] . ' ' . $fup['mime_type'];
            $row_id = $row_id + 1;
            $chkid = "chk" . $row_id;
            $idate = date('d-M-Y H:i',strtotime($fup['date_upload']));
            $name = $fup['name'];
            $fname = pathinfo($name,PATHINFO_FILENAME);
            $linkname = $linkpath .  urlencode($name); 
            if ($gallery['view_thumbs']):
              if (!empty($fup['thumb_ext'])):
                $img = $linkpath . 'thumbs/' . urlencode($fname) . "." . $fup['thumb_ext'];   
              else:
                $img = $linkpath . 'thumbs/' . urlencode($fname) . '.png'; 
              endif; 
            else:
             $img = $linkname;
            endif;
        ?>
    <div class="row">
        <div class="col-7"><span><?= $name ?> <br> <?= $info ?></span>
            <div class="float-right">
            <a href="<?= $linkpath .  urlencode($name) ?>"><img src="<?= $img ?>"  title="<?= $info ?>" /></a>
            </div>
        </div>
        <div class="col-2"><p><?= $idate ?></p></div>
        <div class="col-3"><textarea class="imageDesc" id="img<?=$fup.id?>" cols='40' readonly><?= $fup['description'] ?></textarea></div>
    </div>
<hr>
        <?php endforeach ?>
</tbody>
 </table>
 <?php else: ?>
            <p>No image files in this gallery yet</p>
 <?php endif ?>
</div>
