<?php
    $blogs = $m->blogs;
    $cat = $m->catclean;
?>
<div class='container-fluid'>
    <?php if (!empty($blogs)): ?>
    <div class="row">
    <div id="list" class="col catlist">
          <span class="cattitle"><?= $m->cattitle ?></span>
          <?php foreach($blogs as $blog): ?>
               <div class="row">
            <div class="catlink">
                <a class="btn" id="<?= 'f' . $blog->id ?>"  href="<?= '/cat/' . $cat->name_clean .  '?id=' . $blog->id ?>" ><?= $blog->title ?></a>
            </div>
                </div>
       <?php endforeach ?>
    </div>
    <div class="col-lg-auto">
    <div id="article"></div>
    </div>
    <div class="hidden">
        <a id="first_link"  href="<?= $m->firstId ?>" onclick="fetchid(this);return false;">#First#</a>
    </div>
    </div>
<?php endif ?>
</div>
