<?php
use \WC\HtmlGem as Gem;
use \WC\UserSession;
$us = UserSession::read();
?>
<style>
    span.detail {
        font-weight:bold;
        font-size:1.2em;
        font-family: monospace;
    }
    div.gap {
        margin-top:30px;
    }
    label {

        text-align:right;
    }
</style>
<div class='container outerwrap pad10'>
    <div class="row">
        <div class="col text-right">
            <label>Account user name:</label> 
            <br><label>Account email:</label> 
            <br><label>Account role tokens:</label>  
        </div>
        <div class="col-8">
            <span class="detail"> <?= $us->userName ?></span>
            <br><span class="detail"> <?= $us->email ?></span>
            <br><span class="detail"> <?= $us->roles() ?></span>
        </div>
    </div>
    <?php if (UserSession::auth(['Admin','Editor'])): ?>
    <div class="row gap">
        <div class="col text-center">
            <a href="/admin/dash" class="btn btn-large btn-outline btn-info">Dash</a>
        </div>
    </div>
    <?php endif ?>
    <div class="row gap">
        <div class="col text-center">
            <a href="/end_session" class="btn btn-large btn-outline btn-info">Log out from this session!</a>
        </div>
    </div>
</div>

