<?php
use \WC\HtmlGem as Gem;
use \WC\UserSession;
$us = $this->user_session;
?>
<style>
    span.detail {
        font-weight:bold;
        font-size:1.2em;
        font-family: monospace;
    }
    div.gap {
        margin-top:30px;
    }
    label {

        text-align:right;
    }
</style>
<div class='container outerwrap pad10'>
    <div class="row">
        <div class="col text-right">
            <label>Account user name:</label> 
            <br><label>Account email:</label> 
            <br><label>Account role tokens:</label>  
        </div>
        <div class="col-8">
            <span class="detail"> <?= $us->getUserName() ?></span>
            <br><span class="detail"> <?= $us->getUserEmail() ?></span>
            <br><span class="detail"> <?= implode(',',$us->getUserRoles()) ?></span>
        </div>
    </div>
    <?php if ($us->auth(['Admin','Editor','Finance'])): ?>
    <div class="row gap">
        <div class="col text-center">
            <a href="/admin/dash" class="btn btn-large btn-outline btn-info">Dashboard</a>
        </div>
    </div>
    <?php endif ?>
    <div class="row gap">
        <div class="col text-center">
            <a href="/end_session" class="btn btn-large btn-outline btn-info">Log out from this session!</a>
        </div>
    </div>
</div>

