<!DOCTYPE html>
<html>
    <!-- <?= 'File: ' . __FILE__ ?> -->
    <head>
        <?php $title=$m->title ?? "??" ?>
        <title><?=$title?></title>
        <?= 
            $this->partial('std_head'); 
        ?>

    </head>
    <body style="d-flex flex-column min-vh-100">
       <?= $this->partial('flash'); ?>
       <?=
            $this->getContent(); 
       ?>
        <?= 
            $this->partial('std_foot');
        ?>
    </body>
</html>

