<?php 
if ($view->layout):
    $this->layout($view->layout);
endif;
    $images = $m->images;
    $gallery = $m->gallery;
    $series = $m->series;
    $post = $m->post;
    $name = $gallery['name'];
    $fm = $this->form();
    $btnclass = 'btn btn-lg btn-outline-info';
?>
<style>
    textarea.form-control {
        margin-left:10px;
        margin-right:10px;
    }

    label{
        text-align: right;
        margin-right:10px;
        min-width: 120px;
        font-weight: bold;
    }
</style>
<?php $this->insert("gallery_adm/title.phtml" , $this->data) ?>

<div class="container-fluid outerwrap">
    <form id="galedit" action="/admin/gallery/post" method="post">
        <?= $fm->hidden([ 'name' => 'id', 'value' => $gallery['id'] ]) ?>
        <div class="row">
            <div class="col-10">
                <label for="description" class="control-label">Description</label>
                <?= $fm->multiline([ 'name' => 'description', 'value' => $gallery['description'], 'cols' => 80 ]) ?>
            </div>
            <div class="col-1">
                 <?= $fm->submit([ 'class' => 'btn btn-danger', 'value' => 'Update Gallery' ]) ?>
            </div>
        </div>
        <div class="row">
            <div class="col-3">
                <?= $fm->select([ 'name' => 'seriesid', 'label' => 'Series',  
                    'list' => $series, 'value' => $gallery['seriesid'] ]) ?>
            </div>
            <div class="col-4">
                <label for="leva_path" class="control-label">Previous</label>
                 <?= $fm->plainText([ 'size'=>30, 'name' => 'leva_path', 
                            'value' => $gallery['leva_path'] ]) ?>
            </div>
            <div class="col-4">
                <label for="prava_path" class="control-label">Next</label>
                <?= $fm->plainText([ 'size'=>30, 'name' => 'prava_path', 
                            'value' => $gallery['prava_path'] ]) ?>
            </div>
        </div>
        <div class="row">
            <div class="col-2">
                 <?= $fm->plainText([   'name' => 'view_thumbs',  'checked' =>$gallery['view_thumbs'],
                            'text' => 'View Thumbs'  ]) ?>
            </div>
            <div class="col-6">
                <?= $fm->plainText([  'label' => 'Last upload',  'size' => 20, 
                            'name' => 'last_upload',  'value' =>$gallery['last_upload'] ]) ?>
            </div>
        </div>
    </form>
    <hr>
    <span class="pull-right"><?= $fm->linkTo([  'href' => $post  . 'scan/' . $name, 
        'class' =>$btnclass,   'text' => 'Scan ' . $name   ]) ?></span>
    <span class="pull-right"><?= $fm->linkTo([  'href' => $post  . 'sync/' . $name, 
        'class' => $btnclass,   'text' => 'Sync ' . $name   ]) ?></span>

    <form id='upfile' action="<?=$post  . 'upload'?>" method="post" enctype="multipart/form-data">
        <input type="hidden" id="galleryid" name="galleryid" value="<?= $gallery['id'] ?>" />
        <div style='outline: 1px dotted orange;width:50em;'>
            <table class='table table-condensed table-borderless' >
                <tr>
                    <td><p><span style="font-size:1.0em;"><b>Upload image or file</b></span></p></td>
                    <td><input id="file" type="file" name="files[]" multiple="multple" ></td>
                    <td><input type="submit" value="upload" class='btn-danger' ></td>
                    <td><checkbox name="thumbs" text="Upload to Thumbs"></checkbox></td>
                </tr>
            </table>
        </div>
        <div class="progress">
            <div class="progress-bar" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100"></div>
        </div>
        <div id="targetLayer" style="display:none;"></div>
    </form>
    <div id="image_status"><?php $this->insert("gallery_adm/file.phtml", $this->data) ?></div>
</div>

