<?php 
if ($view->layout):
    $this->layout($view->layout, $this->data);
endif;
    $images = $m->images;
    $gallery = $m->gallery;
    $series = $m->series;
    $post = $m->post;
    $name = $gallery['name'];
    $fm = $this->form();
    $btnclass = 'btn btn-lg btn-outline-info';
?>
<style>
    textarea.form-control {
        margin-left:10px;
        margin-right:10px;
    }
    label {
         font-weight: bold;
    }
    form.label {
        text-align: right;
        margin-right:10px;
        min-width: 120px;
       
    }
</style>
<?php $this->insert("gallery_adm/title.phtml" , $this->data) ?>

<div class="container-fluid outerwrap">
        <div class="row">
            <div class="col">
                 <?= $fm->linkTo([ 'href' => '/admin/gallery/edit/'.$name,
                 'class' => $btnclass, 'text' => 'Edit Gallery Record' ]) ?>
             
                <?= $fm->text_value([ 'label' => 'Name', 'value' => $name ]) ?>
                
                <?= $fm->text_value([  'label' => 'Series',  
                     'value' => $gallery['seriesid'] ]) ?>
        
                 <?= $fm->text_value([  'label' => 'Previous', 
                            'value' => $gallery['leva_path']  ]) ?>
            
                
                <?= $fm->text_value([ 'label' => 'Next',  
                            'value' => $gallery['prava_path'] ]) ?>

                 <?= $fm->check_value([  'checked' =>$gallery['view_thumbs'],
                            'label' => 'View Thumbs']) ?>

                <?= $fm->datetime_value([  'label' => 'Last upload',  
                             'value' =>$gallery['last_upload']]) ?>
            </div>
        </div>
    <hr>
    <span class="pull-right"><?= $fm->linkTo([  'href' => $post  . 'scan/' . $name, 
        'class' =>$btnclass,   'text' => 'Scan ' . $name   ]) ?></span>
    <span class="pull-right"><?= $fm->linkTo([  'href' => $post  . 'sync/' . $name, 
        'class' => $btnclass,   'text' => 'Sync ' . $name   ]) ?></span>

    <form id='upfile' action="<?=$post  . 'upload'?>" method="post" enctype="multipart/form-data">
        <input type="hidden" id="galleryid" name="galleryid" value="<?= $gallery['id'] ?>" />
        <div style='outline: 1px dotted orange;width:50em;'>
            <table class='table table-condensed table-borderless' >
                <tr>
                    <td><p><span style="font-size:1.0em;"><b>Upload image or file</b></span></p></td>
                    <td><input id="file" type="file" name="files[]" multiple="multple" ></td>
                    <td><input type="submit" value="upload" class='btn-danger' ></td>
                    <td><checkbox name="thumbs" text="Upload to Thumbs"></checkbox></td>
                </tr>
            </table>
        </div>
        <div class="progress">
            <div class="progress-bar" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100"></div>
        </div>
        <div id="targetLayer" style="display:none;"></div>
    </form>
    <div id="image_status"><?php $this->insert("gallery_adm/file.phtml", $this->data) ?></div>
</div>

