<wc:init></wc:init>
{~
    @view = Base::Instance()->get('view');
    @images = @view->images;
    @gallery = @view->gallery;
    @post = @view->post;
    @reply = @view->reply;
    @imgCount = isset(@images) ? count(@images) : 0;
~}

<form id='imageList' action="{{@post . 'imageList' }}" method="post">
    <check if="{{ isset(@reply)  }}"><true>
        <repeat group="{{ @reply }}" value="{{ @line }} ">
            <p>{{ @line }}</p>
        </repeat>
        </true></check>
<check if="{{ @imgCount }}" ><true>
        {~   
        @linkpath = "/" . @gallery.path . "/";
        @rowId = 0;
        @select = @view->select;
        ~}
<table class="table-condensed table-striped"><tbody>
        <!-- <tr>
            <th>select</th>
            <th>visible</th>
            <th>name</th>
            <th>thumb</th>
            <th>date</th>
            <th>description</th>
        </tr> 
        <tr>
    <td><input name='{{ @chkid }}' id='{{ @chkid }}' type='checkbox' value='{{ @fup.id }}' /></td>
    <td>{{ @fup.visible }}</td>
    <td class="leftCell">{{ @fup.name }}</td>
    <td><a href="{{ @linkpath .  @fup.name }}"><img src="{{ @thumb }}"  title="{{ @info }}" /></a></td>
    <td><datetime id="{{@dateid}}"  name="{{@dateid}}" class="form-control" value="{{@fup.date_upload}}"></datetime></td>
    <td><textarea class='imageDesc' name='{{ @descid }}' id='{{ @descid }}' cols='40'>{{ @fup.description }}</textarea></td>
</tr>
        -->
        
           <div class="row">
            <div class="col-2">
                <span>Name</span>
            </div>
            <div class="col-5">
                <span class="float-right">Thumbnail</span>
            </div>
            <div class="col-2">
                <span>date</span>
            </div>
            <div class="col-3">
                <span>description</span>
            </div>
        </div>     
 <repeat group="{{ @images }}" value="{{ @fup  }}">
{~ 
    @info = @fup.size_str . ' ' . @fup.mime_type;
     @odate = strtotime( @fup.date_upload );
    @row_id = @row_id + 1;
    @chkid = "chk" . @row_id;
    @descid = "desc" . @row_id;
    @dateid = "date" . @row_id;
    if (!empty(@fup.thumb_ext)) {
        @fname  = pathinfo( @fup.name , PATHINFO_FILENAME);
        @thumb = @linkpath . 'thumbs/' . @fname . "." . @fup.thumb_ext;   
    }
    else {
        @thumb = @fup.name;
    }
~}
<div class="row">
            <div class="col-7">
                <input name='{{ @chkid }}' id='{{ @chkid }}' type='checkbox' value='{{ @fup.id }}' />
                <span>{{ @fup.name }}</span>
                <div class="float-right">
                <a href="{{ @linkpath .  @fup.name }}"><img src="{{ @thumb }}"  title="{{ @info }}" /></a>
                </div>
            </div>
            <div class="col-2">
                <datetime id="{{@dateid}}"  name="{{@dateid}}" class="form-control" value="{{@fup.date_upload}}"></datetime>
            </div>
            <div class="col-3">
                <textarea class='imageDesc' name='{{ @descid }}' id='{{ @descid }}' cols='40'>{{ @fup.description }}</textarea>
            </div>

        </div>
    <hr>
 </repeat>
    <tr><td><label>Perform</label></td>
    <td class="leftCell"><select name='image_op' id="image_op">
            <repeat group="{{ @select }}" key="{{ @skey }}" value="{{ @sval }}">
                <check if="{{ @sval[1] == 1 }}"><true>
                        <option value='{{ @skey}}' selected="selected">{{ @sval[0] }}</option>
                    </true><false>
                        <option value='{{ @skey}}'>{{ @sval[0] }}</option>
                    </false>
                </check>
            </repeat>
        </select></td>
        <td><input name='update' type='submit' value='Update Selected' class='btn-danger' /></td>
</tr>
    </tbody></table>
        </true>
        <false>
    <p>No image files in this gallery yet</p>
    </false>
</check>  
<input type='hidden' name='chkct' value='{{ @imgCount }}' />
<input type='hidden' name='galleryid' value='{{ @gallery.id }}' />
</form>

<check if="{{@AJAX}}">
    <script type="text/javascript">
        pref_imagelist();
    </script>
</check>

