<?php
    $images = $m->images;
    $gallery = $m->gallery;
    $post = $m->post;
    $reply = $m->reply;
    $imgCount = isset($images) ? count($images) : 0;
   $fm = $this->form();
?>

<style>
    .restrict {
        max-width:400px;
    }
</style>
<form id='imageList' action="<?=$post. 'imageList'  ?>  " method="post">
    <?php if( isset($reply) ): ?>
    <?php foreach($reply as $line): ?>
            <p><?= $line ?> </p>
     <?php endforeach ?>
      <?php endif ?>
            <?php if ($imgCount): 
            $linkpath = "/" . $gallery['path'] . "/";
            $rowId = 0;
            $select = $m->select;
        ?>

        
           <div class="row">
            <div class="col-2">
                <span>Name</span>
            </div>
            <div class="col-5">
                <span class="float-right">Thumbnail</span>
            </div>
            <div class="col-2">
                <span>date</span>
            </div>
            <div class="col-3">
                <span>description</span>
            </div>
        </div>     
    <?php foreach($images as $fup ): 
        $info = $fup['size_str'] . ' ' . $fup['mime_type'];
         $odate = strtotime( $fup['date_upload'] );
        $row_id = $row_id + 1;
        $chkid = "chk" . $row_id;
        $descid = "desc" . $row_id;
        $dateid = "date" . $row_id;
        $name = $fup['name'];
        if (!empty($fup['thumb_ext'])) {
            $fname  = pathinfo(  $name, PATHINFO_FILENAME);
            $thumb = $linkpath . 'thumbs/' . $fname . "." . $fup['thumb_ext'];   
        }
        else {
            $thumb = $name;
        }    
?>

<div class="row">
            <div class="col-7">
                <input name='<?= $chkid ?>' id='<?= $chkid ?>' type='checkbox' value='<?= $fup['id'] ?>' />
                <span><?= $name ?></span>
                <div class="float-right">
                <a href="<?= $linkpath .  $name ?>"><img class = "restrict" src="<?= $thumb ?>"  title="<?= $info ?>" /></a>
                </div>
            </div>
            <div class="col-2">
                <?= $fm->datetime(['id' =>$dateid,  'name' => $dateid, 'class' => "form-control", 
                    'value' => $fup['date_upload' ] ]) ?>
              </div>
            <div class="col-3">
                <textarea class='imageDesc' name='<?= $descid ?>' id='<?= $descid ?>' cols='40'><?= $fup['description'] ?></textarea>
            </div>
        </div>
    <hr>
<?php   endforeach ?>
    <table class="table-condensed table-striped"><tbody>
    <tr><td><label>Perform</label></td>
    <td class="leftCell">
            <?= $fm->select([ 'name' => 'image_op',  'id' => 'image_op',  'list' => $m->select, 'value' =>$m->select_op ]) ?>
      </td>
        <td><input name='update' type='submit' value='Update Selected' class='btn-danger' /></td>
</tr>
    </tbody></table>
<?php else: ?>
    <p>No image files in this gallery yet</p>
<?php endif ?>
<input type='hidden' name='chkct' value='<?= $imgCount ?>' />
<input type='hidden' name='galleryid' value='<?= $gallery['id'] ?>' />
</form>
<?php if ($f3->get('AJAX')): ?>
    <script type="text/javascript">
        pref_imagelist();
    </script>
<?php endif ?>

