<?php
    if ($view->layout):
        $this->layout($view->layout, $this->data);
    endif;
    $gallery = $m->gallery;
    $fm = $this->form();
?>
<style>
    textarea.form-control {
        margin:20px;
    }
    
    input.form-control {
        max-width:300px;
        margin:20px;
    }
    label.control-label {
        min-width:110px;
        text-align:right;
        margin-right:10px;
    }
</style>
<div class="container-fluid">
    <div class="outerwrap pad10">
    
    <form method="post" action="<?= $view->url . 'post' ?>">
        <?php 
            $name = $gallery['name'];
            if(empty($gallery['id'])):
                $sval = 'Create';
            ?>
           <h1>Create Image Gallery</h1>
            <?= $fm->hidden(['name' => 'id', 'value' =>  $gallery['id'] ]) ?>
            <div class="row">
            <label for="name" class="control-label">Name</label>
            <?= $fm->plainText(['name' => 'name', 'value' =>  $name  ]) ?>
            </div>
            <?php else: 
                $sval = 'Update';
                ?>
 
            <h1>Update Image Gallery</h1>
                <div class="row">
                    <label for="name" class="control-label">Name</label>
                    <?= $fm->plainText(['name' => 'name', 'value' =>  $name, 'readonly'  ]) ?>
                </div>
            <?php endif ?>
        <div class="row">
            <label for="description" class="control-label">Description</label>
            <?= $fm->multiline(['cols' => 50, 'name' => 'description', 'value' =>  $gallery['description']   ]) ?>
         </div>
        <div class="row">
            <div class="col">
            <?= $fm->submit(['value' => $sval, 'class'=>'btn btn-warning btn-lg']) ?>
            </div>
        </div>
    </form>
    </div>
</div>