<?php
    if ($view->layout):
        $this->layout($view->layout, $this->data);
    endif;
    $gallery = $m->gallery;
    $fm = $this->form();
?>
<style>
    textarea.form-control {
        margin:20px;
    }
    
    input.form-control {
        max-width:300px;
        margin:20px;
    }
    label.control-label {
        min-width:110px;
        text-align:right;
        margin-right:10px;
    }
</style>
<div class="container-fluid">
    <div class="outerwrap pad10">
    <h1>Create Image Gallery</h1>
    <form method="post" action="<?= $view->url . 'post' ?>">
        <?php 
            $name = $gallery['name'];
            if($gallery['id']):
                $sval = 'Create new gallery';
            ?>
            <hidden name="id" value="<?= $gallery['id'] ?>"></hidden>
            <div class="row">
            <label for="name" class="control-label">Name</label>
            <text-field name="name" value="<?= $name ?>" readonly></text-field>
            </div>
            <?php else: 
                $sval = 'Update gallery';
                ?>
                <div class="row">
                    <label for="name" class="control-label">Name</label>
                <text-field name="name" value="<?= $name ?>"></text-field>
                </div>
            <?php endif ?>
        <div class="row">
            <label for="description" class="control-label">Description</label>
            <multiline cols="50" name="description" value="<?= $gallery['description'] ?>"></multiline>
        </div>
        <div class="row">
            <?php $fm->submit(['value' => $sval, 'class'=>'form-control']) ?>
        </div>
    </form>
    </div>
</div>