<?php
// Title Insert
$gallery = $m->gallery;
?>
<div class="row outerwrap">
    <div class="col-10">
    <span style='font-size:1.2em;'> 
        <a href="/dash">Dash</a> &nbsp; &gt;&gt; &nbsp; 
        <a href="/admin/gallery/">Galleries Index</a> &nbsp; &gt;&gt; &nbsp;
        Gallery: <a href="/admin/gallery/images/<?= $gallery['name']  ?>"><?= $gallery['name'] ?></a><br>
        <i><?= $gallery['description'] ?></i>
        
    </span>
    </div>
 </div>