<?php

$link = $m->link;
$url = $m->url;
$linkery = $m->linkery;
$collections = $m->collections;

$display = \Pcan\DB\Links::display();
$urltypes = $link->getUrlTypes();

if ($view->layout) {
    $this->layout($view->layout, $this->data);
}
$fm = $this->form();
?>

<style>
    label {
        font-weight:bold;
        min-width: 10em;
        text-align: right;
        padding-right: 0.5em;
        padding-top:10px;
    }
    

    .col-restrict {
        max-width: 70%;
    }
    #date_created {
        max-width: 15em;
    };
</style>

<div class="container-fluid outerwrap pad10">
    <div class="row">
        <div class="col-4">
            <a href="/dash">Dash</a> &nbsp; >> &nbsp; 
            <a href="/admin/link">Links</a> &nbsp; >> &nbsp; 
            <span><?= $m->title ?></span>
        </div>
<?php if($link['refid']): ?>
            <div class="col-2">
                <?= $fm->linkTo(['href' => '/admin/blog/edit/' . $link['refid'], 
                    'text' =>"Edit Target Blog", 'target' =>"_blank", 'class' => "btn btn-default"]) ?>
            </div>
<?php endif ?>
<?php if(isset($linkery)): ?>
            <div class="col-2">
                <form id="addLinkery" action="/admin/linkery/add" method="post">
                    <hidden name="linkid" value="<?= $link['id'] ?>"></hidden>
                    <hidden name="gallid" value="<?= $linkery['id'] ?>"></hidden>
                <?= $fm->submit(['value' => 'Add to linkery ' . $linkery['name'],
                    'class'=> "btn btn-primary"]) ?>
                </form>
            </div>
<?php endif ?>
    </div>
    <?php if(!empty($collections)): ?>
        <div class="row" >
            <div class="col-1">
                <label><b>Collections</b></label>
            </div>
            <div class="col-11">
                <p><?php foreach($collections as $coll): 
                    echo ($coll['name'] . "&nbsp[" . $coll['id'] . "]&nbsp; | &nbsp;<br>");
                endforeach ?></p>
            </div>
        </div>
<?php endif ?>
    <hr />
    <div class="clear"></div>
    <form id="linkform" name="linkform" method="post" action="<?= $m->post ?>" onsubmit="smotePost()">
        <check if="<?= $link['refid'] ?>">
            <true>
            <hidden name="refid" value="<?= $link['refid'] ?>" />
            </true>
        </check>
        <div class='row'>
            <label class="col-form-label" for='sitename'>Site Name</label>
            <?= $fm->plainText(['name' => 'sitename' , 'value' => $link['sitename'],
              'maxlength' =>  $display['sitename.max'] ]) ?>
        </div>
        <div class='row'>
            <label class="col-form-label" for='title'>Title</label>
            <?= $fm->plainText(['name' => 'title' , 'value' => $link['title'], 'size'=>80,
              'maxlength' =>  $display['title.max'], 'class' =>  "col-restrict"]) ?>
        </div>

        <div class="row">
            <label class="col-form-label" for='url'>URL</label>
            <?= $fm->plainText(['name' => 'url' , 'value' => $link['url'], 'size'=>80,
              'maxlength' =>  $display['url.max'], 'class' =>  "col-restrict"]) ?>
        </div>
        <div class='row pad10'>
            <div class="col-4">
                <?= $fm->checkbox(['label' => 'Enabled', 'name' => 'enabled', 
                    'checked' => $link['enabled'] ]) ?>
            </div>
            <?php if ($m->linkid > 0): ?>
                <div class="col-5">
                    <?= $fm->datetime(['name' => 'date_created', 'size'=>20, 
                        'label' => "Created at",
                        'value' => $link['date_created'] ]) ?>
                 </div>
            <?php endif ?>
            <hidden name="id" value="<?= $link['id'] ?>" />
            <div>
                <label class="col-4" for='url'>URL Type</label>
                <?= $fm->select(['name' => 'urltype', 'list' => $urltypes,
                    'value' => $link['urltype'] ]) ?>
            </div>
        </div>
        <div>
            <button id="airbtn" type="button" 
                    title="This also does a save-submit" 
                    onclick="codeSwitch()">Switch to 'Air-Mode'</button>
        </div>
        <div class="clear"></div>
        <div class="form-group">
            <textarea id='summary' name='summary' cols='100' rows='25'><?= $link['summary'] ?></textarea>
            <hr>
            <?php if ($m->linkid==0): ?>
                <div class="col-sm-2">
                    <input name='btnUpdate' class='btn btn-success' type='submit' id='btnupdate' value="Create">
                </div>
            <?php else: ?>
                <div class="form-group row" >
                    <div class="col-sm-3">
                        <input name='btnDelete' class='btn btn-danger' type='button' id='btndelete' value="Delete" onclick="return doDelete(this.form);"/>
                    </div>
                    <div class="col-sm-6">
                        <input name='btnUpdate' class='btn btn-success' type='submit' id='btnupdate' value="Update">
                    </div>
                </div>
            <?php endif ?>
        </div>
    </form>
</div>





