<?php
$gem = $this->htmlgem;
$links = $m->links;
$chkct = count($links);
$linkery = $m->linkery;
$post = $m->post;
?>


<div class='body-wrap'>
<form id='linkList' action="<?= $post . 'linkList'  ?>" method="post">
    <?php if (isset($m->replylist)): ?>
    <?php foreach($m->replylist as $reply): ?>
            <p><?= $reply  ?></p>
            <?php endforeach ?>
<?php endif ?>
            <?php if (!empty($chkct)): 
                $row_id = 0;
                $select = $m->select;
                ?>
                <table class="table-condensed table-striped"><tbody>
        <tr>
            <th>select</th>
            <th>title</th>
            <th>info</th>
            <th>content</th>
        </tr>
    <?php foreach($links as $fup): 
         $odate = explode(' ', $fup->date_created );
         $info = $odate[0] . '<br>';
         $info .= ($fup->enabled ? 'Enabled' : 'Disabled') . '<br>'
                        .  $fup->urltype;
   
    $row_id = $row_id + 1;
    $chkid = "chk" . $row_id;
    $descid = "desc" . $row_id;
        ?>
<tr>
    <td><input name='<?= $chkid  ?>' id='<?= $chkid  ?>' type='checkbox' value='<?= $fup->id  ?>' /></td>
    <td class="leftCell"><?= $fup->title  ?></td>
    <td><p><?= $gem->linkTo(['text' => $info, 'href' => '/admin/link/edit/' . $fup->id ]) ?></p></td>
    <td><div class='html' name='<?= $descid  ?>' id='<?= $descid  ?>' cols='40'><?= $fup->summary  ?></div></td>
</tr>
 <?php endforeach ?>
           


    
    <tr><td><label>Perform</label></td>
    <td class="leftCell">
        <?= $gem->select(['value' =>$m->select_val,  'name' => 'image_op', 'list'=>$m->select]) ?>
    </td>
        <td><input name='update' type='submit' value='Update Selected' class='btn-danger' /></td>
</tr>
    </tbody></table>
<?php else: ?>
    <p>No records in this Linkery yet</p>

 <?php endif ?>
<input type='hidden' name='chkct' value='<?= $chkct  ?>' />
<input type='hidden' name='linkeryid' value='<?= $linkery->id  ?>' />
</form>
</div>
