<?php
Use WC\HtmlGem as Gem;
$linkery = $m->linkery;
?>

<div class="row outerwrap">
    <div class="col-10">
    <span style='font-size:1.2em;'> 
        <a href="/dash">Dash</a> &nbsp; &gt;&gt; &nbsp; 
        <a href="/admin/linkery">Linkery Index</a> &nbsp; &gt;&gt; &nbsp;
        Linkery: <b><?= $linkery->name ?></b><br>
        <i><?= $linkery->description ?></i>
    </span>
    <span>
    </div>
 </div>