<!DOCTYPE html>
<html lang="en">
    <wc:init></wc:init>
	<head>
    <meta charset="UTF-8" />
    <title>{{ @view->title }}</title>
        <f3:link></f3:link>
        <f3:css-header></f3:css-header>    
	</head>
	<body>
                <check if="{{ !empty(@view->flash) }}"><true>
            <F3:repeat group="{{ @view->flash }}" value="{{ @msg }}">
            <div class="alert alert-{{ @msg.status }} alert-dismissable">
              <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                        {{ @msg.text | esc }}
            </div>
                </F3:repeat>
                </true></check>
<check if="{{ @view->content }}">
    <true>
        <include href="{{ @view->content }}"></include>
    </true>
</check>
<footer class='footer foot-wrap'>
<span class="text-muted">&copy;  | 
    {~
    @out = " Response time " . sprintf('%.2f ms', (microtime(TRUE) - @_SERVER.REQUEST_TIME_FLOAT) * 1000);
    @out .= " | Memory " . sprintf('%.2f MiB', memory_get_peak_usage() / 1024 / 1024);
    echo(@out);
    ~}
</span>
</footer>
<f3:js-footer></f3:js-footer>
	</body>
</html>
