<?php
// Title Insert
$gp = $m->group;
$prefix = '/admin/email_group/edit/';
?>
<div class="container-fluid outerwrap">
<div class="row">
    <div class="col">
    <span style='font-size:1.2em;'> 
        <a href="/dash">Dash</a> &nbsp; &gt;&gt; &nbsp; 
        <a href="/admin/email_group/index">Template Index</a> &nbsp; &gt;&gt; &nbsp;
        Gallery: <a href="/admin/email_group/edit/<?= $gp->name  ?>"><?= $gp->name ?></a><br>
        <i><?= $gp->description ?></i>
        
    </span>
    </div>
</div>

</div>