{~
@view = Base::instance()->get('view');
@blog = @view->blog;
@metadata = @view->metadata;
@back = @view->back;
~}

<style>
    div#title-box {
        background-color:white;
        font-family: Times;
        font-weight: bold;
        font-size:1.8em;
        margin:10px;
    }
    div#article-box {
        border-width:0;
    }
    div#metadata {
        background-image: url( "{{ @theme }}/tile-fog.png" );
    }
</style>
<div class='container-fluid'>
    <div  class="row">
        <div class="col-6">
            <check if="{{ @back }}">
                Back to <a href="{{ @back }}">{{ @view->backname }}</a>&nbsp; &nbsp; &nbsp; 
            </check>
        </div>
    </div>
    <div id="article-box">
    <div class='{{@blog.style}}' >
        <div id="title-box" class="row">
             <div class="col">
            <span>{{ @blog.title }}</span>
             </div>
        </div>
        <div class="row">
            <div class="col">
                {{ @blog.article | raw }}
            </div>
        </div>
    </div>
    </div>
    <check if='{{ count(@metadata) > 0 }}'><true>
        <div class='container-fluid' id='metadata' style='font-size:0.6em;'>
            <div class='table'>
                <repeat group='{{ @metadata }}' value='{{ @mtag }}' > 
                    <check if='{{ @mtag.display == 1 && strlen(@mtag.content) >0 }}'><true>
                        <div class="row">
                            <div class='col-1'>{{ @mtag.meta_name}}:</div>
                            <div class='col-8'>{{ @mtag.content}}</div>
                        </div>
                        </true>
                    </check>
                </repeat>
            </div>
        </div>
        </true>
    </check>
    <hr />
</div>
<div class='clear'></div>

<check if='{{ @metadata }}'><true>
    <div class="fb-share-button" 
         data-href="{{ @view->canonical }}" 
         data-layout="button_count">
    </div>
    </true>
</check>
<check if='{{ @blog.comments }}'><true>
    <div>
        <div id="fb-root"></div>
        <fb:login-button autologoutlink="True" length="short" background="white" size="large"></fb:login-button>
        <div class="fb-comments" data-href="{{ @view->canonical }}" data-width="900" data-numposts="5"></div>
    </div>
    </true>
</check>
