<!-- category.htm -->
{~
@view = Base::instance()->get('view');
@catset = @view->catset;
@catList = @catset->catlist;
@catValues = join(",",@catset->available);
@catBlogId = @catset->cat_blogid;
@chkct = count(@catList);
~}
<check if="{{ @chkct > 0}}" ><true>
<span class="heading">Category List</span>   
<p>&nbsp;<em>Unselected categories are: </em>{{ @catValues }}</p>
<form id='categoryList' action="{{ @url . 'categorytick' }}" method="post">
<table class='table table-striped'>
    {~ @rowid = 0; ~}
    <tbody><tr>
    <repeat group="{{ @catList }}" value="{{ @cat }}" >
        <check if="{{ @rowid % 3 === 0 }}"><true>
            </tr><tr>
        </true></check>
        {~ @rowid += 1;
             @catid = "cat" . @rowid;   
             @checked = (@cat.blog_id > 0) ? "checked" : "";
        ~}

         <td class='leftCell'><input name='{{ @catid }}' id='{{ @catid }}' type='checkbox' value='{{ @cat.id  }}'  {{@checked }} />{{@cat.name}}</td>
    </repeat>
   </tr>
   <tr><td><input type='submit' value='Update' class='btn-danger' /></td>
   </tr>
    </tbody>
    </table>
    <input type='hidden' name='chkct' value='{{ @chkct }}' />
    <input type='hidden' name='blogid' value='{{ @catBlogId }}' />
    </form>
</true>
<false>
<h5>Category List (empty)</h5>
</false>
</check>

<script>
$(document).ready(function () {
    var options = {
      target: '#category_status'
    };
    $('#categoryList').ajaxForm(options);
}); 
</script>