<?php
// Insertion into blog
$events = $m->events;
$chkct = count($events);
$event_blogid = 0;
$row_id = 0;
$url = $m->url;

if ( $chkct > 0): ?>

<div class="body-wrap">
<form id='eventList' action="<?= $url . 'eventUpdate' ?>" method="post">
<table class='table table-striped' style='width:auto;'>
    <thead>
        <tr>
            <th width='10%' class='centerCell'><span class="heading">Events</span></th>
            <th  width='20%' class='centerCell'><label>Start</label></th>
            <th width='20%' class='centerCell'><label>End</label></th>
            <th width='15%' class='centerCell'><label>Slug</label></th>
            <th width='10%' class='centerCell'><label>Enabled</label></th>
        </tr>
    </thead>
    <?php foreach($events as $bevt): 
     if ($row_id === 0) {
                  $event_blogid = $bevt['blogId'];
     }
     $row_id += 1;
     $chkid = "chk" . $row_id; ?>
         <tr><td><input name='<?= $chkid ?>' id='<?= $chkid ?>' type='checkbox' value='<?= $bevt['id'] ?>' /></td>
         <td><?= $bevt['fromTime'] ?></td>
         <td><?= $bevt['toTime'] ?></td>
         <td><?= $bevt['slug'] ?></td>
        <td><?= $bevt['enabled'] ? "Yes" : "No" ?></td>
        <td><a href="/admin/event/<?= $bevt['id'] ?>" target="_blank">Edit</a></td>
         </tr>
    <?php endforeach ?>
    <tr><td><select name='event_op'>
                   <option value='enable'>enable</option>
                   <option value='disable'>disable</option>
                   <option value='remove'>remove</option>
     </select></td>
    
     <td><input type='submit' value='Update Selected' class='btn-danger' /></td></tr>
    </table>
    <input type='hidden' name='chkct' value='<?= $row_id ?>' />
    <input type='hidden' name='blogid' value= "<?= $event_blogid ?>" />
    </form>
</div>
    
<script type="text/javascript">
  $(document).ready(ready_eventList);
</script>
<?php else: ?>
    <p>Event list is empty<p>
<?php endif ?>

