<?php 
$data = $this->data();
$this->layout('layout_plates',$data);
$view = $data['view'];
$f3 = $data['f3'];
$theme = $f3->get('theme');
$m = $view->model;
$catId = $m->catId;
$orderalt = $m->orderalt;
$col_arrow = $m->col_arrow;
$isEditor = $m->isEditor;
$user_id = $m->userId;
$catItems = $m->catItems;
$url = "/admin/blog/";

if ($catId > 0) {
$ubase =  $url . "index?catId=" . $catId . "&orderby=";
} else {
$ubase =  $url . "index?orderby=";
}
$link = $ubase . $m->orderby;  
$page = $m->page;

?>

<div class="body-wrap">
    <a href="/dash" class="btn btn-outline-default title">Dash</a> 
    <?php if ($page->last > 1 ): ?>
        &nbsp; | &nbsp;<?= $this->form()->linkTo(['href' => $link, 'text'=> "First"]) ?>
        &nbsp; | &nbsp;<?= $this->form()->linkTo(['href' => $link . '&page='. $page->before, 'text' => "Previous"]) ?>
        &nbsp; | &nbsp;<?= $this->form()->linkTo(['href' => $link . '&page=' . $page->next, 'text' => "Next"]) ?>
        &nbsp; | &nbsp;<?= $this->form()->linkTo(['href' => $link . '&page=' . $page->last, 'text' => "Last"]) ?>
    <?php endif ?>
    &nbsp;|&nbsp;  <?= $page->current . "/" . $page->last ?>
    &nbsp;|&nbsp;  
    <?= $this->form()->linkTo(['href' => $url . 'new', 'text'=> "New Article",  'class' =>"title"]) ?>

    <?php if (count($catItems) > 0): ?>
        <div class="container">
            <form method='get'>
                <label>Category</label>
                <select id="catId" name="catId">
                    <option value="0">- None -</option>
                    <?php foreach($catItems as $category): 
                        $name = $category['name']; ?>
                    <?php if ($category['id'] == $catId): ?>
                <option value=""<?=$catId?>" selected><?=$name?></option>
                <?php else: ?>
                     <option value="<?= $category['id'] ?>"><?=$name?></option>        
                <?php endif ?>
                <?php endforeach ?>
                </select>
                <hidden name="args" value="<?= $view->args ?>" ></hidden>
                <submit-btn  value="Fetch" />
            </form>
        </div>
    <?php endif ?>
</div>
<div class="container outerwrap">
    <form method="post" action="<?= $url . 'postflag' ?>" >
        <table class="table table-bordered table-striped" align="center">
            <thead>
                <tr>
                    <th><img src='<?= $theme ?>/tick16.png' /></th>
                    <th style="width:50%;"><?= $this->form()->linkTo(['href' => $ubase . $orderalt['title'], 'text' => 'Title' .  $col_arrow['title']]) ?></th>
            <th style="width:15%;"><?= $this->form()->linkTo(['href' => $ubase . $orderalt['author'],  'text'=>"Author" . $col_arrow['author']]) ?></th>
            <th style="width:10%;"><?= $this->form()->linkTo(['href' => $ubase . $orderalt['date'], 'text'=>"Date" . $col_arrow['date']]) ?></th>
            <th>Feature</th>
            <th>Enable</th>
            <th>Comment</th>
            </tr>
            </thead>
            <tbody>
<?php foreach($page->items as $blog): 
    $pubdate = (new DateTime($blog['date_published']))->format('d M y');
?>
                <tr>
                    <td><?= $this->form()->checkbox(['name'=>'op'.$blog['id']])?></td>
                    <?php if ($isEditor): ?>
                    <td class="leftCell"><?= $this->form()->linkTo(['href'=> $url . "edit/" . $blog['id'], 'text' => $blog['title']]) ?></td>
                    <?php else: ?>
                    <td><link-to href="<?=  '/article/' . $blog['title_clean'] ?>" text="<?= $blog['title'] ?>" /></td>
                    <?php endif ?>
                </check>
                <td><?= $blog['author_name'] ?></td>
                <td><?= $pubdate ?></td>
                <td><?php if($blog['featured']): ?>
                    <img src="<?= $theme ?>/tick16.png" />
                    <?php endif ?></td>
                <td><?php if($blog['enabled']): ?>
                    <img src='<?= $theme ?>/tick16.png' />
                    <?php endif ?></td>
                <td><?php if($blog['comments']): ?>
                    <img src='<?= $theme ?>/tick16.png' />
                    <?php endif ?></td>
                </td>
                </tr>
            <?php endforeach ?>
            </tbody>
        </table>
        <select name="flagsel">
            <option value="enable">Enable</option>
            <option value="disable">Disable</option>
            <option value="comment">Comment</option>
            <option value="noComment">No Comment</option>
            <option value="feature">Feature</option>
            <option value="noFeature">No Feature</option>
        </select>
        <submit-btn  value="Change selected" />
        <hidden name="args" value="<?= $view->args ?>" ></hidden>
    </form>
</div>
