<?php
use WC\HtmlGem as Gem;
$assets->add(['bootstrap','DateTime']);
$url = $m->url;
$rec = $m->rec;
?>
<?= $assets->inline_css('form-format'); ?>

<div class="row">
    <div class="col"><?= Gem::linkTo(['href'=>$url . "index", 'text'=>"Back to Index"]) ?></div>
</div>


<div class="page-header">
    <h1>Edit <?=$m->table_name?></h1>
</div>

<?php echo $this->getContent(); ?>


    <div class="container">
<form action="<?= $url ?>save" class="form-horizontal" method="post">
    <div class="row">
    <div class="col-sm-10">
        <?= Gem::plainText(['label' => 'URL', 'name' => "url", "size" => 50, 'value' => $rec->url]) ?>
    </div>
</div>

<div class="row">
    <div class="col-sm-10">
        <?= Gem::datetime(['label' => 'Last update', 'name' => "last_read", "size" => 20, 'value' => $rec->last_read]) ?>
    </div>
</div>


<div class="row">
    <div class="col-sm-10">
        <?= Gem::plainText(['label' => 'Short name', 'name' => "nick_name", "size" => 30,   'value' => $rec->nick_name]) ?>
    </div>
</div>

<div class="row">
    <div class="col-sm-10">
        <?= Gem::plainText(['label' => 'Web site provider', 'name' => "provider", "size" => 30, "value" => $rec->provider]) ?>
    </div>
</div>
<?= Gem::hidden([ 'name' => "id",  'value' => $rec->id]) ?>
    
<div class="row">
    <div class="col">
        <?= Gem::multiline(['label' => 'Content (read-only)' , 'name' => "content",  'value' => $rec->content, "readonly"]) ?>
    </div>
</div>
    
<div class="row">
        <div class="col-sm-offset-2 col-sm-10">
            <?= Gem::submit(['value' => "Save", "class" => "btn btn-info btn-lg"]) ?>
        </div>
    </div>
</form>
        
    </div>
