<?php
$gem = $this->htmlgem;
$assets->add(['bootstrap','DateTime']);
$url = $m->url;
$rec = $m->rec;
?>
<?= $assets->inline_css('form-format'); ?>
<div class="row">
            <li class="previous"><?= $gem->linkTo(['href'=>$url . "index", 'text'=>"Index"]) ?>
</div>

<div class="page-header">
    <h1>Create <?= $m->table_name ?></h1>
</div>

<?php echo $this->getContent(); ?>
<div class="container">
<form action="<?=$url?>create" class="form-horizontal" method="post">
    <div class="row">
    <div class="col-sm-10">
        <?= $gem->plainText(['label' => 'URL', 'name' => "url", "size" => 30, 'value' => $rec->url]) ?>
    </div>
</div>

<div class="row">
    <div class="col-sm-10">
        <?= $gem->datetime(['label' => 'Last update', 'name' => "last_read", "size" => 20, 'value' => $rec->last_read]) ?>
    </div>
</div>

<div class="row">
    <div class="col">
        <?= $gem->multiline(['label' => 'Content' , 'name' => "content",  'value' => $rec->content]) ?>
    </div>
</div>

<div class="row">
    <div class="col-sm-10">
        <?= $gem->plainText(['label' => 'Short name', 'name' => "nick_name", "size" => 30,   'value' => $rec->nick_name]) ?>
    </div>
</div>

<div class="row">
    <div class="col-sm-10">
        <?= $gem->plainText(['label' => 'Web site', 'name' => "provider", "size" => 30, "value" => $rec->provider]) ?>
    </div>
</div>


    <div class="row">
        <div class="col-sm-offset-2 col-sm-10">
            <?= $gem->submit(['value' => "Save", "class" => "btn btn-info btn-lg"]) ?>
        </div>
    </div>
</form>
</div>