<?php

$gem = $this->htmlgem;

$url = $m->url;
$assets->add(['bootstrap']);
$btn_class = "btn btn-outline-primary";
?>

<div class="row">
    <div class="col text-center"><?= $gem->linkTo(['href' => $url . "index", 'text' => "Go Back", "class" => $btn_class]); ?>
        &nbsp; &nbsp;<?= $gem->linkTo(['href' => $url . "new", 'text' => "Create ", "class" => $btn_class]); ?>
    </div>
</div>

<div class="page-header">
    <h1>Search result</h1>
</div>

<?php echo $this->getContent(); ?>
<div class="container-fluid">
    <div class="row">
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>Short  Name</th>
                    <th>Provider</th>
                    <th>Url</th>
                    <th>Last Download</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
<?php foreach ($m->items as $rss_feed): ?>
                    <tr>
                        <td><?= $gem->linkTo(['href' => $url . "process/" .  $rss_feed->id, 'text'=>$rss_feed->nick_name]) ?></td>
                        <td><?= $rss_feed->provider ?></td>
                        <td><?= $rss_feed->url ?></td>
                        <td><?= $rss_feed->last_read ?></td>
                        <td><?= $gem->linkTo(['href' => $url . "edit/" . $rss_feed->id, 'text'=>"Edit"]); ?></td>
                    </tr>
<?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>
