<?php

Use WC\Assets,
    WC\UserSession;
?>
<!DOCTYPE html>
<html>

    <head>
        <title>Schema</title>
        <meta http-equiv='Content-Type' content='text/html; charset=utf-8'/>
        <meta name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=1.0; minimum-scale=1.0; user-scalable=no; target-densityDpi=device-dpi"/>
        <?= Assets::instance()->CssHeader(); ?>
        <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
    </head>
    <body>
       <p>Home page </p>
    </body>
</html>
