
{~
    @rec = @view->rec;
    @url = @view->url;
    @user = @view->user;
    @successLogins = @view->successLogins;
    @passwordChanges = @view->passwordChanges;
    @resetPasswords = @view->resetPasswords;
    @groups = @view->groups;
~}
<form method="post" action="/admin/user/post" autocomplete="off">

<div class='container outerwrap'>
    <div class='row'>
        <link-to href="{{ @url }}" text="User Index" ></link-to>
        <submit-btn name="save" ></submit-btn>        
    </div>
</div>

<div class="container-fluid body-wrap">
    <h2>Edit User</h2>

    <ul class="nav nav-tabs">
        <li class="active"><a href="#A" data-toggle="tab">Basic</a></li>
        <li><a href="#B" data-toggle="tab">Successful Logins</a></li>
        <li><a href="#C" data-toggle="tab">Password Changes</a></li>
        <li><a href="#D" data-toggle="tab">Reset Passwords</a></li>
        <li><a href="#E" data-toggle="tab">Groups</a></li>
    </ul>
    <hr>
<div class="tabbable outerwrap">
    <div class="tab-content">
        <div class="tab-pane active" id="A">
            
            <hidden name="id" value="{{ @user.id }}"></hidden>

            <div class="span4">

                <div class="form-group">
                    <label for="name">Name</label>
                    <text-field name="name" value="{{ @user.name }}"></text-field>
                </div>

            </div>

            <div class="span4">

                <div class="form-group">
                    <label for="email">E-Mail</label>
                    <text-field name="email" value="{{ @user.email }}"></text-field>
                </div>

                <div class="form-group">
                    <label for="status">Status</label>
                    <text-field name="status" value="{{ @user.status }}"></text-field>
                </div>


            </div>
        </div>

        <div class="tab-pane" id="B">
                <table class="table table-bordered table-striped" align="center">
                    <thead>
                        <tr>
                            <th>IP Address</th>
                            <th>Date</th>
                            <th>User Agent</th>
                        </tr>
                    </thead>
                    <check if="{{ @successLogins }}" >
                        <true>
                    <tbody>
                        <repeat group="{{ @successLogins }}" value="{{ @login }}">
                        <tr>
                            <td>{{ @login.created_at }}</td>
                            <td>{{ @login.status_ip }}</td>
                            <td>{{ @login.data }}</td>
                        </tr>
                        </repeat>
                    </tbody>
                    </true>
                    <false>
                        <tr><td colspan="3" align="center">User does not have successful logins</td></tr>
                        </false>
                    </check>
                </table>
        </div>

        <div class="tab-pane" id="C">
                <table class="table table-bordered table-striped" align="center">
                    <thead>
                        <tr>
                            <th>Date</th>
                            <th>IP Address</th>
                            <th>User Agent</th>
                        </tr>
                    </thead>
                     <check if="{{ @passwordChanges }}" >
                         <true>
                    <tbody>
                    <repeat group="{{ @passwordChanges }}" value="{{ @change }}">
                        <tr>
                            <td>{{ @change.created_at}}</td>
                            <td>{{ @change.status_ip }}</td>
                            <td>{{ @change.data }}</td>     
                        </tr>
                    </repeat>
                    </tbody>
                    </true>
                    <false>
                        <tr><td colspan="3" align="center">User has not changed his/her password</td></tr>
                    </false>
                     </check>
                </table>
        </div>

        <div class="tab-pane" id="D">
            <link-to href="{{ @url . 'sendConfirmation/' . @user.id }}" text="Email Password Reset" class="btn"></link-to>
                <table class="table table-bordered table-striped" align="center">
                    <thead>
                        <tr>
                            <th>Date</th>
                            <th>IP</th>
                            <th>Data</th>
                        </tr>
                    </thead>
                    <check if="{{ @resetPasswords }}" >
                         <true>
                    <tbody>
                        
                    <repeat group="{{ @resetPasswords }}" value="{{ @reset }}">
                        <tr>
                            <td>{{ @reset.created_at }}</td>
                            <td>{{ @reset.status_ip }}</td>
                            <td>{{ @reset.data }}</td>
                        </tr>
                    </repeat>
                    </tbody>
                    </true>
                    <false>
                        <tr><td colspan="3" align="center">User has not requested reset his/her password</td></tr>
                        </false>
                    </check>
                </table>
            </p>
        </div>
        <div class="tab-pane" id="E">
            <link-to href="{{ @url . 'groups/' . @user.id }}" text="Edit Groups" class="btn"></link-to>
                <table class="table table-bordered table-striped" align="center">
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Id</th>
                            <th>Created</th>
                        </tr>
                    </thead>
                    <check if="{{ @groups }}" >
                    <true>
                    <tbody>
                    
                    <repeat group="{{ @groups }}" value="{{ @group }}">
                        <tr>
                            <td>{{ @group.name }}</td>
                            <td>{{ @group.status }}</td>
                            <td>{{ @group.created_at }}</td>
                         </tr>
                    </repeat>
                    </tbody>
                    </true>
                    <false>
                        <tr><td colspan="4" align="center">User has no groups assigned</td></tr>
                    </false>
                    </check>
                </table>
   
        </div>

    </div>
</div>

</form>
<hr>
<form id="deleteUser" method="post" action="{{ @url .  'delete'}}">
<div>
    <hidden name="xcheck" value="{{ @view->xcheck }}" ></hidden>
    <hidden name="userId" value="{{ @user.id }}" ></hidden>
    <input type="submit" value="Delete User" class='btn'/>
</div>
    <hr>
</form>
<form id="sendConfirm" method="post" action="{{ @url . 'sendConfirm'}}">
<div>
    <hidden name="xcheck" value="{{ @view->xcheck }}" ></hidden>
    <hidden name="userId" value="{{ @user.id }}" ></hidden>
    <input type="submit" value="Send Confirm Email" class='btn'/>
</div>
</form>