<wc:init></wc:init>
{~
@view = \Base::instance()->get('view');
@url = @view->url;
@rec = @view->rec;
~}
<style>
    div.form-group  label {
        font-weight: bold;
        margin-right:10px;
        vertical-align: bottom;
    }

    p {
        font-size:1.2em;
    }
</style>

<div class='container novosti outerwrap'>
        <h3>Bookings</h3>
        <hr>
        <p>You have sent</p>
            <check if="{{ @view->sub === 1 }}">
                <true><hidden name="sub" value="{{ @view->sub }}" ></hidden></true>
            </check>
            <check if="{{ @rec.id }}">
                <true>            
                <div class="form-group row">
                    <div class="col-5">
                        <datetime label='Date entered' name="created_on" value="{{ @rec.created_on }}" readonly class="form-control" ></datetime>
                    </div>
                </div>
                </true>
            </check>
            <div class="form-group row">
                <div class="col-4">
                    <text-field  name="fullname" value="{{ @rec.fullname }}"  label='Full Name' readonly size="32" class="form-control"></text-field>
                </div>
              
                <div class="col-4">
                    <phone name="telephone" value="{{ @rec.telephone }}"  label='Phone number' readonly size="16" class="form-control"></phone>
                </div>
            </div>
             <div class="form-group row">
              <div class="col-6">
                    <email name="email" value="{{ @rec.email }}" label="Email"  readonly class="form-control" ></email>
                </div>
             </div>
            <div class="form-group row">
                <div class="col-6">
                    <text-field name="venue" value="{{ @rec.venue }}" label="Venue"  readonly class="form-control"></text-field>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-6">
                    <datetime name="date" value="{{ @rec.date }}" label="Date & Time"  readonly class="form-control"></datetime>
                </div>
            </div>
            <div class="form-group row">
            
             <div class="col-11">
                 <label>Other Details</label>
                <multiline name="message" cols="70" rows="5" value="{{ @rec.message }}" readonly></multiline>
             </div>
            </div>
</div>