<?php
if ($view->layout) {
    $this->layout($view->layout, $this->data);
}
$url = $m->url;
$blog = $m->blog;

?>

<div class='container outerwrap novosti pad10'>
    
    <?php  if (!empty($blog)): ?>
                <div class="<?= $blog['style ']?>" >
                    <?= $blog['article'] ?>
        </div>
<?php endif ?>
        <form id="regevt" method='post' action="<?= $url . 'post' ?>">
        <div id="regform">
                <?php $this->insert('form/email_form' , $this->data) ?>
            </div>
       </form>
</div>
