<?php
$rec = $m->rec;
if (empty($view->layout) && !empty($view->flash)):
    $this->insert('flash',$this->data);
endif;
$fm = $this->form();
?>
<style>
    div.form-group  label {
        font-weight: bold;
        margin-right:10px;
        vertical-align: top;
    }
</style>

<div class='container pad10'>
    <div class="outerwrap pad10">

<?php if (!empty($rec)): ?>         
            <div class="form-group row">
                <div class="col-5">
                        <?= $fm->plainText([ 'label' =>'Date sent' ,'name' => 'created_on', 
                                        'value' => $rec['senddate'] , "readonly", 'class' => 'form-control']) ?>
                </div>
            </div>
            <?php endif ?>
                    <div class="form-group row">
            <div class="col-4">
                     <?= $fm->plainText([ 'label' =>'Name' ,'name' => 'name', 'size' => 16,
                                        'value' => $rec['name'] , 'class' => 'form-control', "readonly"]) ?>
            </div>
            <div class="col-4">
                    <?= $fm->email([ 'label' =>'Your email' ,'name' => 'email',
                                        'value' => $rec['email'] , 'class' => 'form-control', "readonly"]) ?>
            </div>
            <div class="col-4">
                     <?= $fm->phone([ 'label' =>'Phone number' ,'name' => 'telephone', 'size' => 16,
                                        'value' => $rec['telephone'] , 'class' => 'form-control', "readonly"]) ?>
            </div>
        </div>
            <div class="form-group">
                <label>Message</label>
             <?= $fm->multiline([ 'name' => 'body', 'cols' => 80, 'rows' => 5,'value' => $rec['body'], "readonly" ]) ?>
            </div>
            <hr>
    </div>
</div>