
<?php
if ($view->layout) {
    $this->layout($view->layout,$this->data);
}
$google = $m->google;
$email = $m->email;
$mbr = $m->mbr;
$message = $m->message;
$countries = $m->countries;
$states = $m->states;
$fm = $this->form();
?>
                                                                                                         
<style>
    label {
        font-weight:bold;
        min-width:100px;
        text-align: right;
        margin-top: auto;

    }

    div.fcell label {
        display: inline-table;
        vertical-align:top;
    }
    .padx {
        padding:30px;
    }
    
</style>
<div class='container outerwrap padx'>
    <p>Sign-up form to receive the emailed ParraCAN Newsletter via Mail Chimp</p>
    <form id='signup' method='post' action='/id/signupPost'>
        <?php if( !empty($message) ): ?>

            <div class="alert alert-primary" role ="alert">
                <p class="message"><?= $message ?></p>
            </div>
<?php endif; ?>
        <div id='ctblock'>
            <div class="row">
                <div class="col-8">
                    <?= $fm->plainText(['label' => 'Email', 'name' => 'email', 
                        'value' => $email, 'size' => 50]) ?>
                </div>
            </div>
            <hr>
            <p>Contact Details</p>
            <hr>
            <div class="row" >
                <div class="col-6">
                    <?= $fm->plainText(['label' => 'First Name', 'name' => 'fname', 
                        'value' => $mbr['fname'], 'size' => 30]) ?>
                 </div>
                <div class="col-6">
                     <?= $fm->plainText(['label' => 'Last Name', 'name' => 'lname', 
                        'value' => $mbr['lname'], 'size' => 30]) ?>
                 </div>
            </div>
            <div class="row">
                <div class='col'>
                    <?= $fm->plainText(['label' => 'Address', 'name' => 'addr1', 
                        'value' => $mbr['addr1'], 'size' => 50]) ?>
                     <br>
                     <?= $fm->plainText(['label' => '_', 'name' => 'addr2', 
                        'value' => $mbr['addr2'], 'size' => 50]) ?>
                 </div>
            </div>
            <div class="row">
                <div class='col'>
                    <?= $fm->plainText(['label' => 'City', 'name' => 'city', 
                        'value' => $mbr['city'], 'size' => 40]) ?>
                    <?= $fm->select([ 'name' => 'state', 'label' => 'State', 
                                    'list' => $states, 'value' => $mbr['state'] ]) ?>
                 </div>
            </div>
            <div class="row">
                <div class='col-8'>
                    <?= $fm->plainText(['label' => 'Post-Code', 'name' => 'postcode', 
                        'value' => $mbr['postcode'], 'size' => 8]) ?>
                      <?= $fm->select([ 'name' => 'country_code', 'label' => 'Country', 
                                    'list' => $countries, 'value' => $mbr['country_code'] ]) ?>
                 </div>
            </div>
            <div class="row">
                <div class='col-5'>
                    <?= $fm->phone(['label' => 'Phone', 'name' => 'phone', 
                        'value' => $mbr['phone'], 'size' => 20]) ?>
                 </div>   
            </div>
            <div class="row">
                <div class='fcell col-12'>
                    <?= $fm->multiline(['label' => 'Volunteer info', 'name' => 'source', 
                        'value' => $mbr['source'], 'cols' => 50, 'rows' => 3]) ?>
                </div>   
            </div>
        </div>
        <?= $fm->hidden(['name' => 'xcheck', 'value' =>$m->xcheck ]) ?>
        
        <?php if ($google['enabled'] ): ?>
            <script>
                function onSubmit(token) {
                    document.getElementById("signup").submit();
                }
            </script>
            <script src="https://www.google.com/recaptcha/api.js" async defer></script>
            <button class ="g-recaptcha" data-sitekey="<?= $google['site'] ?>" data-callback="onSubmit">
                Signup
            </button> 
            <?php else: ?>
            <div class="form-group">
                <?= $fm->submit(['name' => 'login', 'value' => 'Signup', 'class' => 'btn btn-primary btn-large' ]) ?>
             </div>    
            <?php endif; ?>
    </form>
</div>