<?php
use WC\HtmlGem as Gem;
$url = $m->url;
$rec = $m->rec;
$xcheck = $m->xcheck;
$google = $m->google;
$blog = $m->blog;
$recid = $rec->id;
$formid = $m->formid;
$assets->add('validate');
?>
<style>
    div.form-group  label {
        font-weight: bold;
        margin-right:10px;
        vertical-align: top;
    }
</style>
<h3>Send email message to <?= $app->get('organization','our organization') ?>.</h3>
    <hr>
        <?php if ($m->sub === 1): ?>
            <?= Gem::hidden([ 'name' => 'sub', 'value' =>  $m->sub]) ?>
            <?php endif ?>
           <?php if ($recid): ?>         
               <?= Gem::hidden([ 'name' => 'id', 'value' =>  $recid]) ?>
            <div class="form-group row">
                <div class="col-5">
                        <?= Gem::datetime([ 'label' =>'Date sent' ,'name' => 'created_on', 
                                        'value' => $rec->senddate , "readonly", 'class' => 'form-control']) ?>
                </div>
            </div>
            <?php endif ?>
        <div class="form-group row">
            <div class="col-4">
                     <?= Gem::plainText([ 'label' =>'Name' ,'name' => 'name', 'size' => 16,
                                        'value' => $rec->name , 'class' => 'form-control']) ?>
            </div>
            <div class="col-4">
                    <?= Gem::email([ 'label' => 'Your email address' ,'name' => 'email',
                                        'value' => $rec->email , 'class' => 'form-control']) ?>
            </div>
            <div class="col-4">
                     <?= Gem::phone([ 'label' =>'Phone number' ,'name' => 'telephone', 'size' => 16,
                                        'value' => $rec->telephone , 'class' => 'form-control']) ?>
            </div>
        </div>
            <div class="d-flex form-group">
                <label>Message</label>
             <?= Gem::multiline([ 'name' => 'body', 'cols' => 80, 'rows' => 5,'value' => $rec->body ]) ?>
            </div>
        <hr>
            <?= Gem::xcheck([ 'name' => $xcheck['key'], 'value' =>  $xcheck['value'] ]) ?>
        
            <div class="d-flex  justify-content-center" >
                <?= Gem::submit(['id' => 'submit',  'name' => 'submit', 'value' => 'Send', 'class' => 'btn btn-outline-primary btn-lg' ]) ?>
                <label id="loading" style="display:none;">&nbsp; &nbsp; &nbsp; processing now ... </label>
            </div>    
        <hr>
         <?php if (!is_null($google) && $google['enabled']): ?>
            <div class="d-flex  justify-content-center"">
               <?= Gem::invisiCaptcha([ 'site' => $google['site'], 'formid' => $formid, 'ajax'=>'formid_submit()']) ?>
            </div>
        <?php endif ?>
 <?php if (is_null($google) || !$google['enabled']) {
 $blob = <<<EOJS
<script>        
 var grecaptcha = {
         getResponse : function() { return true; }
         };
 </script>
EOJS;
 $assets->addJS($blob);
 }
?>
<?php
$blob = <<<EOJS
<script>         
function prep_valid() {
  // Initialize form validation on the registration form.
  // It has the name attribute "registration"

  $("#$formid").validate({
    // Specify validation rules
    rules: {
      // The key name on the left side is the name attribute
      // of an input field. Validation rules are defined
      // on the right side
      name: "required",
      email: {
        required: true,
        // Specify that email should be validated
        // by the built-in "email" rule
        email: true
      },
      body: {
        required: true,
        minlength: 5
      }
    },
    // Specify validation error messages
    messages: {
      name: "Please enter your name",
      body: "Please enter a message",
      email: "Please enter a valid email address"
    },
    // Make sure the form is submitted to the destination defined
    // in the "action" attribute of the form when valid
    submitHandler: function(form) {
        if (grecaptcha.getResponse()) {
            formid_submit();
        }else{
            grecaptcha.reset();
            grecaptcha.execute();
        } 
    }
  });
}
</script>
EOJS;
$assets->addJS($blob);
?>