<?php
$assets->add('bootstrap');
$url = $m->url;
$args = explode("?",$m->url,2);
if (count($args) > 1) {
    $path = $args[0];
    $query = $args[1];
}
else {
    $path = $url;
    $query = "";
}
?>

<div class='container outerwrap novosti pad10'>
    <p style="font-size:1.2em;">Redirect for HTTPS service
    <a id="redirect" href="<?= $url ?>"><?= $path ?></a></p>
    <div id="message"></div>
</div>

<script>
function pageRedirect(){
 var delay = 4000; // time in milliseconds

 var url = document.getElementById("redirect").getAttribute("href");
 // Display message
 document.getElementById("message").innerHTML = "Please wait for redirect to secure https";

 setTimeout(function(){
  window.location = url;
 },delay);
 
}

window.onload = pageRedirect;

</script>
