<?php
$gem = $this->htmlgem;

$orderalt = $m->orderalt;
$col_arrow = $m->col_arrow;


$page = $m->page;
$data = $page->items;
$pgsize = "?pgsize=" . $m->pgsize;
$ubase =  $m->url . $pgsize . "&orderby=";
$link = $ubase . $m->orderby;  

$assets->add('bootstrap');
?>


<div class='outerwrap pad10'>
    <div class="container-fluid">
        <?php if ($page->last > 1 ): ?>
        &nbsp; | &nbsp;<?= $gem->linkTo(['href' => $link, 'text'=> "First"]) ?>
        &nbsp; | &nbsp;<?= $gem->linkTo(['href' => $link . '&page='. $page->before, 'text' => "Previous"]) ?>
        &nbsp; | &nbsp;<?= $gem->linkTo(['href' => $link . '&page=' . $page->next, 'text' => "Next"]) ?>
        &nbsp; | &nbsp;<?= $gem->linkTo(['href' => $link . '&page=' . $page->last, 'text' => "Last"]) ?>
    <?php endif ?>
    &nbsp;|&nbsp;  <?= $page->current . "/" . $page->last ?>
    &nbsp;|&nbsp;  
        <a href="/admin/member/new" >New Record</a> &nbsp;|&nbsp;  
        
        <div class="row">
            <div class="col-1">
                # <span class="titlecol"><?= $gem->linkTo(['href' => $ubase . $orderalt['name'], 'text' => 'Name']) . $col_arrow['name'] ?></span>
            </div>
            <div class="col-2">
                <span class="titlecol"><?= $gem->linkTo(['href' => $ubase . $orderalt['surname'], 'text' => 'Surname']) . $col_arrow['surname'] ?></span>
            </div>
            <div class="col-3">
                <span class="titlecol"><?= $gem->linkTo(['href' => $ubase . $orderalt['email'], 'text' => 'Email']) . $col_arrow['email'] ?></span>
            </div>
            <div class="col-2">
                <span class="titlecol"><?= $gem->linkTo(['href' => $ubase . $orderalt['phone'], 'text' => 'Phone']) . $col_arrow['phone'] ?></span>
            </div>
            <div class="col-2">
                <span class="titlecol"><?= $gem->linkTo(['href' => $ubase . $orderalt['city'], 'text' => 'Suburb']) . $col_arrow['city'] ?></span>
            </div>
            <div class="col-1">
                <span class="titlecol"><?= $gem->linkTo(['href' => $ubase . $orderalt['cdate'], 'text' => 'Created']) . $col_arrow['cdate'] ?></span>
            </div>
            <div class="col-1">
                <span class="titlecol"><?= $gem->linkTo(['href' => $ubase . $orderalt['status'], 'text' => 'Status']) . $col_arrow['status'] ?></span>
            </div>
        </div>
        <hr>
        <style>
            .row-striped div.row:nth-of-type(odd) {
                background-color: aliceblue;
            }
            .row-striped div.row:nth-of-type(even) {
                background-color: azure;
            }            
        </style>
        <?php $rno = 0 ?>
        
        <div class="row-striped">
            <?php foreach($data as $row):
                $rno += 1; ?>
            <div class="row">
            <div class="col-3">
                 <?= $rno . ' ' . $gem->linkTo(['href' => '/admin/member/edit/' . $row['id'], 'text' => $row['fname'] . ' &nbsp; ' . $row['lname'] ]) ?>
                </div>
                <div class="col-3">
                    <?= $row['email_address'] ?>
                </div>
                <div class="col-2">
                    <?=  $row['phone'] ?>
                </div>                
                <div class="col-2">
                    <?=  $row['city'] ?>
                </div>
                <div class="col-1">
                    <?=  $row['create_date']?>
                </div>
                <div class="col-1">
                    <?=  $row['email_status']?>
                </div>
            </div>
            <?php endforeach; ?>
        </div>
    </div>
</div>