<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["rss_link", "Back"]) ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>Edit rss_link</h1>
</div>

<?php echo $this->getContent(); ?>

<form action="rss_link/save" class="form-horizontal" method="post">
    <div class="form-group">
    <label for="fieldFeedId" class="col-sm-2 control-label">Feed</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["feed_id", "type" => "number", "class" => "form-control", "id" => "fieldFeedId"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldXmlJson" class="col-sm-2 control-label">Xml Of Json</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["xml_json", "size" => 30, "class" => "form-control", "id" => "fieldXmlJson"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldExtract" class="col-sm-2 control-label">Extract</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textArea(["extract", "cols" => 30, "rows" => 4, "class" => "form-control", "id" => "fieldExtract"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldExtractTitle" class="col-sm-2 control-label">Extract Of Title</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["extract_title", "size" => 30, "class" => "form-control", "id" => "fieldExtractTitle"]) ?>
    </div>
</div>


    <?php echo $this->tag->hiddenField("id") ?>

    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <?php echo $this->tag->submitButton(["Save", "class" => "btn btn-default"]) ?>
        </div>
    </div>
</form>
