<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-header">
    <h1>Search rss_link</h1>
    <p><?php echo $this->tag->linkTo(["rss_link/new", "Create rss_link"]) ?></p>
</div>

<?php echo $this->getContent() ?>

<?php echo $this->flash->output() ?>

<form action="rss_link/search" class="form-horizontal" method="get">
    <div class="form-group">
    <label for="fieldId" class="col-sm-2 control-label">Id</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["id", "type" => "number", "class" => "form-control", "id" => "fieldId"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldFeedId" class="col-sm-2 control-label">Feed</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["feed_id", "type" => "number", "class" => "form-control", "id" => "fieldFeedId"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldXmlJson" class="col-sm-2 control-label">Xml Of Json</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["xml_json", "size" => 30, "class" => "form-control", "id" => "fieldXmlJson"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldExtract" class="col-sm-2 control-label">Extract</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textArea(["extract", "cols" => 30, "rows" => 4, "class" => "form-control", "id" => "fieldExtract"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldExtractTitle" class="col-sm-2 control-label">Extract Of Title</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["extract_title", "size" => 30, "class" => "form-control", "id" => "fieldExtractTitle"]) ?>
    </div>
</div>


    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <?php echo $this->tag->submitButton(["Search", "class" => "btn btn-default"]) ?>
        </div>
    </div>
</form>
