<?php 
use WC\HtmlGem as Gem;
$url = $m->url;
$assets->add('bootstrap');
?>

<div class='container'>
    <div align="center">
        <h2>Create Content</h2>
    </div>
    <form method='post' action="<?= $url . 'postnew' ?>">
        <table>
            <tr>
                <td align="right">
                    <label for="title">Title</label>
                </td>
                <td align="left">
                    <?= Gem::plainText(['name' => 'title', 'size' => 30]) ?>
            </td>
            </tr>
            <tr>
                <td align="right"> <?= Gem::submit(['value' => 'Save', 'class' => "pure-button pure-button-primary"]) ?></td>
            </tr>

        </table>

    </form>
</div>


