<?php
$gem = $this->htmlgem;
$assets->add( [ 'bootstrap','grid', 'cat-menu', 'styles'] );
$assets->minify('cat-menu');
$blog = $m->blog;
$list = $m->list;
$btn_class = 'btn btn-outline';
?>
<style>
    .color-fill {
        background-color:paleturquoise;
        min-height:10px;
    }
@media screen and (max-width: 900px){
    #mgrid[data-columns]::before {
        content: '3 .column.size-1of1';
    }
}

@media screen and (min-width: 901px) and (max-width: 1300px) {
    #mgrid[data-columns]::before {
            content: '2 .column.size-1of2';
    }
}
@media screen and (min-width: 1301px) {
    #mgrid[data-columns]::before {
            content: '3 .column.size-1of3';
    }
}

.column { float:left; }
.size-1of1 { width: 100%; }
.size-1of2 { width: 50%; }
.size-1of3 { width: 33.333%; }

.title {
    font-size:1.2em;
}
</style>
<div class="container" >
    <p>Revisions for <span class="title"><?=$blog->title?></span></p>
</div>
<div class='container-fluid'>
    <?php if (!empty($m->list)): ?>

    <div id="list">
        <?php $fid = 0;
                foreach($m->list as $menu): 
                    $itemUrl = "/admin/blog/rget/" . $blog->id . "/" . $menu->id;
                 
            ?>
               <div class="row">
                <div class="col-3">
                    <a class="<?=$btn_class?>" id="f<?=$fid+1?>" href="<?= $itemUrl ?>" onclick="fetch(this);return false;"><?=$menu->id . ")"?> View </a>
                </div>
                <div class="col-3">
                    <a class="<?=$btn_class?>" id="f<?=$fid+2?>" href="<?= $itemUrl . '?html=1' ?>" onclick="fetch(this);return false;"> as HTML</a>
                </div>
                <div class="col-3">
                    <a class="<?=$btn_class?>" id="f<?=$fid+3?>" href="<?= '/admin/blog/edit/' . $blog->id . '?revid=' . $menu->id ?>"> Edit Revision #<?= $menu->id ?> </a>
                </div>
                </div>
               <?php $fid+=3;  endforeach ?>
    </div>
    <div class="col-10">
    <div id="article"></div>
    </div>
    <div class="hidden">
        <a id="first_link" href="<?= $m->firstId ?>" onclick="fetch(this);return false;">#First#</a>
    </div>
    </div>
<?php endif ?>
</div>
