<?php
//$view = $this->data['view'];

$evt = $m->evt;
$rego = $m->rego;

if ($view->layout) {
    $this->layout($view->layout, $this->data);
}
$fm = $this->form();

?>


<style>
    label {
        min-width:150px;
        text-align:right;
        padding-right:10px;
    }
    
</style>
<div class="container-fluid body-wrap">
    <hr>
    <form id="edtevt" method="post" action="/admin/eventpost">
        <?= $fm->hidden( ['name'=>'id', 'value'=> $evt['id'] ]) ?> 
        <div class="row">
            <div class="col-4">
                <?= $fm->datetime(['label' => "From", 'name' => "fromTime", 'size' => 20, 'value' => $evt['fromTime']]) ?>
             </div>
             <div class="col-4">
                <?= $fm->datetime(['label' => "To", 'name' => "toTime", 'size' => 20, 'value' => $evt['toTime']]) ?>
           </div>
        </div>
        <div class="row">
             <div class="col-4">
                <?= $fm->plainText(['label' => "Slug", 'name' => "slug", 'size' => 20, 'value' => $evt['slug']]) ?>
            </div>
            <div class="col-4">
                <?= $fm->checkbox(['text' => 'Enabled', 'name' => 'enabled', 'checked' => $evt['enabled']]) ?>
            </div>
        </div>
        <div class="row">
            <div class="col-3"></div>
            <div class="col-4">
                <?= $fm->submit(['name' => 'submit', 'value' => 'Update' ]); ?>
            </div>
        </div>
    </form>
    <hr>
        <?php if (!empty($rego)): ?>
              <div class="row body-wrap pad10">
                  <div class="col-2">
                  <h1>Registrations</h1>
                  </div>
                <div class="col-10">
                <?php foreach($rego as $rg): ?>  
                    <div class="row">
                        <div class="col-3"><?= $rg['fname'] ?>&nbsp;<?= $rg['lname'] ?></div>
                        <div class="col-3"><?= $rg['email'] ?></div>
                        <div class="col-2"><?= $rg['phone'] ?></div>
                        <div class="col-1"><?= $rg['people'] ?></div>
                        <div class="col-2"><?= $rg['created_at'] ?></div>
                    </div>
                    <hr>
                <?php endforeach ?>
                </div>
              </div>
              <?php endif ?>
</div>
