<?php
if (isset($m->layout)) {
    $this->layout($m->layout, $this->data);
}
$eblog = $m->eblog;
$hasEvent = !empty($eblog);
$reg = $m->register;
$fm = $this->form();

?>

<?= $fm->hidden(['name' => 'id', 'value' => $reg['id']]) ?>
<?= $fm->hidden(['name' => 'eventid', 'value' => $eblog['eventid']]) ?>

<div class="row">
    <div class="col-12">
        <?= $fm->plainText(['label' => 'First name', 'name' => 'fname', 
                                'value' => $reg['fname'], 'size' => 40]) ?>    </div>
</div>
<div class="row">
    <div class="col-12">
        <?= $fm->plainText(['label' => 'Last name', 'name' => 'lname', 
                                'value' => $reg['lname'], 'size' => 40]) ?>
    </div>
</div>
<div class="row">
    <div class="col-12">
         <?= $fm->email(['label' => 'Email', 'name' => 'email', 
                                'value' => $reg['email'], 'size' => 40]) ?>
        <span>Optional to receive email link for edit or delete registration</span>
    </div>
</div>
<div class="row">
    <div class="col-12">
                 <?= $fm->phone(['label' => 'Phone', 'name' => 'phone', 
                                'value' => $reg['phone'] ]) ?>
        <span>Optional mobile number</span>
    </div>
</div>
<div class="row">
    <div class="col-12">
        <label for="people">Addition Persons</label>
                         <?= $fm->number(['name' => 'people', 
                                'value' => $reg['people'], 'size' => 4 ]) ?>
    </div>
</div>
<div class="row">
    <div class="col-2">
    </div>
      <?php if (empty ($reg['id'])): ?>
            <div class="col-4">
                <?= $fm->submit(['name' => 'submit', 'value' => 'Register']) ?>
               
            </div>
         <?php else: ?>
                <div class="col-2">
                     <?= $fm->submit(['name' => 'submit', 'value' => 'Update']) ?>
                </div>
                <div class="col-2">
                     <?= $fm->submit(['name' => 'delete', 'value' => 'Delete']) ?>
                </div>
        <?php endif; ?>
    </div>
</div>
