<?php
if ($view->layout) :
    $this->layout($view->layout, $this->data);
endif;
$eblog = $m->eblog;
$hasEvent = !empty($eblog);
$reg = $m->register;
?>

<style>
    label {
        min-width:10em; 
        text-align:right;
        padding-right:10px;
    }
    .eblog {
        background-color: antiquewhite;
    }
</style>

<div class="container-fluid body-wrap">
    <div class="row">
        <div class="col-6 text-center">
            <h4>Registration Page for Event</h4>
        </div>
    </div>
        <?php if ($hasEvent): ?>
            <form id="regevt" method="post" action="/register/regpost">
            <div id="regform">
                <?php $this->insert('events/regform' , $this->data) ?>
            </div>
        </form>
    <hr>
    <div class="eblog">
        <div class="<?= $eblog['style'] ?>">
            <?= $eblog['article'] ?>
        </div>
    </div>
<?php else: ?>
        <p>Event Page not found</p>
<?php endif; ?>
</div>