<wc:init></wc:init>
{~
@view = \Base::instance()->get('view');
@eblog = @view->eblog;
@hasEvent = !empty(@eblog);
@reg = @view->register;
~}

<style>
    label {
        min-width:10em; 
        text-align:right;
        padding-right:10px;
    }
</style>

<div class="container-fluid body-wrap">
    <div class="row">
        <div class="col-6 text-center">
            <h4>Registration Page for Event</h4>
        </div>
    </div>
    <check if="{{@hasEvent}}">
        <true>
        <div class="{{@eblog.style}}">
            {{ @eblog.article | raw }}
        </div>
        <form id="regevt" method="post" action="/register/regpost">
            <div id="regform">
                <include href="events/regform.phtml"></include>
            </div>
        </form>

        </true>
        <false>
        <p>Event Page not found</p>
        </false>
    </check>
</div>