<wc:init></wc:init>
<!--  url("{{ @theme }}/tile-fog2.png"); -->
<style>
nav  {
    background-image: url( "{{ @theme }}/tile-fog.png" );
    color:black;
}
ul.navbar-nav a {
    font-size:1.2em;
}
.nav-link {
    font-weight:bold;
}
.navbar-brand {
    padding-top:0;
    padding-bottom:0;
}
.navbar {
    padding:0 0;
    margin: 0 0;
}
.site-logo img {
    max-height: 3.2em;
    padding: 5px;
    
}

.view-title {
    background-color: white;
    color:darkslateblue;
    font-size:1.5rem;
    padding-right:10px;
    border-right-style: solid;
    border-right-width: 1px;
}


</style>

<nav class="navbar navbar-expand-lg navbar-light ">
    <div class="view-title">
        <check if="{{ UserSession::isLoggedIn('User') }}">
            <true>
            <a class="site-logo" href="/"><img src="{{ @theme }}/heat_extinction.png"></a> 
            </true>
         <false>
        <a class="site-logo" href="/"><img src="{{ @theme }}/site-logo-small.png"></a>
         </false>
        </check>
        <span>{{ @view->title }}</span>
        
    </div>
    <button class="navbar-toggler" type="button" data-toggle="collapse" 
            data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
            <include href="generated/dropdowns.phtml"></include>
        </ul>
    </div>
<check if="{{ UserSession::isLoggedIn('User') }}"><false>
        <a class="site-logo" href="/login"><img src="{{ @theme }}/heat_extinction.png"></a> 
        </false>
</check>
</nav>