{~
    @view = \Base::instance()->get('view');
    @cat = @view->cat;
    @url = @view->url;
~}

<div class='header row'>
    <div class="outerwrap pad10">
    <link-to href="{{ @url  }}" text="Category List"  class="btn btn-warning"></link-to><span class="btn">{{ @view->title }}</span>
    </div>
</div>
<div class="container pad10">
    
<form action="{{ @url . 'post' }}" method="post">
    <check if="{{ isset(@cat.id) && @cat.id > 0 }}">
        <true>
    <div class="form-group row">
        <label class="col-form-label" >Id</label>
        <text-field name="id" value="{{ @cat.id }}" readonly="readonly"></text-field>
    </div>
    </true>
    </check>
     <div class="form-group row">
        <label class="col-form-label" >Name</label>
        <text-field name="name" value="{{ @cat.name }}" ></text-field>
        <?php echo $form->render("name"); ?>
   </div>
    <div class="form-group row">
        <label class="col-form-label" >Name Clean</label>
        <text-field name="name_clean" value="{{ @cat.name_clean }}" ></text-field>
  </div>
   <div class="form-check row">
        <label class="col-form-label" >Enabled</label>
        <checkbox name="enabled" checked="{{ @cat.enabled }}"></checkbox>
      </div>
    <p>
        <input type="submit" value="Save" />
    </p>

</form>
</div>
<F3:asset src="/css/admin.css" priority="5"></F3:asset>