{~
    @view = \Base::instance()->get('view');
    @page = @view->page;
    @url = @view->url;
~}
<div class="container body-wrap">
    <div class="row">
<span class="title">Index</span>
<link-to href="{{ @url . 'new' }}" text="New Category" class="btn btn-outline-primary"></link-to>
    </div>
<div class="container body-wrap">
<table class="table table-bordered table-striped" align="center">
    <thead>
        <tr>
            <th style="width:65%;">Category</th>
            <th style="width:20%;">URL Part</th>
            <th style="width:15%;">Enabled</th> 
        </tr>
    </thead>

    <tbody>
    <repeat group="{{ @page->items }}" value="{{ @cat  }}">
            <tr>
                <td class="leftCell"><link-to href="{{ @url . 'edit/' . @cat.id  }}" text="{{ @cat.name }}" ></link-to></td>
                <td>{{ @cat.name_clean }}</td>
                <td><check if="{{ @cat.enabled }}"><true>Y</true><false>N</false></check></td>
            </tr>
    </repeat>
    </tbody>

</table>

</div>
      </div>  

