<?php
//$gem = $this->htmlgem;
$blog = $m->blog;
$metadata = $m->metadata;
$back = $m->back;
$theme = '/' . $m->theme;
$revision = $m->revision;
$assets->add(['bootstrap','styles']);
$page_url = "https://" . $app->domain . "/article/" . $blog->title_clean;

$zentix = $app->use_zentix;
$facebook = $app->want_facebook;
if ($facebook) {
    $m->want_facebook = true;
    $m->fbook = $app->getSecrets('facebook');
}
?>


<style>
    .cmtx_container {
        padding:0.2em;
        background-color:palegoldenrod;
    }
    .cmtx_form_heading {
        padding-left: 0.5em;
    }
    
    div#title-box {
        background-color:white;
        font-family: Times;
        font-weight: bold;
        font-size:1.8em;
        margin:10px;
    }
    div#article-box {
        border-width:0;
    }
    div#metadata {
        background-image: url( "<?= $theme ?>/tile-fog.png" );
    }
    div.article-wrap {
        background-color: white;
        border-radius: 8px;
    }
</style>
<div class='container article-wrap'>

    <div  class="row">
        <div class="col-6">
            <?php if($back): ?>
                Back to <a href="<?= $back ?>"><?= $m->backname ?></a>&nbsp; &nbsp; &nbsp; 
            <?php endif; ?>
        </div>
    </div>

    <div id="article-box">
    <div class='<?=$blog->style ?>' >
        <div class="row">

             <div class="col">

                <div id="title-box"><?= $blog->title ?></div>

             </div>
                <?php if ($app->want_facebook): ?>

                 <?php $this->partial('facebook_share', [
                        'coded_url'=>urlencode($page_url),
                        'canonical' => $m->canonical
                    ]); ?>
                 

                     <?php endif ?>
        </div>
        <div class="row">
            <div class="col">
                <?= $revision->content ?>
            </div>
        </div>
    </div>
    </div>
    <?php if ( !empty($metadata) ): ?>
        <div class='container' id='metadata' style='font-size:0.6em;'>
            <div class='table'>
                <?php foreach($metadata as $mtag): ?>
                   <?php if ($mtag['display'] == 1 && strlen($mtag['content'] ) >0): ?>
                        <div class="row">
                            <div class='col-1'><?= $mtag['meta_name'] ?>:</div>
                            <div class='col-8'><?= $mtag['content'] ?></div>
                        </div>
                <?php endif; ?>
                <?php endforeach; ?>
            </div>
        </div>
 <?php endif; ?>
    <hr />
</div>

<?php if ( $blog->comments ): ?>
<div style='clear:both;'></div>
<?php if ($app->want_facebook): ?>
    <div class="outerwrap">
        <div id="fb-root"></div>
        <fb:login-button autologoutlink="True" length="short" background="white" size="large"></fb:login-button>
        <div class="fb-comments" data-href="<?= $m->canonical ?>" data-width="960" data-numposts="5"></div>
    </div>
<?php elseif ($app->use_zentix): ?>
    <div class="comment-wrap">
    <?php
    $cmtx_identifier = 'b' . $blog->id;
    $cmtx_reference = $blog->title;
    $cmtx_folder    = '/posts/';
    require ($_SERVER['DOCUMENT_ROOT'] . $cmtx_folder . 'frontend/index.php');
    ?>
    </div>

<?php endif; ?>
<?php endif;  // comments ?>
