<?php 
    $images = $m->images;
?>

<style>
.carousel-inner,.carousel,.item,.fill {
  height: <?=$m->maxHeight ?>px;
  width:100%;
  background-position:center center;
}   

.carousel-inner {
    background-color:black;
}
.carousel-inner img {
    margin: auto;
}
</style>

<?php if (!empty($images)): 

  $row_id = 0;
  ?>   
    <div id="gallery-c" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner">
    <?php foreach($images as $fup): 
      $info = $fup['description'];
      $row_id = $row_id + 1;
      $chkid = "chk" . $row_id;
      $idate = strtotime($fup['date_upload']);
      $itemClass = ($row_id === 1) ? "carousel-item active" : "carousel-item";
        $img_path = "/" . $fup['path'] . "/thumbs/" .   $fup['name'] . ".png";
        $doc_url = "/" . $fup['path'] . "/" .   $fup['name'] ;
    ?>
     <div class="<?=$itemClass ?>">
         <a href="<?=$doc_url?>"><img  class="d-flex align-items-center" src="<?=$linkpath .  $fup['name'] ?>"  title="<?=$info ?>" alt="<?='slide ' . $row_id ?>" ></a>
    </div>
    <?php endforeach ?>
<a class="carousel-control-prev" href="#gallery-c" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#gallery-c" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
<?php else: ?>
            <p>No image files in this gallery yet</p>
<?php endif ?>
