<?php
$gem = $this->htmlgem;
$series = $m->series;
$us = $this->user_session;
$assets->add('bootstrap');
?>
<style>
    p {
        font-size:1.3em;
    }
</style>
<div class="outerwrap padborder">
    <div class="row">
        <div class="col-4">
            <h2>Series</h2>
        </div>
         <div class="col-4">
            <?= $gem->linkTo(['href' => '/admin/series/new', 'text' => 'New Series record']) ?>
        </div>
    </div>
    <?php if ( !empty($series)): ?>
    <hr>
    <true>
            <div class="row" style="margin-bottom:5px;">
                <div class="col-1"><span>ID</span></div>
                <div class="col-2"><span>Name</span></div>
                <div class="col-1"><span>Tag</span></div>
            <div class="col-8"><span>Description</span></div>
        </div>
    <hr>
    <?php if ($us->auth('Editor')) 
    {
        $href = "/admin/series/edit/";
    }
    else {
        $href = "/series/";
    }  
    ?>

    <?php foreach($series as $sr): ?>
        <div class="row" style="margin-bottom:5px;">
            <div class="col-1"><p><?= $sr->id ?></p></div>
            <div class="col-2"><p><a href="<?= $href . $sr->id ?>"><?= $sr->name ?></a></p></div>
            <div class="col-1"><p><?= $sr->tinytag ?></p></div>
            <div class="col-8"><p><?= $sr->description ?></p></div>
        </div>
    <?php endforeach ?>
    <?php endif  ?>
</div>
