<?php
$series = $m->series;
$episodes = $m->episodes;
$assets->add('bootstrap');
?>


<style>
    p {
        font-size:1.3em;
    }
</style>
<div class="outerwrap padborder">
    <div class="row">
        <div class="col-4">
            <h2><?= $series->name ?></h2>
        </div>
        <div class="col-8">
            <p><?= $series->description  ?></p>
        </div>
    </div>
    <?php if (!empty($episodes)): ?>
    <hr>
    <?php foreach( $episodes as $ep): ?>
        <div class="row" style="margin-bottom:5px;">
           
            <div class="col-6"><p><a href="/gallery/view/<?= $ep->name ?>"><?= $ep->description ?></a></p></div>
            <?php if ($this->user_session->auth('Admin')): ?>
            <div class="col-6"><p><a href="/admin/gallery/edit/<?= $ep->name ?>"><?= $ep->name ?></a></p></div>
            <?php endif ?>
        </div>
<?php endforeach; ?>
<?php endif; ?>
</div>
