<!DOCTYPE html>
<html lang="en">
    <wc:init></wc:init>
    <head>
        <meta charset="UTF-8" />
        <title>{{ @view->title }}</title>
    <check if="{{@view->metaloaf}}">
        <repeat group="{{@view->metaloaf}}" value="{{@meta}}">
            {{ @meta | raw }}
        </repeat>
    </check>
    <f3:link></f3:link>
    <f3:css-header></f3:css-header>    
</head>
<body>
<check if="{{ @view->nav }}">
    <true>
    <include href="{{ @view->nav }}" />
    </true>
</check>
<check if="{{ !empty(@view->flash) }}"><true>
    <F3:repeat group="{{ @view->flash }}" value="{{ @msg }}">
        <div class="alert alert-{{ @msg.status }} alert-dismissable">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            {{ @msg.text | raw }}
        </div>
    </F3:repeat>
    </true></check>
<check if="{{ @view->content }}">
    <true>
    <div>
        <include href="{{ @view->content }}"></include>
    </div>
    </true>
</check>

<footer class='page-footer font-small indigo' >
    <div class="row" >
       <div class="col text-muted">
            {~
            @f3 = \Base::Instance();
            echo( "Session as " . UserSession::sessionName() );
            ~}
        </div>
        <div class="col text-muted"> 
            &copy;&nbsp;{{@f3->get('organisation')}}

        </div>
        <div class="col text-muted">            
            {{ \WC\App::end_stats(@f3) }}
        </div>
    </div>
</footer>
<f3:js-footer></f3:js-footer>
</body>
</html>
