<head>
<?php use \WC\Assets; 
    use \WC\UserSession; 
?>
    <meta charset="UTF-8" >
    <meta name="viewport" content="width=device-width, initial-scale=1" >
    <?php
    if ($m->metaloaf): 
        foreach($m->metaloaf as $meta):
            echo($meta) . PHP_EOL;
        endforeach;
    endif; ?>
    <?php if (isset($m->title)): ?>
    <title><?= $m->title ?></title>
    <?php endif; ?>
    <?= Assets::instance()->CssHeader(); ?> 
</head>