<?php use \WC\Assets; 
    use \WC\UserSession; 
?>
<div class="clear"></div>
<!-- std_foot -->
<footer class="page-footer">
    <div class="row" >
        <div class="col-3">
            <?php
            $f3 = \Base::Instance();
            $sid = UserSession::sessionName();
            if ($sid !== 'NULL') {
                echo("<a href=\"/end_session\">End Session: " . $sid . "</a>");
            }
            else {
                echo("No session");
            }
            ?>
        </div>
        <div class="col-3"> 
            &copy;&nbsp;<?= $f3->get('organization') ?>
        </div>
        <div class="col-6">            
            <?= \WC\App::end_stats($f3); ?>
        </div>
    </div>
</footer>
<?= Assets::instance()->JsFooter(); ?>