<?php use \WC\Assets; 
    use \WC\UserSession; 
?>
<div class="clear"></div>
<footer class="page-footer">
    <div class="row" >
        <div class="col-3">
            <?php
            $f3 = \Base::Instance();
            echo( "Session: " . UserSession::sessionName() );
            ?>
        </div>
        <div class="col-3"> 
            &copy;&nbsp;<?= $f3->get('organization') ?>
        </div>
        <div class="col-6">            
            <?= \WC\App::end_stats($f3); ?>
        </div>
    </div>
</footer>
<?= Assets::instance()->JsFooter(); ?>