<wc:init></wc:init>
{~ 
@view = Base::Instance()->get('view');
@images = @view->images;
@gallery = @view->gallery;
@series = @view->series;
@post = @view->post;
~}
<style>
    textarea.form-control {
        margin-left:10px;
        margin-right:10px;
    }

    label{
        text-align: right;
        margin-right:10px;
        min-width: 120px;
        font-weight: bold;
    }
</style>
<include href="gallery_adm/title.phtml" />

<div class="container-fluid outerwrap">
    <form id="galedit" action="/admin/gallery/post" method="post">
        <hidden name="id" value="{{@gallery.id}}"></hidden>
        <div class="row">
            <div class="col-10">
                <label for="description" class="control-label">Description</label>
                <multiline cols="80" name="description" value="{{ @gallery.description }}"></multiline>
            </div>
            <div class="col-1">
                <submit-btn value="Update Gallery" class="btn btn-danger "></submit-btn>
            </div>
        </div>
        <div class="row">
            <div class="col-3">
                <select-menu name="seriesid" label="Series" list="{{@series}}" value="{{@gallery.seriesid}}"></select-menu>
            </div>
            <div class="col-4">
                <label for="leva_path" class="control-label">Previous</label>
                <text-field size="30" name="leva_path" value="{{ @gallery.leva_path }}"></text-field>
            </div>
            <div class="col-4">
                <label for="prava_path" class="control-label">Next</label>
                <text-field size="30" name="prava_path" value="{{ @gallery.prava_path }}"></text-field>
            </div>
        </div>
        <div class="row">
            <div class="col-2">
                <checkbox name="view_thumbs" text="View Thumbs" checked="{{@gallery.view_thumbs}}"></checkbox>
            </div>
            <div class="col-6">
                
                <datetime label="Last upload" name="last_upload" size="20" value="{{@gallery.last_upload}}" ></datetime>
            </div>
            
        </div>
    </form>
    <hr>
    <span class="pull-right"><link-to href="{{ @post }}" class="btn btn-warning" text="{{ 'Galleries'}}"/></span>
    <span class="pull-right"><link-to href="{{ @post  . 'scan/' . @gallery.name }}" class="btn btn-warning" text="{{ 'Scan ' . @gallery.name}}"/></span>
    <span class="pull-right"><link-to href="{{ @post  . 'sync/' . @gallery.name }}" class="btn btn-warning" text="{{ 'Sync ' . @gallery.name}}"/></span>

    <form id='upfile' action="{{@post  . 'upload'}}" method="post" enctype="multipart/form-data">
        <input type="hidden" id="galleryid" name="galleryid" value="{{ @gallery.id }}" />
        <div style='outline: 1px dotted orange;width:50em;'>
            <table class='table table-condensed table-borderless' >
                <tr>
                    <td><p><span style="font-size:1.0em;"><b>Upload image or file</b></span></p></td>
                    <td><input id="file" type="file" name="files[]" multiple="multple" ></td>
                    <td><input type="submit" value="upload" class='btn-danger' ></td>
                    <td><checkbox name="thumbs" text="Upload to Thumbs"></checkbox></td>
                </tr>
            </table>
        </div>
        <div class="progress">
            <div class="progress-bar" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100"></div>
        </div>
        <div id="targetLayer" style="display:none;"></div>
    </form>
    <div id="image_status"><include href="gallery_adm/file.phtml" /></div>
</div>

