{~
    @view = \Base::instance()->get('view');
    @gallery = @view->gallery;
~}
<style>
    textarea.form-control {
        margin:20px;
    }
    
    input.form-control {
        max-width:300px;
        margin:20px;
    }
    label.control-label {
        min-width:110px;
        text-align:right;
        margin-right:10px;
    }
</style>
<div class="container-fluid">
    <div class="outerwrap pad10">
    <h1>Create Image Gallery</h1>
    <form method="post" action="{{ @view->url . 'post' }}">
        <check if="{{  @gallery.id  }}">
            <true>
            <hidden name="id" value="{{  @gallery.id  }}"></hidden>
            <div class="row">
            <label for="name" class="control-label">Name</label>
            <text-field name="name" value="{{ @gallery.name }}" readonly></text-field>
            </div>
            </true>
            <false>
                <div class="row">
                    <label for="name" class="control-label">Name</label>
                <text-field name="name" value="{{ @gallery.name }}"></text-field>
                </div>
            </false>
        </check>
        <div class="row">
            <label for="description" class="control-label">Description</label>
            <multiline cols="50" name="description" value="{{ @gallery.description }}"></multiline>
        </div>
        <div class="row">
            <submit-btn value="Create new gallery" class="form-control"></submit-btn>
        </div>
    </form>
    </div>
</div>