<?php
//$gem = $this->htmlgem;
$blog = $m->blog;
$metadata = $m->metadata;

$theme = '/' . $m->theme;
$revision = $m->revision;
$assets->add(['bootstrap','styles']);
$page_url = "https://" . $app->domain . "/article/" . $blog->title_clean;
$coded_url = urlencode($page_url);
$hasComments = $blog->comments && (($app->want_facebook) || ($app->use_zentix));
?>
<?php if ($app->want_facebook): ?>
<div class="fb-share-button" 
     data-href="<?=$page_url?>" 
     data-layout="button" data-size="large">
    <a target="_blank" 
       href="https://www.facebook.com/sharer/sharer.php?u=<?=$coded_url?>&amp;src=sdkpreparse" 
       class="fb-xfbml-parse-ignore">Share</a>
</div>
<?php endif ?>
<style>
    div#title-box {
        background-color:white;
        font-family: Times;
        font-weight: bold;
        font-size:1.8em;
        margin:10px;
    }
    div#article-box {
        border-width:0;
    }
    div#metadata {
        background-image: url( "<?= $theme ?>/tile-fog.png" );
    }
</style>
<div class='container outerwrap'>

    <div id="article-box">
    <div class='<?=$blog->style ?>' >
        <div id="title-box" class="row">
             <div class="col">
            <span><?= $blog->title ?></span>
             </div>
        </div>
        <div class="row">
            <div class="col">
                <?= $revision->content ?>
            </div>
        </div>
    </div>
    </div>
    <?php if ( !empty($metadata) ): ?>
        <div class='container' id='metadata' style='font-size:0.6em;'>
            <div class='table'>
                <?php foreach($metadata as $mtag): ?>
                   <?php if ($mtag['display'] == 1 && strlen($mtag['content'] ) >0): ?>
                        <div class="row">
                            <div class='col-1'><?= $mtag['meta_name'] ?>:</div>
                            <div class='col-8'><?= $mtag['content'] ?></div>
                        </div>
                <?php endif; ?>
                <?php endforeach; ?>
            </div>
        </div>
 <?php endif; ?>
    <hr />
</div>


