{~
   @url = @view->url;
   @email = @view->email;
~}

<style>
    .col-form-label {
        min-width:150px;
        text-align: right;
    }
    
    input {
        margin-left : 15px;
    }
</style>
<form method="post" autocomplete="off" action="{{ @url . 'changePwdPost' }}">

    <div class="container outerwrap pad10">
        <h3>{{ @view->header }}</h3>
        <hidden name="email" value="{{ @email }}"></hidden>
        <div class="row pad10">
            <pwd-field label="New password" name="new_pwd" value="" size="24"></pwd-field>
        </div>
            <div class="row pad10">
            <pwd-field label="Confirm password" name="confirm_pwd" value="" size="24"></pwd-field>
            
        </div>
        <div class="row pad10">
        <submit-btn name="submit" value="Change"></submit-btn>
        </div>
    </div>

</form>