{~
    @view = \Base::instance()->get('view');
    @google = @view->google;
    
~}
<div  class="container  outerwrap pad10" style="max-width:50em" >
    <div class="row pad10">
        <h4>Send password reset token</h4>
    </div>
    <form id="getPWReset" method='post' action='forgotPost' >
        
        <email label="Email" name='email' value="{{ @view->email }}" size="60" required></email>
        
    <check if="{{ @google.enabled }}">
    <true>
    <script>
        function onSubmit(token) {
            document.getElementById("getPWReset").submit();
        }
    </script>
    <script src="https://www.google.com/recaptcha/api.js" async defer></script>
    <div class="pad10">
    <button class ="g-recaptcha" data-sitekey="{{ @google.site }}" data-callback="onSubmit">
        Email Reset Token
    </button> 
    </div>
    </true>
    <false>
    <div class="form-group">
         <submit-btn name='login' value="Email Reset Token" class='btn btn-primary btn-large' />
    </div>    
    </false>
    </check>   
        
    </form>


	

</div>