<?php
if ($view->layout) {
    $this->layout($view->layout, $this->data);
}
    $cat = $m->cat;
    $url = $m->url;
    $fm = $this->form();
?>

<style>
     label.col-form-label {
        min-width: 100px;
        text-align: right;
        margin-right:20px;
    }
</style>
<div class='header row'>
    <div class="outerwrap pad10">
        <?= $fm->linkTo(['href' =>$url , 'text' =>"Category List", 'class' => "btn btn-outline-warning"]) ?><span class="btn"><?= $m->title ?></span>
    </div>
</div>
<div class="container pad10 outerwrap">
    
<form action="<?= $url . 'post' ?>" method="post">
    <?php if ( isset($cat['id']) && $cat['id'] > 0 ): ?>
    <div class="form-group row">
        <label class="col-form-label" >Id</label>
        <?= $fm->plainText(['name' => 'id', 'value' => $cat['id'], "readonly"]) ?>
    </div>
    <?php endif; ?>
     <div class="form-group row">
        <label class="col-form-label" >Name</label>
        <?= $fm->plainText([ 'name' => 'name', 'value' => $cat['name'] ]) ?>
   </div>
    <div class="form-group row">
        <label class="col-form-label" >Name Clean</label>
        <?= $fm->plainText([ 'name' => 'name_clean', 'value' => $cat['name_clean'] ]) ?>
  </div>
   <div class="form-check row">
        <label class="col-form-label" >Enabled</label>
         <?= $fm->checkbox([ 'name' => 'enabled', 'value' => $cat['enabled'] ]) ?>
      </div>
    <p>
        <input type="submit" value="Save" />
    </p>
</form>
</div>