<wc:init></wc:init>
{~
@view = \Base::instance()->get('view');
@rego = @view->rego;
@evt = @view->evt;
~}

<style>
    label {
        min-width:150px;
        text-align:right;
        padding-right:10px;
    }
    
</style>
<div class="container-fluid body-wrap">
    <hr>
    <form id="edtevt" method="post" action="/admin/eventpost">
        <hidden name="id" value="{{ @evt.id }}"></hidden>
        <div class="row">
            <div class="col-4">
                <datetime label="From" name="fromTime" value="{{ @evt.fromTime }}" size="20"></datetime>
            </div>
             <div class="col-4">
                <datetime  label="To" name="toTime" value="{{ @evt.toTime }}"  size="20"></datetime>
            </div>
        </div>
        <div class="row">
             <div class="col-4">
                <text-field  label="Slug" name="slug" value="{{ @evt.slug }}"></text-field>
            </div>
            <div class="col-4">
                <checkbox  text="Enabled" name="enabled" value="1" checked="{{ @evt.enabled }}"></checkbox>
            </div>
        </div>
        <div class="row">
            <div class="col-3"></div>
            <div class="col-4">
            <submit-btn name="submit" value="Update"></submit-btn>
            </div>
        </div>
    </form>
    <hr>
        <check if="{{ !empty(@rego) }}">
              <div class="row body-wrap pad10">
                  <div class="col-2">
                  <h1>Registrations</h1>
                  </div>
                <div class="col-10">
                <repeat group="{{ @rego }}" value="{{ @rg }}">
                    <div class="row">
                        <div class="col-3">{{ @rg.fname }}&nbsp;{{ @rg.lname }}</div>
                        <div class="col-3">{{ @rg.email }}</div>
                        <div class="col-2">{{ @rg.phone }}</div>
                        <div class="col-1">{{ @rg.people }}</div>
                        <div class="col-2">{{ @rg.created_at }}</div>
                    </div>
                    <hr>
                </repeat>
                </div>
              </div>
        </check>
</div>
