{~
    @view = \Base::instance()->get('view');
    @domain = @view->publicUrl;
    @link = @domain . @view->confirmUrl;
~}
<h3 style="font-size: 14px;font-family:Verdana,Helvetica,Arial,sans-serif;">Join SBO Form</h3>
            <p style="color:#000;font-size: 16px;line-height:24px;font-family:Verdana,Helvetica,Arial,sans-serif;font-weight:normal;">
This email has been sent by the sign-up form on {{ @domain }}<br>
as user name: {{ @view->userName }}<br>
Use the following link confirms your email : <br>
<a href="{{ @link }}">{{ @link }}</a>
            </p>


