<?php 
Use WC\Assets; 
use WC\UserSession ?>
<li class="nav-item dropdown">
<a class="nav-link dropdown-toggle" href="#" id="dd_m36" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
Content
</a>
<div class="dropdown-menu" aria-labelledby="dd_m36">
<a href="/links/?mit=37" class="dropdown-item">All</a>
<a href="/links/?k=Remote&mit=38" class="dropdown-item">Web</a>
<a href="/events/?mit=39" class="dropdown-item">Events</a>
<a href="/links/?k=Blog&mit=40" class="dropdown-item">Here</a>

</div>
</li>

<li class="nav-item dropdown">
<a class="nav-link dropdown-toggle" href="#" id="dd_m41" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
About
</a>
<div class="dropdown-menu" aria-labelledby="dd_m41">
<a href="/cat/article/who-is-parracan?mit=42" class="dropdown-item">Who is ParraCAN?</a>
<a href="/cat/article/overwhelming-evidence-we-caused-global-warming?mit=43" class="dropdown-item">Human industrial world is cause of Global Warming</a>
<a href="/cat/article/why-act-good-news?mit=44" class="dropdown-item">Why act -- good news</a>
<a href="/cat/article/why-act-bad-news?mit=45" class="dropdown-item">Why act - bad news</a>
<a href="/cat/article/our-vision-and-associations?mit=46" class="dropdown-item">Our vision and associations</a>
<a href="/cat/article/history-of-parracan?mit=47" class="dropdown-item">History of ParraCAN</a>
<a href="/cat/article/become-a-member?mit=48" class="dropdown-item">Help us</a>

</div>
</li>

<li class="nav-item dropdown">
<a class="nav-link dropdown-toggle" href="#" id="dd_m49" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
News
</a>
<div class="dropdown-menu" aria-labelledby="dd_m49">
<a href="/cat/article/save-the-biosphere-turn-off-fossil-fuel-machinery?mit=50" class="dropdown-item">Save the biosphere: Turn off fossil fuel machinery</a>
<a href="/cat/article/hundreds-of-thousands-in-australia-demand-government-climate-action-now?mit=51" class="dropdown-item">Hundreds of Thousands in Australia demand government climate action now</a>
<a href="/cat/article/australian-election-a-two-nobbled-horse-race?mit=52" class="dropdown-item">Australian Election a two nobbled horse race</a>
<a href="/cat/article/stop-adani-convoy-draws-organic-bullshit-from-the-australian?mit=53" class="dropdown-item">Stop Adani Convoy success draws organic bullshit from </a>
<a href="/cat/article/a-necessary-collapse?mit=54" class="dropdown-item">A Necessary Collapse underway  by 2025</a>
<a href="/cat/article/breathe-in-the-fresh-burned-coal-particulates-and-oxides?mit=55" class="dropdown-item">Breathe fresh burned coal particulates and oxides every day in the Sydney region</a>
<a href="/cat/article/classic-developer-donations-for-government-favours?mit=56" class="dropdown-item">Classic Australian Developer Donations for Government favours</a>
<a href="/cat/article/droughts-and-deluge-coal-diminishes-national-security?mit=57" class="dropdown-item">More Droughts and Deluge, Adani Coal diminishes Australian National Security</a>

</div>
</li>

<li class="nav-item dropdown">
<a class="nav-link dropdown-toggle" href="#" id="dd_m58" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
Contact
</a>
<div class="dropdown-menu" aria-labelledby="dd_m58">
<a href="/contact-us/?mit=59" class="dropdown-item">Contact Us</a>
<a href="/id/signup/?mit=60" class="dropdown-item">Newsletter Subscribe</a>

</div>
</li>

