<?php
$cfg = $app->module_cfg;
if (is_array($cfg)) {
    $menus = $cfg['menus'] ?? null;
}
else {
    $menus = null;
}
?>
<!-- <?= 'File: ' . __FILE__ ?> -->

</style>
<div class="d-flex flex-row" style="width:100%;" >
    <div class="nav-title-wrap">
        <a class="site-logo" href="/"><img src="/<?=$m->theme?>/site-logo.png"></a>
    </div>
    <div style="opacity:0.0; min-width:15px"></div>
    <div class="title-wrap">
        <?= $m->title ?>
    </div>
    <div style="opacity:0.0; min-width:15px"></div>
<div class="navbar-wrap d-flex flex-row-reverse">
<nav class="navbar navbar-expand-lg navbar-light ">

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <?php if (is_array($menus)): ?>
    <div class="collapse navbar-collapse" id="navbarNavDropdown"> 
        <?php  foreach($menus as $msrc): ?>
    <ul class="navbar-nav mr-auto">
        <?=  $this->partial($msrc) ?>
    </ul>    
    <?php endforeach; ?>
            </div>
    <?php endif; ?>
</nav>
</div>
</div>
<div class="hline"></div>