<?php
$cfg = $app->module_cfg;
if (is_array($cfg)) {
    $menus = $cfg['menus'] ?? null;
}
else {
    $menus = null;
}
?>
<!-- <?= 'File: ' . __FILE__ ?> -->
<style>
    nav  {
        background-image: url("/<?=$m->theme?>/tile-fog.png");
        color:lightcoral;
    }
    ul.navbar-nav a {
        font-size:1.2em;
    }
    .nav-link {
        font-weight:bold;
    }
    .navbar-brand {
        padding-top:0;
        padding-bottom:0;
    }
    .navbar {
        padding:0 0;
        margin: 0 0;
    }
    .site-logo img {
       max-height:100%;
        padding:5px;
    }
    
    .view-title {
        background-color: white;
        color:darkslateblue;
        font-weight:bold;
        font-size:1.5rem;
        padding-right:10px;
       height:70px;
    }
</style>
<nav class="navbar navbar-expand-lg navbar-light ">
    <div class="view-title">
        <a class="site-logo" href="/"><img src="/<?=$m->theme?>/site-logo.png"></a>
    </div>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <?php if (is_array($menus)): ?>
    <div class="collapse navbar-collapse" id="navbarNavDropdown"> 
        <?php  foreach($menus as $msrc): ?>
    <ul class="navbar-nav mr-auto">
        <?=  $this->partial($msrc) ?>
    </ul>    
    <?php endforeach; ?>
            </div>
    <?php endif; ?>
</nav>