<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" >
    
    <?php
    if (isset($m->metaloaf)): 
        foreach($m->metaloaf as $meta):
            echo($meta) . PHP_EOL;
        endforeach;
    endif; ?>
    <?php if (isset($m->title)): ?>
    <title><?= $m->title ?></title>
    <?php endif; ?>
    <?= $assets->Link() ?>
    <?= $assets->CssHeader(); ?>
    
    <style>
    body {
                background-image: url("/<?= $app->theme ?>/body.png");
        }
    nav {
        //background-image: url("/<?=$m->theme?>/tile-fog.png");
        background-color:whitesmoke;
        color:black;
    }
    </style>
</head>