<style>
    nav  {
        background-image: url("/image/gallery/site/tile-fog2.png");
        color:lightcoral;
    }
    ul.navbar-nav a {
        font-size:1.0em;
    }
    .nav-link {
        font-weight:bold;
    }
    .navbar-brand {
        padding-top:0;
        padding-bottom:0;
    }
    .navbar {
        padding:0 0;
        margin: 0 0;
    }
    
</style>

<nav class="navbar navbar-expand-lg navbar-light ">
    <div class="view-title">
        <a class="site-logo" href="/"><img src="{{ @theme }}/red-logo.png"></a><span>&nsp;{{ @view->title }}</span>
    </div>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
            <include href="generated/dropdowns.phtml"></include>
        </ul>
    </div>
</nav>