<?php
if ($view->layout) {
    $this->layout($view->layout, $this->data);
}
$fm = $this->form();
?>
<style>
    .col-form-label {
        min-width:150px;
        text-align: right;
    }
    
    input {
        margin-left : 15px;
    }
</style>
<form method="post" autocomplete="off" action="<?= $m->url . 'changePwdPost' ?>">

    <div class="container outerwrap pad10">
        <h3><?= $m->header ?></h3>
        <hidden name="email" value="<?= $m->email ?>"></hidden>
        <div class="row pad10">
            <?= $fm->password(['label' => 'New password', 'name' => 'new_pwd',
                'value' => '', size =>24 ]) ?>
        </div>
            <div class="row pad10">
                <?= $fm->password(['label' => 'Confirm password', 'name' => 'confirm_pwd',
                'value' => '', size =>24 ]) ?>
            
        </div>
        <div class="row pad10">
            <?= $fm->submit(['name' => 'submit', 'value' => 'Change' ]) ?>
        </div>
    </div>

</form>