<?php 
    $this->layout('layout_plates',$this->data); 
?>
<div style="font-size:24px;">
<div class="container outerwrap pad10">
    <div class="row">
        <div class="col-3">
            <a href="/admin/blog">Articles</a>
        </div>
        <div class="col-3">
            <a href="/admin/blog/export">Backup/Export</a>
        </div>
        <div class="col-3">
            <a href="/admin/blog/import">Import</a>
        </div>
        <div class="col-3">
           <a href="/admin/info">PHP Info</a>
        </div>
    </div>
    <div class="row">
        <div class="col-3">
            <a href="/admin/link">Links</a><br>
        </div>
        <div class="col-3">
            <a href="/admin/linkery">Linkery</a>
        </div>
        <div class="col-3">
            <a href="/admin/user">User Index</a>
        </div>
        <div class="col-3">
            <a href="/admin/shop">Shop</a>
        </div>
    </div>
    <div class="row">
        <div class="col-3">
           <a href="/admin/gallery">Gallery</a>
        </div>
        <div class="col-3">
            <a href="/admin/menu">Menus</a>
        </div>
        <div class="col-3">
            <a href="/admin/member/list">Members</a>
        </div>
        <div class="col-3">
            <a href="/chimp/lists">Mail Chimp Lists</a>
        </div>
    </div>
    <div class="row">
        <div class="col-3">
           <button id="asset_cache">Clear Asset Cache</button>
        </div>
    </div>
</div>

    <script>
    function setup_dash() {
        $("#asset_cache").click(function() {
            $.get("/dash/assetcache", function(data, status) {
                alert("Data: " + data + "\nStatus: " + status);
            })
        });
    }
    
    window.onload = setup_dash;
    
    </script>