{~
    @view = \Base::instance()->get('view');
    @info = @view->info;
~}
<div style="font-size:24px;">
<div class="container outerwrap pad10">
    <div class="row">
        <div class="col-3">
            <a href="/admin/blog">Articles</a>
        </div>
        <div class="col-3">
            <a href="/admin/blog/export">Backup/Export</a>
        </div>
        <div class="col-3">
            <a href="/admin/blog/import">Import</a>
        </div>
        <div class="col-3">
           <a href="/admin/info">PHP Info</a>
        </div>
    </div>
    <div class="row">
        <div class="col-3">
            <a href="/admin/link">Links</a><br>
        </div>
        <div class="col-3">
            <a href="/admin/linkery">Linkery</a>
        </div>
        <div class="col-3">
            <a href="/admin/user">User Index</a>
        </div>
        <div class="col-3">
            <a href="/admin/shop">Shop</a>
        </div>
    </div>
    <div class="row">
        <div class="col-3">
           <a href="/admin/gallery">Gallery</a>
        </div>
        <div class="col-3">
            <a href="/admin/menu">Menus</a>
        </div>
        <div class="col-3">
            <a href="/admin/member/list">Members</a>
        </div>
        <div class="col-3">
            <a href="/chimp/lists">Mail Chimp Lists</a>
        </div>
    </div>
    <div class='row'>
  
</div>
</div>
