<?php

    if ($view->layout) {
        $this->layout($view->layout, $this->data);
    }
    $google = $m->google;
    $fm = $this->form();
?>
<div  class="container  outerwrap pad10" style="max-width:50em" >
    <div class="row pad10">
        <h4>Send password reset token</h4>
    </div>
    <form id="getPWReset" method='post' action='forgotPost' >
        <?= $fm->email(['label' => 'Email', 'name' => 'email', 
            'class' => 'form-control', 'value' => $m->email, 'size' => 60, "required"]) ?>
    <?php if($google['enabled']): ?>
    <script>
        function onSubmit(token) {
            document.getElementById("getPWReset").submit();
        }
    </script>
    <script src="https://www.google.com/recaptcha/api.js" async defer></script>
    <div class="pad10">
    <button class ="g-recaptcha" data-sitekey="<?= $google['site'] ?>" 
                data-callback="onSubmit">
        Email Reset Token
    </button> 
    </div>
    <?php else: ?>
    <div class="row">
        <div class="col">
        <?= $fm->submit(['name' => 'login', 
            'value' => 'Email Reset Token', 'class' => 'btn btn-outline-primary btn-large']) ?>
        </div>  
            </div>    
    <?php endif ?> 
    </form>
</div>