<!DOCTYPE html>
<html lang="en">
    <head>
    <wc:init></wc:init>
        <meta charset="UTF-8" />
        <title>{{ @view->title }}</title>
    <f3:link></f3:link>
    <f3:css-header></f3:css-header>    
</head>
<body>
    <style>
        
        .banner-wrap {
            height:200px;
            padding-left:5px;
            background-color:black;
        }
        
        .banner-wrap img {
            height:100%;
        }
    </style>

    <div class="banner-wrap">
        <a href="/"><img  src="/sbo/banner.jpg"></a>
    </div>
<F3:repeat group="{{ @view->topPanels }}" value="{{ @panel }}">
    <div class="panel-wrap">{{ @panel.summary | raw }}</div>
</F3:repeat>
<div class="clear"></div>

<check if="{{ @view->nav }}">
    <true>
    <include href="{{ @view->nav }}" />
    </true>
</check>
<check if="{{ !empty(@view->flash) }}"><true>
    <F3:repeat group="{{ @view->flash }}" value="{{ @msg }}">
        <div class="alert alert-{{ @msg.status }} alert-dismissable">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            {{ @msg.text | esc }}
        </div>
    </F3:repeat>
    </true></check>
<check if="{{ @view->content }}">
    <true>
    <div id="view"><include href="{{@view->content}}"></include></div>
    </true>
</check>


<footer class='footer foot-wrap'>
    <div class="row">
        <div class="col-2 text-muted">
            {~
            echo( "Session as " . UserSession::sessionName() );
            ~}
        </div>
        <div class="col-4 text-muted">&copy;  | 
            {~
            @out = " Response time " . sprintf('%.2f ms', (microtime(TRUE) - @_SERVER.REQUEST_TIME_FLOAT) * 1000);
            @out .= " | Memory " . sprintf('%.2f MiB', memory_get_peak_usage() / 1024 / 1024);
            echo(@out);
            ~}
        </div>
    </div>
</footer>
<f3:js-footer></f3:js-footer>
</body>
</html>
