<?php

    if ($view->layout) {
        $this->layout($view->layout, $this->data);
    }
    $google = $m->google;
    $fm = $this->form();
?>

<div class='container outerwrap pad10'>
 
<form id="user-login" method='post' action='login'>
    <fieldset>
        <?php if(isset($m->message)): ?>
            <div class="alert alert-primary" role ="alert">
                <p class="message"><?= $m->message ?></p>
            </div>
        <?php endif ?>
        <div class="form-group">
            <label for="email">Username/Email</label>
            <div class="controls">
                <?= $fm->email(['name' => 'email', 'class' => 'form-control']) ?>
            </div>
        </div>
        <div class="form-group">
            <label for="password">Password</label>
            <div class="controls">
                <?= $fm->password(['name' => 'password', 'class' => 'form-control']) ?>
            </div>
        </div>
        <?php 
          if($google['enabled']): 
           echo ($fm->recaptcha(['id' => 'user-login', 
               'site' => $google['site'],
               'text' => 'Login']) );
           else: ?>
    <div class="form-group">
        <?= $fm->submit(['name' => 'login', 'value' => 'Login',
            'class' => 'btn btn-outline-primary' ]) ?>
    </div>    
        <?php endif ?>

</fieldset>       
     <?= $fm->xcheck(['value' => $m->xcheck ]) ?>
</form>
    <div class="row">
        <div class="col-3"></div>
        <div class="col-4 pad10"><?= $fm->linkTo(['href' => '/login/forgot', 
            'text' => 'Send password reset token', 
            'class' => 'btn btn-outline-info']) ?></div>
    </div>
</div>