
<?php
$hasEvents = !empty($m->list);
$hasOld = !empty($m->old);
if ($view->layout) {
    $this->layout($view->layout, $this->data);
}
?>

<style>
    div.sidebox {
        background-color:whitesmoke;
        border-radius:4px;
    }
    div.title-area span.link-sitename {
        color:darkred;
        font-size:1.2em;
    }
    
    div.colborder {
        border-left-style: dotted;
        border-left-width:1;
        border-left-color: lightgray;
    }
</style>
<div class="container-fluid">
        <?php if ($hasEvents): ?>
              <div class="row">
                  <h1>Past Events</h1>
              </div>
                <?php foreach($m->list as $box): ?>
                    <div class="row pad10" style="background-color:whitesmoke">
                    <div class="<?=$box['style'] ?>">
                        <?=$box['article']  ?>
                    </div>
                    <hr>
                    </div>
                <?php endforeach ?>     
        <?php endif  ?>
    <?php if ($hasOld): ?>
     <?php foreach($m->old as $box): ?>
     <repeat group="<?= $view->old ?>" value="<?= $box ?>">
                    <div class="row">
                    <div class="<?=$box.style ?>">
                         <?=$box['article']  ?>
                    </div>
                    </div>
                 <?php endforeach ?>     
        <?php endif  ?>
</div>
