<wc:init></wc:init>
{~
@view = Base::instance()->get('view');
@blog = @view->blog;
@metatags = @view->metatags;
@url = @view->url;
@stylelist = &@view->stylelist;
@module = '/admin/';
~}
<style>
    .form-check label {
        padding-left:10px;
        padding-right:40px;
        font-weight:bold;
    }
    
    .form-check-input {
        margin-left:0px;
    }
    .col-form-label {
        min-width:100px;
        padding-right:10px;
        padding-left:10px;
        font-weight:bold;
        text-align:right;
    }

    .date label {
        min-width:100px;
        font-weight:bold;
        text-align:right;
        padding-right:10px;
        padding-left:10px;
    }

    .date input {
        max-width:300px;
    }
</style>
<div class='row center outerwrap'>
    <div class="col-2">
        <span><link-to text="Articles" href="{{ @module . 'blog' }}"></link-to></span>
    </div>
    <div class="col-2">
        <link-to href='{{ @module ."links/blog/" . @blog.id }}' text="Generate Link"  target='_blank'  class='btn btn-default' />
    </div>
    <div class="col-2">
        <link-to href='{{ @module ."gallery"  }}' text="Galleries"  target='_blank'  class='btn btn-default' />
    </div>
</div>

<form action="{{  @url . 'post'  }}"
      id="postForm"
      method='post'
      onsubmit='smotePost()'>
    <hidden name='id' value='{{ @blog.id }}' ></hidden>

    <div class="container">
        <div class='row'>
            <div class='col-7 outerwrap'>
                <div class='form-group'>
                    <label class='col-form-label' for="title">Title</label>
                    <text-field name='title' size='40' value='{{ @blog.title }}' /><br>
                    <label class=' col-form-label' for="issue">Issue</label>
                    <text-field name='issue' size='4' type='number' value='{{ @blog.issue }}'/>
                </div>
                <div class='form-group'>
                    <label class='col-form-label' for="lock_url">Unlock URL</label>
                    <checkbox name='lock_url' size='5'  class="form-check-input"/><br>

                    <label class='col-form-label' for="title_clean">Unique URL</label>
                    <text-field name='title_clean' size='40' value='{{ @blog.title_clean }}'/>
                </div>



            </div>
            <div class='col-5 outerwrap'>
                <div class='form-group'>
                    {{ 'Updated ' .  @blog.date_updated . ' &nbsp;'  }}
                    <submit-btn name='save' value='Save' class='btn btn-primary' ></submit-btn>
                </div>
                <div class='form-group'>
                    <label for="class_select">Select style wrapper</label>
                    <select-menu name='style' list='{{@stylelist}}' empty='false' onChange='wrapStyle()'  value="{{ @blog.style }}"></select-menu>
                </div>

                <div class='form-group'>
                    <label for="summernote">Article Text</label>
                    <button id="airbtn" type="button" class='col-form-button' title="This also does a save-submit"
                            onclick="codeSwitch()">Switch to 'Air-Mode'</button>
                </div>
            </div>
        </div>
    </div>

    <div class="clear"></div>
    <div class="row body-wrap pad10">
        <button onclick="smoteVerify(); return false;">Verify HTML</button>
        <textarea id="analysis" cols="80"></textarea>
    </div>
    <div id='wrap_style' class="{{ @blog.style }}">
        <textarea id='article' name='article' style='display:none;' cols='100' rows='25'>{{ @blog.article }}</textarea>
    </div>
    <div class='container outerwrap'>
        <span class="heading">Author / Flags</span>
        <div class='body-wrap'>
             <div class="row">
                 <div class="col-3">
                    <label for="author_id">Author</label><text-field name='author_id' type='number' readonly='readonly' />
                 </div>
                 <div class="col-4"> <!-- value="{{ @blog.date_published }}"  -->
                     <datetime label="Date" name="date_published" class="form-control" value="{{ @blog.date_published }}" ></datetime>
                 </div>
             </div>
            
            <div class="row">
                <div class="col-2">
                     <checkbox  name='enabled' value='1'  checked="{{ @blog.enabled }}"></checkbox><label for="enabled">Enabled</label>
                </div>

            <div class="col-2">
                <checkbox name='featured' value='1' checked="{{ @blog.featured }}"/></checkbox><label for="featured">Featured</label>
            </div>
            <div class="col-2">
                <checkbox name='comments' value='1' checked="{{ @blog.comments }}"/></checkbox><label for="comments">Comments</label>
            </div>
            </div>
        </div>
    </div>
    <div class='container outerwrap'>
        <span class="heading">Meta-Tags for Search Engines</span>
        <table class='table table-striped'>
            <tbody>
            <repeat group='{{ @metatags }}' value='{{ @meta }}'>
                {~
                @label = @meta.meta_name;
                @name = 'metatag-' .  @meta.id;
                @value = @meta.content;
                ~}
                <tr>
                    <td class='rightCell'><label for='{{ @name }}'> {{ @label }}</label></td>
                    <td class='leftCell'>
                <check if='{{ @meta.data_limit <= 80 }}' ><true>
                    <text-field name='{{ @name }}' value='{{ @value }}' size='60' cols='60' maxlength='{{ @meta.data_limit }}' />
                    </true><false>
                    <textarea name='{{ @name }}' id='{{ @name }}'  size='60' cols='60' maxlength='{{ @meta.data_limit }}' >{{ @value }}</textarea>
                    </false>
                </check>
                </td>
                </tr>
            </repeat>
            </tbody>
        </table>
    </div>
</form>
<div class='container outerwrap pad10' >
    <div class="body-wrap">
        <div id="category_status" ><include href='blog/category.phtml' /></div>
    </div>
</div>
<div class='container outerwrap pad10'>
    <div id="event_dates" ><include href='blog/event_dates.phtml' /></div>
    <form id='eventForm' action="{{ @url  . 'addevent'}}" method="post">
        <input type="hidden" name="event_blogid" value="{{ @blog.id }}" />
        <span class="heading">Add Event</span>
        <div class="form-group">
            <datetime label="From " name="fromDate" class="form-control"></datetime>
        </div>
        <div class="form-group">
            <datetime label="To " name="toDate" class="form-control"></datetime>
        </div>
        <div class="form-group">
            <text-field label="Slug" name="slug" class="form-control" size="30"></text-field>
        </div>
        <input type="submit" class='btn-danger' value='Add Event'></input>
    </form>
</div>

