<?php 
if ($view->layout):
    $this->layout($view->layout, $this->data);
endif;
$url = $m->url;
$fm = $this->form();
?>

<div class='container'>
    <div align="center">
        <h2>Create Content</h2>
    </div>
    <form method='post' action="<?= $url . 'postnew' ?>">
        <table>
            <tr>
                <td align="right">
                    <label for="title">Title</label>
                </td>
                <td align="left">
                    <?= $fm->plainText(['name' => 'title', 'size' => 30]) ?>
            </td>
            </tr>
            <tr>
                <td align="right"> <?= $fm->submit(['value' => 'Save', 'class' => "pure-button pure-button-primary"]) ?></td>
            </tr>

        </table>

    </form>
</div>


