    {~ 
            @view = Base::Instance()->get('view');
            @links = @view->links;
            @linkery = @view->linkery;
            @post = @view->post;
    ~}
    <style>
    label.control-label {
        min-width:110px;
        text-align:right;
        margin-right:10px;
        font-weight: bold;
    }
</style>
    <include href="linkery_adm/title.phtml" ></include>

 <div class="container outerwrap">
         <hr>
 <form id="edit_linkery" method="post" action="{{ @post . "post" }}" >
                     <hidden name="id" value="{{  @linkery.id  }}"></hidden>
            <div class="row">
            <label for="name" class="control-label">Name</label>
            <text-field name="name" value="{{ @linkery.name }}"></text-field>
            </div>
           <div class="row">
            <label for="description" class="control-label">Description</label>
            <multiline name="description" value="{{ @linkery.description }}">{{ @linkery.description }}</multiline>
            </div>
                     <hr>
         <div class="row">
            <submit-btn value="Update details"></submit-btn>
        </div>
 </form>
 </div>
             <hr>
<div class="container-fluid">
    <div id="image_status"><include href="linkery_adm/file.phtml" /></div>
</div>
