<?php
Use WC\HtmlGem;
$donations = $m->donations;
$btnclass = 'btn btn-outline-info';
$gem = $this->htmlgem;
$fmt = HtmlGem::moneyFormat('en-AU');
?>
<?php if (!empty($donations)): ?>
<div class='container' >
    <div id='dnwrap' class='row'>
        <div class='col-2 text-center'>
            Date
        </div>
        <div class='col-2 text-center'>
            Purpose
        </div>
        <div class='col-2 text-center'>
            Amount
        </div>
        <div class='col-2 text-center'>
            Detail
        </div>
    </div>
    
    <?php foreach($donations as $dn): ?>
        <div class="row" id="dnid<?= $dn['id'] ?>">
            <div class="col-2 text-center">
                <span><?= $dn['member_date'] ?></span>
            </div>

            <div class="col-2 text-center">
                <span><?= $gem->linkTo(['href'=>'/admin/donation/edit/' . $dn['id'], 'text'=> $dn['purpose']]) ?></span>
            </div>
            <div class="col-2 text-right">
                <span class="align-right"><?= $fmt->format($dn['amount']) ?></span>
            </div>
            <div class="col-2">
                <span><?= $dn['detail'] ?></span>
            </div>
        </div>
    <?php endforeach ?>
</div>
<?php endif ?>