<?php
Use WC\HtmlGem;
$donations = $m->donations;
$btnclass = 'btn btn-outline-info';
$fmt = Html::moneyFormat('en-AU');
?>
<div class='container' >
    <div id='dnwrap' class='row'>
        <div class='col-2 text-center'>
            Date
        </div>
        <div class='col-2 text-center'>
            Purpose
        </div>
        <div class='col-2 text-right'>
            Amount
        </div>
    </div>
    
    <?php foreach($donations as $dn): ?>
        <div class="row" id="dnid<?= $dn['id'] ?>">
            <div class="col-2 text-center">
                <span><?= $dn['member_date'] ?></span>
            </div>

            <div class="col-2 text-center">
                <span><?= $dn['purpose'] ?></span>
            </div>
            <div class="col-2 text-right">
                <span class="align-right"><?= $fmt->format($dn['amount']) ?></span>
            </div>
        </div>
    <?php endforeach ?>
</div>