<?php
    $blogs = $m->blogs;
    $cat = $view->catclean;
?>
<div class='container-fluid'>
    <?php if (!empty($blogs)): ?>
    <div class="row">
    
    <div id="list" class="col catlist">
          <span class="cattitle"><?= $m->cattitle ?></span>
          <?php foreach($blogs as $blog): 
             $id = $blog['id'];
             ?>
               <div class="row">
            <div class="catlink">
                <a class="btn" id="f<?= $id ?>"  href="<?= $id ?>" onclick="fetchid(this);return false;"><?= $blog['title'] ?></a>
            </div>
                </div>
          <?php endforeach ?>
    </div>
    <div class="col">
    <div id="article"></div>
    </div>
    </div>
    <div class="hidden">
        <a id="first_link"  href="<?= $m->firstId?>" onclick="fetchid(this);return false;">#First#</a>
    </div>
    <?php endif  ?>
</div>
