<?php
use WC\HtmlGem as Gem;
$assets->add(['bootstrap', 'grid']);
$ubase = "gallery?orderby="; 
$link =  $ubase . $m->orderby;  
$page = $m->page;
$url =  "/gallery/view/";

?>
<div class='container body-wrap'>      
   <?= Gem::linkTo(['href'=>$link, 'text'=>'First']) ?>
   <?= Gem::linkTo(['href'=>$link.'&page='.$page->before,
   'text'=>'Previous']) ?> |
    <?= Gem::linkTo(['href'=>$link.'&page='.$page->next,
   'text'=>'Next']) ?> |
   <?= Gem::linkTo(['href'=>$link.'&page='.$page->last,
   'text'=>'Last']) ?> |
   <?=$page->current . "/" . $page->last ?>
<table class='table table-striped'>
    <thead>
        <tr>
            <th>Path</th>
            <th>Description</th>
            <th>Upload</th>
        </tr>
    </thead>
    <tbody>
        <?php 
         foreach($page->items as $gallery): 
         $udate = date('d-M-Y H:i',strtotime($gallery['last_upload']));
         $description = $gallery['description'];
         $name = $gallery['name'];
         ?>
<tr>
    <td class='leftCell'><?= Gem::linkTo(['href'=>$url.$name, 'text'=>$name]) ?></td>
            <td class='leftCell'><?= $description ?></td>
             <td><?= $udate ?></td>
        </tr>
        <?php endforeach ?>
    </tbody>
</table>
</div>
