{~    
    @user = @view->user;
    @groups = @view->groups;
    @others = @view->others;
    @url = @view->url;
~}

<div class="container-fluid outerwrap">
<check if="{{ empty(@user) }}">
    <true><p>No Data Found</p></true>
    
    <false>
<form method="post" autocomplete="off" action="{{@url . 'gpost'}}">
    <input type="hidden" name='id' value='{{@user.id}}'>
<ul class="pager">
    <li class="previous pull-left">
    <link-to href="{{ @url . 'edit/' . @user.id }}" text="{{ '&larr; User ' .  @user.name}}"></link-to>
    </li>
</ul>

    <h2>Groups for {{@user.name}}</h2>
    <p>Default Group of 'Guest'</p>
    <h3>Remove Groups</h3>
    <check if="{{!empty(@groups)}}">
        <repeat group="{{@groups}}" value="{{@group}}">
            <div class="row">
                <div class="col">
                <input type='checkbox' name='{{"dgp" . @group.id}}' value="1"> {{@group.name}}
                </div>
            </div>
        </repeat>        
    </check>

    <hr>
    <check if="{{!empty(@others)}}">
        <true>
            <h3>Add Groups</h3>
    <repeat group="{{@others}}" value="{{@group}}">
        <div class="row">
            <div class="col">
            <input type='checkbox' name='{{"agp" . @group.id}}' value="1"> {{@group.name}} 
             </div>
        </div>
    </repeat>
            </true>
            <false>
                 <p>User is in all possible groups</p>
            </false>
    </check>
    <div class="row">
        <div class="col-1">
        </div>
        <div class="col">
    <button type="submit" name="add_group" value="1" class="btn btn-warning btn-lg">Change</button>
        </div>
    </div>
    <hr>
</form>
    </false>
</check>
</div>