{~
    @view = \Base::instance()->get('view');
    @rec = @view->rec;
~}
<h3 style="font-size: 14px;font-family:Verdana,Helvetica,Arial,sans-serif;">Julies Catering Contact Form</h3>
            <p style="color:#000;font-size: 16px;line-height:24px;font-family:Verdana,Helvetica,Arial,sans-serif;font-weight:normal;">
Date: {{ @rec.sendDate }}<br>
From: {{ @rec.name }}<br>
Email: {{ @rec.email }}<br>
Telephone: {{ @rec.telephone }}<br>

            </p>
            <h3>Message</h3>
<p style="font-size: 14px;line-height:24px;font-family:Verdana,Helvetica,Arial,sans-serif;">
{{ @rec.body }}
            <br/>
            </p>


