<?php
$gem = $this->htmlgem;
$gp = $m->group;
$m->title = "Preview";
$tp = $m->template;
$name = $tp->name;
$rego = $m->rego;
$actions = $m->actions;
$tpid = $tp->id;

$assets->add(["bootstrap"]);
    
$btnclass = 'btn btn-lg btn-outline-info';
$assets->add('bootstrap');

?>
<style>
    textarea.form-control {
        margin-left:10px;
        margin-right:10px;
    }

    label{
        text-align: right;
        margin-right:10px;
        min-width: 120px;
        font-weight: bold;
        vertical-align: top;
    }
</style>

<div class="container-fluid outerwrap">
    <h3>Preview</h3>
    <div style="border-style:dotted;padding:10px;">
    <?= $m->htmlMsg ?>
    </div>
</div>
<div class="container-fluid outerwrap">
            <form id="reglist" method="post" action="<?= $m->url . 'queue' ?>">
        <?= $gem->hidden( ['name'=>'id', 'value'=> $tp->id ]) ?> 
                <?= $gem->hidden( ['name'=>'rego', 'value'=> $tp->id ]) ?>
<?php if (!empty($rego)): ?>
              <div class="row body-wrap pad10">
                  <div class="col-3 text-center">
                  <span class="title">Registrations</span>
                  </div>
                <div class="col-9">
                    
                    <?= $gem->select(['list' => $actions, 'name' => 'actions', 'label' => 'Action']) ?>
                    <?= $gem->submit(['name' => 'submit', 'value' => 'Update' ]); ?>
                  </div>
              </div>
  <hr>
  
                <?php foreach($rego as $rg): 
                    $regid = $rg->id;
                    $link = "previewreg/$tpid/$regid";
                    ?>  
                    <div class="row">
                        <div class="col-3"><?= 
                    $gem->linkto(['href' => $m->url . $link,
                        'text' => $rg->fname . '&nbsp;' . $rg->lname ]) ?></div>
                        <div class="col-3"><?= $rg->email ?></div>
                        <div class="col-1"><?= $rg->phone ?></div>
                        <div class="col-2"><?= $rg->created_at ?></div>
                        <div class="col-1"><?php if (!empty($rg->mail)){ echo("mail"); } else {echo("X"); } ?></div>
                        <div class="col-1"><?= $gem->checkbox(['name'=>'chk' . $rg->id, 'checked'=>false]); ?></div>
                    </div>
                    <hr>
                <?php endforeach ?>
              <?php endif ?>
            </form>
</div>
