<style>
    nav  {
        background-image: url("/image/gallery/site/tile-fog2.png");
        color:lightcoral;
    }
    ul.navbar-nav a {
        font-size:1.2em;
    }
    .nav-link {
        font-weight:bold;
    }
    .navbar-brand {
        padding-top:0;
        padding-bottom:0;
    }
    .navbar {
        padding:0 0;
        margin: 0 0;
    }
    .site-logo img {
        max-height:150px;
        padding:5px;
    }

    .view-title {
        color:darkslateblue;
        font-weight:bold;
        font-size:1.5rem;
        padding-right:10px;

    }

</style>
<!--


    ul.Nav {
        background:lightblue !important;
        padding:0px;
        list-style-position:outside;
    }
    li.Nav {
        background:lightyellow !important;
        padding:0px;
        margin:-1px;
    }
    a.Nav {
        padding:0px;
        margin:0px;
    }

-->
<nav class="navbar navbar-expand-lg navbar-light ">
    <div class="view-title">
        <a class="site-logo" href="/"><img src="/image/gallery/site/site-logo.png"></a>
    </div>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
            <include href="generated/dropdowns.phtml"></include>
        </ul>
    </div>
</nav>