<style>
    nav  {
        background-image: url("/image/gallery/site/tile-fog2.png");
        color:lightcoral;
    }
    ul.navbar-nav a {
        font-size:1.2em;
    }
    .nav-link {
        font-weight:bold;
    }
    .navbar-brand {
        padding-top:0;
        padding-bottom:0;
    }
    .navbar {
        padding:0 0;
        margin: 0 0;
    }
    

 @media screen and (max-width: 1600px)
 {
     .site-logo img {
        max-height:150px;
        padding:5px;
    }
    
 .view-title {
        color:darkslateblue;
        font-weight:bold;
        font-size:1.5rem;
        padding-right:10px;
        max-width:300px;
    }
    
    .bigf {
        font-family: georgia;
        font-size:1.5em;
        
    }    
     
 }
 @media screen and (max-width: 1024px) { 
     .site-logo img {
        max-height:80px;
        padding:5px;
    }
    
 .view-title {
        color:darkslateblue;
        font-weight:bold;
        font-size:1.5rem;
        padding-right:10px;
        max-width:80x;
    }
    
    .bigf {
        font-family: georgia;
        font-size:1.2em;
        
    }    
 }
 @media screen and (max-width: 800px) { 
     .site-logo img {
         display:none;
    }
    
    .view-title {
        display:none;
    }
    
    .bigf {
        font-family: georgia;
        font-size:1.2em;
        
    }    
 }
 
 
    

</style>
<!--


    ul.Nav {
        background:lightblue !important;
        padding:0px;
        list-style-position:outside;
    }
    li.Nav {
        background:lightyellow !important;
        padding:0px;
        margin:-1px;
    }
    a.Nav {
        padding:0px;
        margin:0px;
    }

-->
<div class="row justify-content-between"">
    <div class="col view-title">
        <a class="site-logo" href="/"><img src="/cater/gallery/site/left_side.jpg"></a>
    </div>
    <div class="col">

        <div class='bigf'>
            <p><a class='splink' data-toggle='tooltip' href='/contact/index' title='Contact Julie' >Contact Julie for Requirements</a></p>  
            <p><a class='splink' data-toggle='tooltip' href='/map/index' title='Map Location' >Our Location</p> 
             <div class='fb-like' data-share='true' data-width='450' data-show-faces='true'></div>
        </div>
    </div>
    <div class="col view-title float-right">
        <a class="site-logo" href="/"><img src="/cater/gallery/site/right_side.jpg"></a>
    </div>
</div>