<?php
use \WC\Assets; 
use \WC\App;  
use \WC\UserSession; 
$theme=$f3->get('theme');
?><!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <title><?= $m->title ?></title>
        <?= Assets::instance()->CssHeader(); ?>  
</head>
<body>
    <style>
        .site-logo img {
            height:144px;
            padding:5px;
            border-radius:4px;
            border-width:4px;
        }

        .panel-wrap {
            height:144px;
            background-color:papayawhip;
            display: table-cell;
        }
        .view-title {
            background-color: white;
            color:darkslateblue;
            font-weight:bold;
            font-size:1.5rem;
            padding-right:10px;
        }     
    </style>
    <div class="row">
  
            <a class="site-logo " href="/"><img style="min-width:400px;max-width:600px; width:100%;" src="<?= $theme ?>/site-logo.png" class="panel-wrap"></a>
            <?php foreach($m->topPanels  as $panel ): ?>
                <div class="panel-wrap"><?= $panel['summary'] ?></div>
            <?php endforeach; ?>

    </div>
<div class="clear"></div>
<?php
if (!empty($view->nav)):
    $this->insert($view->nav, $this->data);
endif;
?>
<?php
if (!empty($view->flash)):
    foreach ($view->flash as $msg):
        ?>
        <div class="alert alert-<?= $msg['status'] ?> alert-dismissable">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button
            <?= $msg['text'] ?>
            </div>
            <?php
            
        endforeach;
    endif;
    ?>
<?= $this->section('content'); ?>
<footer class="page-footer">
            <div class="row" >
       <div class="col-3">
            <?php
            $f3 = \Base::Instance();
            echo( "Session: " . UserSession::sessionName() );
            ?>
        </div>
        <div class="col-3"> 
            &copy;&nbsp;<?= $f3->get('organization')?>
        </div>
        <div class="col-6">            
            <?= \WC\App::end_stats($f3); ?>
        </div>
    </div>
        </footer>
        <?= Assets::instance()->JsFooter(); ?>
</body>
</html>
